### ISSUE TITLE
What exactly is version 1.2 of elasticluster?

### ISSUE THREAD

**Issue by rdhyee** [gc3-uzh-ch/elasticluster#134]
The current version of elasticluster on PyPi is [1.2](https://pypi.python.org/pypi/elasticluster/1.2).  However, there is no tag or branch named 1.2 in the repository at the moment.  The latest commit (as of writing) has as a [version label 1.1-dev](https://github.com/gc3-uzh-ch/elasticluster/blob/980c31be810a58fc87dd5d14b4726547507ca75e/setup.py#L75).  

Please clarify what version 1.2 actually is.

**Comment by nicolasbaer** [comment]
i tagged version 1.2.0 of elasticluster it points to e9eedae
