### ISSUE TITLE
ansible fails with centos image on GCE.

### ISSUE THREAD

**Issue by YidingZhou** [gc3-uzh-ch/elasticluster#148]
When I try to deploy cluster based on centos image, I got the following error.

TASK: [Setup SSH known hosts file] 
fatal: [frontend001] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_ssh_host_key_dsa_public'", 'failed': True}                                                                                                                    

This happens with centos only. Debian (at least) seems to be fine.

I'm using centos-7-v20150226.

**Comment by dsteinkraus** [comment]
I'm getting this error on Ubuntu as well.

**Comment by verdurin** [comment]
I'm seeing this with a Slurm cluster too, on CentOS 7.1.

**Comment by riccardomurri** [comment]
I think this has been fixed long ago.
