### ISSUE TITLE
Doc request - Example for GlusterFS

### ISSUE THREAD

**Issue by kern3020** [gc3-uzh-ch/elasticluster#149]
Hello,

In the section of the documentation entitled “Playbooks distributed with elasticluster”, I like the way you show config usage examples for each. GlusterFS is the only exception.  
http://elasticluster.readthedocs.org/en/latest/playbooks.html#id6

Can someone provide an example for it? 

-jk

**Comment by riccardomurri** [comment]
I'll be glad to provide one but it might take a few weeks until I have free time to spend on ElastiCluster ...

**Comment by dkoppstein** [comment]
+1
