### ISSUE TITLE
Error creating GCE cluster

### ISSUE THREAD

**Issue by jean997** [gc3-uzh-ch/elasticluster#150]
When creating a GCE cluster I am getting this error:

>ERROR:gc3.elasticluster:Error creating instance `<HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/<project_id>/zones/us-central1-a/instances?alt=json returned "Invalid value for field
'resource.disk.initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/test-cloud'.  Referenced resource was not
found.">`
>ERROR:gc3.elasticluster:could not start node `worker001` for reason `Error creating instance `<HttpError 400 when requesting
https://www.googleapis.com/compute/v1/projects/<project_id>/zones/us-central1-a/instances?alt=json returned "Invalid value for field
'resource.disk.initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/test-cloud'.  Referenced resource was not
found.">``
>ERROR:gc3.elasticluster:Error creating instance `<HttpError 400 when requesting
https://www.googleapis.com/compute/v1/projects/<project_id>/zones/us-central1-a/instances?alt=json returned "Invalid value for field
'resource.disk.initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/test-cloud'.  Referenced resource was not
found.">`
ERROR:gc3.elasticluster:could not start node `controller001` for reason `Error creating instance `<HttpError 400 when requesting
https://www.googleapis.com/compute/v1/projects/<project_id>/zones/us-central1-a/instances?alt=json returned "Invalid value for field
'resource.disk.initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/test-cloud'.  Referenced resource was not
found.">``

In the config file I have the following sections (personal info taken out):

[cloud/google]
provider=google
gce_client_id=
gce_client_secret=
gce_project_id=<projecti_id>

[login/google]
image_user=
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_clients

[cluster/test]
cloud=google
login=google
setup_provider=ansible-gridengine
security_group=default
#Jean replace with special JADE image
image_id=my-private-image
#image_id=ubuntu-1204-precise-v20150127
flavor=n1-highcpu-2
controller_nodes=1
worker_nodes=1
#image_userdata=
ssh_to=controller

[cluster/jade/controller]
flavor=n1-standard-1

I get the same error using either the private image or the public one.

**Comment by YidingZhou** [comment]
i seems to have problem with ubuntu image too. try centos.

**Comment by jean997** [comment]
Thank you so much for responding! I tried with both centos and debian since the documentation says that only debian is currently compatible with GCE. With both I am able to create a cluster but it seems gridengine is not installed:

>qhost
>-bash: qhost: command not found

Sorry if I'm missing something silly - any help would be appreciated!

**Comment by yidingz** [comment]
I can deploy slurm over debian running on GCE. Haven't tried torque or GE. ymmv.

**Comment by jean997** [comment]
Yes - I got slurm with debian to work but now I am trying to use a private image based on debian 7 and getting the original error posted in my first post.

**Comment by nicolasbaer** [comment]
Hi
If you're using a private image you'll have to specify the full url in the configuration option `image_id` starting with http(s)://. Otherwise it will try to create the url to match one of the GCE default images.

Regarding your second issue (Gridengine not installed): Make sure that the `groups` definition in your setup section matches the cluster `nodes`. I think you should change the following parts:
```
[setup/ansible-gridengine]
frontend_groups=gridengine_master
compute_groups=gridengine_clients

[cluster/test]
controller_nodes=1
worker_nodes=1
```

to 

```
[setup/ansible-gridengine]
frontend_groups=gridengine_master
compute_groups=gridengine_clients

[cluster/test]
frontend_nodes=1
compute_nodes=1
```

**Comment by jean997** [comment]
Thanks for helping me trouble shoot this. I tried using the full URL but it still looks like it is trying to fill in the url so I end up with an error like 
 >ERROR:gc3.elasticluster:Error creating instance `<HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/<project_name>/zones/us-central1-a/instances?alt=json returned "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/https://www.googleapis.com/compute/v1/projects/<part of project name>-cloud/global/images/<the url I entered>'.  Must be the URL to a Compute resource of the correct type">`

**Comment by nicolasbaer** [comment]
What version of elasticluster are you using? Could you please try with the latest development version from master branch: https://github.com/gc3-uzh-ch/elasticluster#installing-the-development-version-from-github

**Comment by jean997** [comment]
I have been using version 1.2. When I tried with the development version it was successful! Thank you!
I forgot to mention before that your solution for getting gridengine working was also successful! I do have the problem that regardless of how many CPUs are on the worker node the queue is set up with one slot per node and I have to change it manually. Otherwise it is working well - thank you for all the help.

**Comment by nicolasbaer** [comment]
Great to hear that it is working. I think the setup of the queue per node is a design decision by @arcimboldo, since we wouldn't know what resources (e.g. CPU, I/O, Memory) your specific task relies on and therefore 1 slot per worker seems quite reasonable.
