### ISSUE TITLE
`__init__() got an unexpected keyword argument 'sudo'`

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#156]
I installed Elasticluster following published instructions for install using virtualenv.

When trying to deploy an elasticluster I got the error:

    ERROR:gc3.elasticluster:the setup provider was not able to setup the cluster,
    but the cluster is running by now. Setup provider error message: `__init__()
    got an unexpected keyword argument 'sudo'`

Digging into it, I noticed that the Ansible Playbook interface changed back in November (2014).  See:

  https://github.com/ansible/ansible/commit/5f6db0e16477749c1bccf472150132ca06c50b3b

and specifically the change to lib/ansible/playbook/__init__.py.

    -    sudo_pass        = C.DEFAULT_SUDO_PASS,
         remote_port      = None,
         transport        = C.DEFAULT_TRANSPORT,
         private_key_file = C.DEFAULT_PRIVATE_KEY_FILE,
         callbacks        = None,
         runner_callbacks = None,
         stats            = None,
    -    sudo             = False,
    -    sudo_user        = C.DEFAULT_SUDO_USER,
         extra_vars       = None,
         only_tags        = None,
         skip_tags        = None,
     @@ -77,11 +74,13 @@ def __init__(self,
         check            = False,
         diff             = False,
         any_errors_fatal = False,
    -    su               = False,
    -    su_user          = False,
    -    su_pass          = False,
         vault_password   = False,
         force_handlers   = False,
    +    # privelege escalation
    +    become           = C.DEFAULT_BECOME,
    +    become_method    = C.DEFAULT_BECOME_METHOD,
    +    become_user      = C.DEFAULT_BECOME_USER,
    +    become_pass      = None,

The Elasticluster interface to Ansible (elasticluster/providers/ansible_provider.py) has not changed and so tries to pass parameters that no longer are accepted by Ansible ("sudo" and "sudo_user"):

        pb = PlayBook(
            playbook=self._playbook_path,
            host_list=inventory_path,
            callbacks=playbook_cb,
            runner_callbacks=runner_cb,
            forks=10,
            stats=stats,
            sudo=self._sudo,
            sudo_user=self._sudo_user,
            private_key_file=private_key_file,
        )

The version of Ansible that the Elasticluster install dropped into my virtualenv is indeed very new:

    $ ansible --version
    ansible 1.9.1

To resolve this, I uninstalled Ansible and re-installed 1.7.2, which at a glance appeared to be one of or the last version without the above noted change.  Here is the list of Ansible releases:

  http://releases.ansible.com/ansible/

1.7.2 is stamped the same date (November 24) as the noted change.

    $ pip uninstall ansible
    <snip>
    Proceed (y/n)? y
      Successfully uninstalled ansible-1.9.0.1

    $ pip install ansible==1.7.2
    Collecting ansible==1.7.2
    <snip>
    Installing collected packages: ansible
      Running setup.py install for ansible
    Successfully installed ansible-1.7.2

    $ ansible --version
    ansible 1.7.2

I was then able to deploy a cluster which successfully installed gridengine on Google Compute Engine.

**Comment by vtrubets** [comment]
I just ran into the same error. Downgrading to ansible 1.7.2 as @mbookman suggests resolves this.
