### ISSUE TITLE
Add `elasticluster import/export` subcommand, to move the cluster definition to another host

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#161]
I would like to see two new subcommands in ElastiCluster: `export` and `import`.

Their purpose is to move cluster definitions from one host to another:
say, I create cluster "foo" on my laptop, then run `elasticluster
export foo` and get a file `foo.zip` that I can copy on the cluster
frontend.  There I would run `elasticluster import foo.zip` and after
that I can manage the cluster from the frontend itself.

This can of course be already accomplished, but one needs to know how
the ElastiCluster "storage" directory is organized and what files to
copy. The export/import commands are meant to remove this need from
the user.

Proposed interface:

        elasticluster export CLUSTERNAME

        Create a `.zip` file with the cluster definition data,
        suitable for importing in another ElastiCluster installation.

        Options:

          -o, --output-file FILE

            Save cluster definition in the given file.  A `.zip`
            extension is appended if it's not already there.  By
            default, the output file named like the cluster.

        --------

        elasticluster import FILE[.zip]

        Import a cluster definition from FILE into local storage.
        After running this command, it will be possible to operate
        on the imported cluster as if it had been created locally.

        The FILE to be imported must have been created with
        `elasticluster export`.

        If a cluster already exists with the same name of the one
        being imported, the import operation is aborted and
        `elasticluster` exists with an error.

**Comment by arcimboldo** [comment]
After the latest changes to the master branch, I'm not sure this is needed at all.
If saving clusters as YAML (now the default), you can easily copy the yaml file and possibly change manually a few attributes (specifically: path to the user ssh key files).

**Comment by riccardomurri** [comment]
Well, the whole point is *not doing any manual step* other than export/import of the `.zip` file.

**Comment by arcimboldo** [comment]
On Mon, May 25, 2015 at 4:55 PM, Riccardo Murri <notifications@github.com>
wrote:

> Well, the whole point is *not doing any manual step* other than
> export/import of the .zip file.
>
>
I think the only issue is with the public/private ssh keys. For these, the
only option is override their values using the corresponding configuration
options.

We can either to it everytime the cluster is loaded, or use the "migrate"
subcommand we already have. Which one do you prefer? (I prefer the latter)

.a.

-- 
antonio.s.messina@gmail.com
arcimboldo@gmail.com
GC3: Grid Computing Competence Center
http://www.gc3.uzh.ch/
University of Zurich
Winterthurerstrasse 190
CH-8057 Zurich Switzerland

**Comment by riccardomurri** [comment]
I'm not sure I'm following:

> I think the only issue is with the public/private ssh keys.

Did you reduce the number of stored files per cluster to just 1?  (It was 2 before the latest changes.)

And then, why do we have to "do it everytime the cluster is loaded"?  If those paths have to be changed, why not make it part of the `import` subcommand?

Finally: still, even if ElasitCluster's storage format has changed to a saner one, I would like elasticluster to copy files in/out of its storage directory, without me hunting for the right file in hidden folders.  In other words: even if there is now only 1 file and it's YAML, I still do see a need for `export`/`import` subcommands.
