### ISSUE TITLE
Install fails: error: pbr 0.11.0 is installed but pbr<2.0,>=1.3 is required by set(['oslo.utils'])

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#174]
Running an install of Elasticluster in a clean local workspace currently fails with:

$ python setup.py install
...
Installed /usr/local/google/home/mbookman/scratch/workspace/elasticluster.clean/lib/python2.7/site-packages/monotonic-0.2-py2.7.egg
error: pbr 0.11.0 is installed but pbr<2.0,>=1.3 is required by set(['oslo.utils'])

I'll submit a PR for this shortly. Simple fix is to update setup.py:

-    'pbr==0.11.0',
+    'pbr>=0.11.0',

but we should be able to just remove the version completely here now. After changing the above version 1.3 of pbr was installed and everything seems to work fine:

$ pip show pbr | grep ^Version
Version: 1.3.0

**Comment by nicolasbaer** [comment]
relates to #162

**Comment by nicolasbaer** [comment]
fixed in f055e2b
