### ISSUE TITLE
Removing nodes should remove records from known_hosts file

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#176]
Have found that when I have a cluster in which I remove and add nodes that the adding of nodes often fails because Elasticluster cannot connect to the new node. The underlying problem is that the IP address for the new node is a re-use of a previous IP address. Thus the associated host key in the cluster's known_hosts file is the old one.

I'm not sure where the fix for this should go. It seems like it could be in node.stop() or cluster.remove_node(). It also looks to me like in order to remove a line from the cluster's known_hosts file requires using paramiko to recreate the file (I see no remove/delete method).

I do have a PR which I will send in a moment, which simply improves the messaging reported. This improved messaging better surfaces the underlying connection problem.

**Comment by nicolasbaer** [comment]
That is something we did not handle yet, true. The logic should go into `cluster.remove_node` and yes, it looks like we would have to recreate the file.

**Comment by riccardomurri** [comment]
Fixed by @whrc in #554
