### ISSUE TITLE
Another pbr installation problem

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#179]
I'm trying to install the current GitHub version and there is another pbr problem. This time, it is a dependency in the debtcollector package, which has the following requires.txt:

pbr<2.0,>=1.3
Babel>=1.3
six>=1.9.0
wrapt>=1.7.0 # BSD License

which then conflicts with version 0.11.0 that has been installed.

**Comment by nicolasbaer** [comment]
fixed in f055e2b
