### ISSUE TITLE
playbooks do not start/restart slurm-llnl-slurmdbd

### ISSUE THREAD

**Issue by ewiger** [gc3-uzh-ch/elasticluster#199]
**slurm-llnl-slurmdbd** booting order is wrong or simply is not started. As a suggestion maybe a playbook can contain a simple test if the configure SLURM cluster can submit and executed jobs via `srun` or `sbatch`.

**Comment by riccardomurri** [comment]
I think this is a duplicate of issue #188

**Comment by ewiger** [comment]
It is indeed a duplicate. After checking my notes I think you have also the other issues covered. Thank you.
