### ISSUE TITLE
Playbook debugging

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#202]
I'm looking into the SSH host key problem when using CentOS 7 images, #184, and it would be very helpful if I could set the verbosity within the ansible-playbook calls made by elasticluster, as well as for what elasticluster is doing itself.

At the moment, it makes no sense, in that the error refers to DSA host keys even though I've edited the .j2 template to use ecdsa instead, but this is hard to pin down. 

I've tried running the playbooks manually, but they're missing too much other configuration and they fail before reaching the task I'm investigating.

**Comment by riccardomurri** [comment]
Can you please try ElastiCluster from the branch `feature/forward-compatibility-with-ansible`?  The experimental code there will propagate any `--verbose` option passed to ElastiCluster down to Ansible.  So `-vvv` will put *both* ElastiCluster *and* Ansible in DEBUG log mode.

**Comment by riccardomurri** [comment]
Fixed code now available in the "develop" branch. Please test and let me know if this solves your problem.

**Comment by verdurin** [comment]
Yes, the verbosity setting is being passed through to Ansible now, as I can see when provisioning of a compute node fails.

Thanks.

**Comment by verdurin** [comment]
This doesn't appear to be working with the `master` branch as of today, which I have to use to test your Slurm changes.

Even with `-vvvvv` I can't see more than the default level of detail.

**Comment by riccardomurri** [comment]
You're right: apparently the log level is reset back to `logging.WARNING` somewhere between the start of `main()` and the point where Ansible is actually invoked, so no matter how many `-v`'s appear on ElastiCluster's command-line, Ansible is never sees them.

**Comment by riccardomurri** [comment]
This should be really fixed in <https://github.com/gc3-uzh-ch/elasticluster/commit/f4bc71fdef74a106c389fcd60386ecba6b6b37ce>.  Can you please confirm?

**Comment by verdurin** [comment]
Looks fixed to me - thanks.
