### ISSUE TITLE
global name 'FlavorError' is not defined

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#211]
elasticluster/providers/openstack.py
from elasticluster.exceptions
missing FlavorError

ERROR:gc3.elasticluster:could not start node `compute002` for reason `global name 'FlavorError' is not defined`

**Comment by riccardomurri** [comment]
Can you please try with the latest code from branch "master"?

**Comment by riccardomurri** [comment]
Fix available in the "master" branch already.  Can you please test and report if this fixes the issue?

**Comment by pinguinkiste** [comment]
FWIW, I've never seen this one since I use ElastiCluster on OpenStack, but started on a `master` that had the fix. Assume fixed and close the issue?

**Comment by riccardomurri** [comment]
I guess so - @smaffiol please re-open if you run into this again.
