### ISSUE TITLE
ERROR:gc3.elasticluster:while adding a new node of type `compute`, I was unable to find a good name for it.

### ISSUE THREAD

**Issue by mbookman** [gc3-uzh-ch/elasticluster#220]
I was scaling up a cluster from 60 nodes to 90 and got the error:

ERROR:gc3.elasticluster:while adding a new node of type `compute`, I was unable to find a good name for it.

Looking at https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/cluster.py:

        if not name:
            nodenames = [i.name for i in self.nodes[kind]]
            numnodes = len(nodenames)
            for index in range(numnodes+1, numnodes+50):
                _name = "%s%03d" % (kind, index)
                if _name in nodenames:
                    continue
                else:
                    name = _name
                    break

        if not name:
            log.error("while adding a new node of type `%s`, I was unable to find a good name for it.", kind)
            return None

I believe the problem is this restriction:

            for index in range(numnodes+1, numnodes+50):

while the number of nodes in the cluster is currently 60, it had reached a peak of 110, so it is trying to find an available node name in the range 61 to 100 and not finding it.

The quick fix here is to set this range to be much larger than 50, make this a while instead of a for (essentially unbounded), or find the largest used value in the nodenames array.

But I'm curious what is the intended logic for node name reuse? Why doesn't this just start at 1?

**Comment by mbookman** [comment]
BTW, I confirmed that changing the increment at top of the range 50 to 500 makes the problem go away.

**Comment by riccardomurri** [comment]
> But I'm curious what is the intended logic for node name reuse? Why doesn't this just start at 1?

I'm puzzled about this as well... maybe @arcimboldo and @nicolasbaer can provide some hints?

**Comment by riccardomurri** [comment]
I have committed different fixes on the "master" and "develop" branches: the one in "master" is the trivial fix (just keep trying with higher numbers), the one in "develop" is -more importantly- better testable but requires much more extensive code changes.

I haven't tested either in the wild, though (vacations are too close!), so I would be grateful if you could report if they do actually work.

**Comment by mbookman** [comment]
The fix committed to master seems fine. Picked up the latest last week and have scaled up a cluster in the following progression:

  * 1 compute node
  * 10 compute nodes
  * 20 compute nodes
  * 50 compute nodes
  * 70 compute nodes
  * 100 compute nodes
  * 120 compute nodes

Created another cluster which I scaled up from 0 to 60 right away. Then scaled it from 60 to 120 without a problem.
