### ISSUE TITLE
Cannot terminate a cluster when resources have been already terminated (e.g. manually)

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#226]
In case resources associated to a given cluster have been terminated outside the scope of elasticluster (e.g. manually), running: elasticluster stop [cluster name]
gives:
...
ERROR:gc3.elasticluster:could not stop instance `ecad264b-3ba8-4d22-a9aa-0b2c14b4ec46`, it might already be down.
WARNING:gc3.elasticluster:Not all instances have been terminated. Please rerun the `elasticluster stop test`

and then elasticluster keeps reporting the cluster as available.
I suspect the same behaviour happen when only partial resources have been terminated, thus preventing elasticluster to properly shut-down an existing cluster

Regards,
Sergio

**Comment by riccardomurri** [comment]
I'm unsure whether this is a more general case of issue #207 

At any rate, it looks like ElastiCluster should just ignore errors in updating info about cluster nodes when the cluster is about to stop.
