### ISSUE TITLE
Clarification requested in Configuration section

### ISSUE THREAD

**Issue by PeterVermont** [gc3-uzh-ch/elasticluster#234]
http://elasticluster.readthedocs.org/en/latest/configure.html

This says that the template file is automatically created when elasticluster first run but running without any arguments gives the usage message and does not deploy the default configuration file.

Either fix it so that running without args deploys or re-write to something like this:

After installing elasticluster for the first time, we suggest you run the following command:

elasticluster list-templates

When elasticluster is run for the first time, if no configuration file is found it will copy a template configuration file in ~/.elasticluster/config. Such template is fully commented and self documented.

If you don’t already have a configuration file, this command will create one for you. Of course, the file is not complete, as it does not contain any authentication information, and you will get an error similar to the following:

**Comment by riccardomurri** [comment]
I have tried to amend the instruction text in the "master" branch following your suggestions.  Thanks!
