### ISSUE TITLE
Different image types for frontend and compute nodes

### ISSUE THREAD

**Issue by jsharpe** [gc3-uzh-ch/elasticluster#245]
I should be able to specify different node types for frontend and compute nodes as I may want a small e.g. t2.micro frontend and large compute nodes.

**Comment by riccardomurri** [comment]
This is already possible::

    [cluster/ubuntu]
    cloud=s3it-playground
    setup_provider=slurm

    # Ubuntu 14.04.4
    image_id=53477a02-df92-409c-8794-7cecd4a5ed64
    login=ubuntu

    security_group=default

    frontend_nodes=1
    compute_nodes=10
    ssh_to=frontend

    [cluster/ubuntu/frontend]
    flavor=1cpu-4ram-hpc

    [cluster/ubuntu/compute]
    flavor=8cpu-32ram-hpc

Where would be a good place in the documentation to add this info?
