### ISSUE TITLE
cluster fails to resize when removing all compute nodes

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#247]
* Created a slurm cluster with 2 compute nodes
* Remove both compute nodes with:
$ elasticluster resize -r 2:compute 

Error on Task
TASK: [Configure slurm] ******************************************************* 
...
fatal: [frontend001] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'slurm_clients'", 'failed': True}

Failure persist even if:
$ elasticluster setup

**Comment by riccardomurri** [comment]
Technically, this should be straightforward (if verbose) to fix: one needs to test for that `slurm_clients` exists and use a default empty value in case it doesn't.

However, this potentially makes the playbooks quite verbose and unreadable -- we should do that for every host group, not just `slurm_clients`.

Is there a strong use case for this feature?

**Comment by riccardomurri** [comment]
Anyway: [SLURM does not allow a cluster with no compute nodes][1]: the `slurmctld` will refuse to start with message `fatal: no NodeName information available`.

What I can do is change the playbooks to allow that a node be *both* a frontend/controller node *and* a worker node.  Then you can resize the cluster to remove all worker nodes except -of course- the frontend/controller.  Would this help?

[1]: https://github.com/SchedMD/slurm/blob/master/src/common/node_conf.c#L578

**Comment by smaffiol** [comment]
mmm..., with this approach all frontend nodes will also become compute
nodes - and thus starting potentially heavy jobs on the same node that is
also - by default configuration - acting as NFS server....
maybe not

S.

2016-05-14 3:14 GMT+02:00 Riccardo Murri <notifications@github.com>:
