### ISSUE TITLE
Problem installing from GitHub

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#249]
I'm trying to install from GitHub and am seeing the same error, both in `master` and `develop`:

```
Searching for funcsigs>=0.4
Reading https://pypi.python.org/simple/funcsigs/
Best match: funcsigs 1.0.1
Downloading https://pypi.python.org/packages/ab/5b/a6dff630fe5b68a4d2a049b6d95b51ad1510fb72e9606d656feb2c34efd8/funcsigs-1.0.1.tar.gz#md5=c2d84de116ce1aba0dc844a359cd20dd
Processing funcsigs-1.0.1.tar.gz
Writing /tmp/easy_install-YlNQFx/funcsigs-1.0.1/setup.cfg
Running funcsigs-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YlNQFx/funcsigs-1.0.1/egg-dist-tmp-ezFWww
error: Setup script exited with error in funcsigs setup command: Invalid environment marker: python_version<"2.7"
```

This is on a CentOS 7.2 host.

**Comment by riccardomurri** [comment]
Hmmm, `python_version<"2.7"` looks like a perfectly valid environment marker from [PEP-496][1] to me.  It could be that RHEL/CentOS ships by default a version of setuptools that's too old and not compatible with environment markers.  What versions is setuptools on your CentOS install?

[1]: https://www.python.org/dev/peps/pep-0496/

**Comment by verdurin** [comment]
`0.9.8`

**Comment by riccardomurri** [comment]
GitHub's tag only let me go back in history to setuptools 8.2; according
to the change log, though, environment marker support was introduced in
0.7 but substantially rewritten between 20.2--20.5.

Could you please try upgrading to setuptools >= 20.5 and then installing
ElastiCluster again?

**Comment by verdurin** [comment]
Yes, I did upgrade to setuptools 20.10.1 and installation did then work (from the master branch).

**Comment by riccardomurri** [comment]
I have tried to fix this by requiring Setuptools >= 20.6.8 but it doesn't work at the moment because of https://github.com/pypa/setuptools/issues/568

**Comment by riccardomurri** [comment]
I think this is fixed in commit cc54eeefa <https://github.com/gc3-uzh-ch/elasticluster/commit/cc54eeefaeba32c24c685dfe4ac75eae48585b11>

**Comment by verdurin** [comment]
@riccardomurri - just installed from GitHub on a similar CentOS 7.2 VM and it worked - thanks.

**Comment by riccardomurri** [comment]
Was this re-opened because of #251 ?

**Comment by verdurin** [comment]
No - I just thought you might want to close it yourself. I'm happy that it's fixed.

**Comment by riccardomurri** [comment]
Fix pushed to the "master" branch, therefore I'm marking this issue as solved.
