### ISSUE TITLE
multiple possible networks error although i'm specifying the networks_id parameter (OpenStack)

### ISSUE THREAD

**Issue by GlastonburyC** [gc3-uzh-ch/elasticluster#254]
I keep getting the following errors:
```
elasticluster -c .elasticluster/config start slurm -n mycluster
Starting cluster `mycluster` with 1 frontend nodes.
Starting cluster `mycluster` with 2 compute nodes.
(this may take a while...)
2016-05-25 18:16:24 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[8560] WARNING DeprecationWarning: The novaclient.v2.images module is deprecated and will be removed after Nova 15.0.0 is released. Use python-glanceclient or python-openstacksdk instead.
2016-05-25 18:16:24 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[8560] ERROR could not start node `compute002` for reason `Multiple possible networks found, use a Network ID to be more specific. (HTTP 400) (Request-ID: req-f26edfa4-82ad-440d-9efd-d0f81c26bab0)`
2016-05-25 18:16:24 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[8560] ERROR could not start node `frontend001` for reason `Multiple possible networks found, use a Network ID to be more specific. (HTTP 400) (Request-ID: req-064a9032-a811-4efc-921e-3ac24949717c)`
2016-05-25 18:16:24 rna-seq-map-ref-bastion.novalocal gc3.elasticluster[8560] ERROR could not start node `compute001` for reason `Multiple possible networks found, use a Network ID to be more specific. (HTTP 400) (Request-ID: req-7bd281ff-62e1-4739-9227-ab2ea5743e20)`
```
My config file is the following:

```
[cloud/openstack]
provider=openstack
auth_url=OS_AUTH_URL
username=USERNAME_CENSORED
password=PASSWORD_CENSORED
project_name=rna-seq-map-ref

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=blah
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_workers

[cluster/slurm]
cloud=openstack
network_ids=7d326b6a-fae5-4c4f-87e4-e7b5a3628fc1 # Apparently you can use the subnet ID, tried this, same error
login=ubuntu
setup_provider=ansible-slurm
security_group=icmp-ssh-rna-seq-map-ref

image_id=CentOS-7.2-1604
flavor=m2.lul
frontend_nodes=1
compute_nodes=2
ssh_to=frontend

```
This is the version
`elasticluster version 1.3.dev0`

**Comment by riccardomurri** [comment]
Hmmm... weird, I have a similar setup (OpenStack + multiple neutron
networks) and it works::

    [cluster/ubuntu]
    cloud=s3it-playground
    # ...
    network_ids=c86b320c-9542-4032-a951-c8a068894cc2

Can you please try:

- removing the `# Apparently you can ...` comment from the
  `network_ids` line -- I think that Python will only consider `#` as
  a comment-starting character if it's the first non-blank char on a
  line.

- if that does not work, can you please post the output of `openstack
  network list` and `neutron net-list` for your OpenStack project?

**Comment by GlastonburyC** [comment]
I removed all comments and it had no effect.
`[cglastonbury@rna-seq-map-ref-bastion ~]$ openstack network list
+--------------------------------------+---------------------+--------------------------------------+
| ID                                   | Name                | Subnets                              |
+--------------------------------------+---------------------+--------------------------------------+
| 01744de8-45d1-4c5b-800c-63da6aebeb2a | pilot6-net          | b818a040-ab35-4828-9a6b-eb3f2e1b480a |
| 01c812a1-2781-4a9c-a172-5c0a7f2e8b34 | 215_project_net     | 7049821b-e10e-492c-b482-e6bce2e0ce03 |
| 07d9465a-2576-40f1-b276-a9b01a606db7 | qmul-dev-net3       | fa7b6c2d-1257-4280-8379-37a4e1cb8e35 |
| 127837f1-879b-4f01-93da-f72f44efe7d8 | net_provider_200    | 65b20a20-e587-4fba-bfff-42e8316c3646 |
| 1d095116-1e4f-4ec9-a594-71a81bea38a7 | docana_private      | b1ffec13-42ce-491f-b87c-ed0bdc3f3467 |
| 33b18122-909b-41ee-acec-9e0dfcd6a86d | ocf_test            | 4961016b-9922-4023-8878-bd68ee375a4c |
| 34ecc552-228a-494f-afdb-695b15f8ad5f | my_network          | fb074b31-9ef8-48a5-97d1-c20d16ebd909 |
| 5f784843-37ce-4c2f-bbb6-e4b426dd02d4 | net_provider_712    | b314d076-a728-4639-b0db-d9a7d5b0f267 |
| 64f1ffe8-9c2a-4d88-9932-6b3ab8af5024 | pilot5-net          | 17a90510-a0bd-4a23-baba-0fe2e89d5de1 |
| 73d6dcff-d739-4434-93f4-992acde3fa8e | pilot9-net          | dbf9e422-9fa3-4dd1-8d69-2e2fc2e46d7e |
| 74af2c0a-46c6-4f69-8d17-819a721b4b5c | arvados-net         | 92f1b560-f024-4993-8d12-3ea77303df96 |
| 7d326b6a-fae5-4c4f-87e4-e7b5a3628fc1 | rna-seq-map-ref-net | a50cc147-41e9-4bd2-a6e6-51c94e799a73 |
| 8a7701e6-1221-4373-b660-668cbd04e214 | vanloo-net          | 940242c8-6160-4d95-9079-e3dff92bc603 |
| 8ee52c16-cbf1-4537-9a73-b4ef40c5faa4 | ops-net             | 00fc50dd-767e-47f7-b754-2cc15a31eea4 |
| a0fcd6c7-61dc-4dd9-97d2-1c119dff66ca | pilot8-net          | 6436b8ae-0c7a-4218-be23-fd6f3e8229dd |
| a4b9663c-e00b-41d2-b4f4-8459058ca097 | StocCal-net         | dfeef5a6-7628-46bb-be08-30b6555fb055 |
| a91ef011-be3e-4272-a430-596b0b2b3c3c | vanloo-storage-711  | 3416a906-da7f-4828-984a-bb9413a64cc5 |
| ae58cb3b-6329-4568-aa8c-2bd6747b8d07 | provider-216        | 997430af-c6a0-4419-83f2-b27968d1b78e |
| b8841c22-8187-4ec0-ba1e-552ff48c4561 | test_proj_net       | 7a3348f8-e259-430c-a1c2-6a63099a2205 |
| bbbddb45-cdf3-4777-bffc-d396686488ab | RET-net-224         | b7dd2fe2-1937-406e-b260-b310d73e3f8e |
| c4f261aa-173d-4feb-b9a4-c1fe4a2729c6 | public_api          | 1b222f5e-ef3f-4347-a915-69d04382ee95 |
| d08703a3-92e8-47a7-9839-f986ed3a39be | pilot7-net          | bb15cfd3-1df7-4d02-81d7-f02eb47f5143 |
| d2481cac-b068-4b13-81a6-dd0d7bff7798 | vanloo-project-net  | e57a5b1b-7513-471c-9e78-f8487e7ee232 |
| d2e897c6-da16-4de0-9219-a8288461f215 | my_network2         | d17e3feb-b10e-4b65-8961-c390e670a5d3 |
| d4ff1114-1b68-4444-a3ab-4ec0286cc0a6 | denaxas-net         | 8c2eaf8c-9473-4d30-b173-39cf83c2aed6 |
| ee40ef4d-eae9-40f9-b037-80e542f5804b | admin-net           | d4b99860-9c48-47a3-8459-2ebc6b5ec696 |
| efeef77b-16bb-4120-be0f-caf4f2356b8d | gosgene-net         | ca5cbd3c-1f95-4be1-a280-a3791a161afc |
+--------------------------------------+---------------------+--------------------------------------+`

`[cglastonbury@rna-seq-map-ref-bastion ~]$ neutron net-list
+--------------------------------------+---------------------+------------------------------------------------------+
| id                                   | name                | subnets                                              |
+--------------------------------------+---------------------+------------------------------------------------------+
| 01744de8-45d1-4c5b-800c-63da6aebeb2a | pilot6-net          | b818a040-ab35-4828-9a6b-eb3f2e1b480a 10.2.217.0/24   |
| 01c812a1-2781-4a9c-a172-5c0a7f2e8b34 | 215_project_net     | 7049821b-e10e-492c-b482-e6bce2e0ce03 10.10.215.0/24  |
| 07d9465a-2576-40f1-b276-a9b01a606db7 | qmul-dev-net3       | fa7b6c2d-1257-4280-8379-37a4e1cb8e35 10.2.221.0/24   |
| 127837f1-879b-4f01-93da-f72f44efe7d8 | net_provider_200    | 65b20a20-e587-4fba-bfff-42e8316c3646 10.1.42.0/24    |
| 1d095116-1e4f-4ec9-a594-71a81bea38a7 | docana_private      | b1ffec13-42ce-491f-b87c-ed0bdc3f3467 192.168.0.0/24  |
| 33b18122-909b-41ee-acec-9e0dfcd6a86d | ocf_test            | 4961016b-9922-4023-8878-bd68ee375a4c 10.21.16.0/21   |
| 34ecc552-228a-494f-afdb-695b15f8ad5f | my_network          | fb074b31-9ef8-48a5-97d1-c20d16ebd909 10.0.9.0/24     |
| 5f784843-37ce-4c2f-bbb6-e4b426dd02d4 | net_provider_712    | b314d076-a728-4639-b0db-d9a7d5b0f267 10.254.192.0/18 |
| 64f1ffe8-9c2a-4d88-9932-6b3ab8af5024 | pilot5-net          | 17a90510-a0bd-4a23-baba-0fe2e89d5de1 10.2.214.0/24   |
| 73d6dcff-d739-4434-93f4-992acde3fa8e | pilot9-net          | dbf9e422-9fa3-4dd1-8d69-2e2fc2e46d7e 10.2.220.0/24   |
| 74af2c0a-46c6-4f69-8d17-819a721b4b5c | arvados-net         | 92f1b560-f024-4993-8d12-3ea77303df96 10.2.212.0/24   |
| 7d326b6a-fae5-4c4f-87e4-e7b5a3628fc1 | rna-seq-map-ref-net | a50cc147-41e9-4bd2-a6e6-51c94e799a73 10.2.223.0/24   |
| 8a7701e6-1221-4373-b660-668cbd04e214 | vanloo-net          | 940242c8-6160-4d95-9079-e3dff92bc603 10.2.210.0/24   |
| 8ee52c16-cbf1-4537-9a73-b4ef40c5faa4 | ops-net             | 00fc50dd-767e-47f7-b754-2cc15a31eea4 10.25.30.0/24   |
| a0fcd6c7-61dc-4dd9-97d2-1c119dff66ca | pilot8-net          | 6436b8ae-0c7a-4218-be23-fd6f3e8229dd 10.2.219.0/24   |
| a4b9663c-e00b-41d2-b4f4-8459058ca097 | StocCal-net         | dfeef5a6-7628-46bb-be08-30b6555fb055 10.2.222.0/24   |
| a91ef011-be3e-4272-a430-596b0b2b3c3c | vanloo-storage-711  | 3416a906-da7f-4828-984a-bb9413a64cc5 10.253.192.0/18 |
| ae58cb3b-6329-4568-aa8c-2bd6747b8d07 | provider-216        | 997430af-c6a0-4419-83f2-b27968d1b78e 10.2.216.0/24   |
| b8841c22-8187-4ec0-ba1e-552ff48c4561 | test_proj_net       | 7a3348f8-e259-430c-a1c2-6a63099a2205 10.28.28.0/24   |
| bbbddb45-cdf3-4777-bffc-d396686488ab | RET-net-224         | b7dd2fe2-1937-406e-b260-b310d73e3f8e 10.2.224.0/24   |
| c4f261aa-173d-4feb-b9a4-c1fe4a2729c6 | public_api          | 1b222f5e-ef3f-4347-a915-69d04382ee95 10.0.42.0/24    |
| d08703a3-92e8-47a7-9839-f986ed3a39be | pilot7-net          | bb15cfd3-1df7-4d02-81d7-f02eb47f5143 10.2.218.0/24   |
| d2481cac-b068-4b13-81a6-dd0d7bff7798 | vanloo-project-net  | e57a5b1b-7513-471c-9e78-f8487e7ee232 10.16.1.0/24    |
| d2e897c6-da16-4de0-9219-a8288461f215 | my_network2         | d17e3feb-b10e-4b65-8961-c390e670a5d3 10.0.5.0/24     |
| d4ff1114-1b68-4444-a3ab-4ec0286cc0a6 | denaxas-net         | 8c2eaf8c-9473-4d30-b173-39cf83c2aed6 10.2.213.0/24   |
| ee40ef4d-eae9-40f9-b037-80e542f5804b | admin-net           | d4b99860-9c48-47a3-8459-2ebc6b5ec696 10.2.215.0/24   |
| efeef77b-16bb-4120-be0f-caf4f2356b8d | gosgene-net         | ca5cbd3c-1f95-4be1-a280-a3791a161afc 10.2.211.0/24   |
+--------------------------------------+---------------------+------------------------------------------------------+`

**Comment by riccardomurri** [comment]
I cannot see anything that's obviously wrong.

Let's compare versions then.  What versions of the OpenStack client API is installed where you are running ElastiCluster?  (e.g., run `pip freeze | fgrep novaclient`)

**Comment by GlastonburyC** [comment]
python-novaclient==4.0.0

**Comment by GlastonburyC** [comment]
No worries, all fixed. I think there was something buggy about my root account having a different config file to the user account. All works now! Thanks for your help and response.

**Comment by riccardomurri** [comment]
All is well that ends well :-)
