### ISSUE TITLE
Broken on CentOS 7 due to requiretty in `/etc/sudoers`

### ISSUE THREAD

**Issue by pinguinkiste** [gc3-uzh-ch/elasticluster#267]
I tried to get ElastiCluster run with CentOS 7 images. It fails in the setup task because CentOS has `Defaults requiretty` in `/etc/sudoers` but ansible does not run with a TTY (obviously). This is with `image_sudo=True` in the config. If I change it to `image_sudo=False` it runs the first task but fails when adding the EPEL repository with: `fatal: [frontend001]: FAILED! => {"changed": true, "failed": true, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\n"]}`

All of my attempts to work around that (by removing the line from `/etc/sudoers` have failed so far. Any pointers on how to fix this would be great.

Best,

Manuel

**Comment by verdurin** [comment]
@pinguinkiste - see #183 - there is a workaround

**Comment by pinguinkiste** [comment]
Thanks @verdurin! I wonder why the issue did not turn up in my search!? Anyway, setting the environment variable works. Closing this issue.
