### ISSUE TITLE
Setting up a parallel environment on Grid Engine

### ISSUE THREAD

**Issue by tomsing1** [gc3-uzh-ch/elasticluster#274]
If I understand correctly, a SLURM cluster can be configured to automatically use the available cores on each node, as requested in [this](https://github.com/gc3-uzh-ch/elasticluster/pull/120) closed issue. Is something similar possible for a gridengine cluster?

I found [this stackoverflow post](http://stackoverflow.com/questions/35140775/specifying-parallel-environment-on-google-compute-engine-using-elasticluster/35560896#35560896) that explains how to configure the master manually. The responding author suggests to file an issue here, to see if this functionality could be included by default.

Would it be possible to configure a parallel environment in e.g. in the elasticluster configuration file? Or alternatively, could this setp be added to the [Gridengine playbook](elasticluster/elasticluster/share/playbooks/roles/gridengine/tasks/master.yml)?

Thanks a lot for making this great tool available!

**Comment by riccardomurri** [comment]
Yes, it should be possible.

I'll try to get it done for the 1.4 release.

**Comment by tomsing1** [comment]
Great! Thanks a lot for adding it to the to-do list.

**Comment by jmrk84** [comment]
Also interested in this. :)

**Comment by jmrk84** [comment]
I added parallel environment creation to the gridengine playbooks - if you are interested before I get to creating a pull request, send me a message.

**Comment by riccardomurri** [comment]
@jmrk84 Fantastic!  If you do not have time to create a PR, just send me the updated playbooks and I'll take care of merging.  Thank you very much!

**Comment by riccardomurri** [comment]
Finally fixed in https://github.com/gc3-uzh-ch/elasticluster/commit/3181efb04ac9f04f3971d120dce20e04f5a47f8a at long last!
