### ISSUE TITLE
Add support for Keystone V3 API

### ISSUE THREAD

**Issue by arcimboldo** [gc3-uzh-ch/elasticluster#291]
If OpenStack is configured with multiple domains (https://wiki.openstack.org/wiki/Domains) and you want to use an user which is not member of the "default" domain, you _need_ to use V3 authentication when interacting with Keystone.

Elasticluster doesn't currently support Keystone V3, but we should support it.

**Comment by cbrown2** [comment]
Submitted PR for this #428

**Comment by cbrown2** [comment]
This has been merged so I guess can now be closed?

**Comment by riccardomurri** [comment]
Yes, indeed
 Can you please do it? (I am traveling without my computer)

**Comment by cbrown2** [comment]
@riccardomurri sorry, don't have the permissions

@arcimboldo ?
