### ISSUE TITLE
resize an existing cluster with different flavor

### ISSUE THREAD

**Issue by radaniba** [gc3-uzh-ch/elasticluster#301]
Hello all,

Can we use the resize command to add different compute to an already existing cluster but with different flavor ?

I looked at resize options and I don't think this is something doable, hoping am wrong

Any help or hint will be more than welcome

Thanks

**Comment by riccardomurri** [comment]
> Can we use the resize command to add different compute to an already
existing cluster but with different flavor ?
>

Yes, but you nerd to change the configurazione file to use the new flavor,
or add a differenti compute nodes kind with the new flavor.

(As you already noted, options of the "resize" command do not let you
override the configyred flavor.)

**Comment by radaniba** [comment]
Thank you @riccardomurri 

I tried this 

```
[cluster/gridengine]
cloud=collab
login=ubuntu
setup_provider=ansible-gridengine
security_group=raniba-sg
security_group=default
image_id=b2527be2-562f-4477-b722-b0ae90025edf
flavor=c1.medium
frontend_nodes=1
compute_nodes=20
ssh_to=frontend

[cluster/gridengine/compute]
flavor=c1.large
compute_nodes=2

[cluster/gridengine/compute]
flavor=c1.xlarge
```

And then went with `eslasticluster start gridengine` then `elasticluster ssh gridengine` but the added compute nodes were not takn in consideration

Should I stop/destroy the cluster  first ?

**Comment by riccardomurri** [comment]
Hello @radaniba,

in order to resize a cluster with nodes of a different
flavor, you need to define a *new* node kind and then resize
by adding nodes of that kind.  The config you posted defines
the "compute" node kind twice so the latter definition overwrites
the former.

I would use something like the following instead::

```
[cluster/gridengine]
# ... rest as in your posted example
compute_nodes=20
xlargecompute_nodes=0
ssh_to=frontend

[cluster/gridengine/compute]
flavor=c1.large
compute_nodes=2

[cluster/gridengine/xlargecompute]
flavor=c1.xlarge

[setup/cluster-gridengine]
# ... rest as usual
xlargecompute_groups=gridengine_clients
```

then you can issue:

```
elasticluster resize -a 1:xlargecompute
```

**Comment by radaniba** [comment]
Thank you @riccardomurri
