### ISSUE TITLE
Installation issues on CentOS 7.2

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#308]
Just installed in a new `virtualenv` on a CentOS 7.2 VM. Had to upgrade the `pip` copy of `setuptools`. After that, I saw this error:

```
(elasticluster)[centos@hostname src]$ elasticluster list
Traceback (most recent call last):
  File "/home/centos/src/venv-2016-09-21/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2985, in <module>
    @_call_aside
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2971, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    ws.require(__requires__)
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/src/venv-2016-09-21/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-novaclient' distribution was not found and is required by elasticluster
```

**Comment by riccardomurri** [comment]
Indeed, it looks like the install process is skipping the `python-novaclient`
dependency altogether::

    $ pip install -e .
    Obtaining file:///home/centos/elasticluster
      Running setup.py egg_info for package from file:///home/centos/elasticluster
      ...
    Requirement already satisfied (use --upgrade to upgrade): PyCLI in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): ansible>=2.0 in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): coloredlogs in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): configobj in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): paramiko in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): voluptuous>=0.8.2 in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): boto in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): google-api-python-client in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): python-gflags in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): simplejson>=2.5.0 in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): netifaces in /tmp/e/lib/python2.7/site-packages (from elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): jinja2 in /tmp/e/lib/python2.7/site-packages (from ansible>=2.0->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): PyYAML in /tmp/e/lib/python2.7/site-packages (from ansible>=2.0->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /tmp/e/lib/python2.7/site-packages (from ansible>=2.0->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /tmp/e/lib/python2.7/site-packages (from ansible>=2.0->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): humanfriendly>=1.42 in /tmp/e/lib/python2.7/site-packages (from coloredlogs->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): six in /tmp/e/lib/python2.7/site-packages (from configobj->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /tmp/e/lib/python2.7/site-packages (from paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /tmp/e/lib/python2.7/site-packages (from paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): httplib2<1,>=0.8 in /tmp/e/lib/python2.7/site-packages (from google-api-python-client->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): oauth2client<4.0.0,>=1.5.0 in /tmp/e/lib/python2.7/site-packages (from google-api-python-client->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): uritemplate<1,>=0.6 in /tmp/e/lib/python2.7/site-packages (from google-api-python-client->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /tmp/e/lib/python2.7/site-packages (from jinja2->ansible>=2.0->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /tmp/e/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): enum34 in /tmp/e/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): ipaddress in /tmp/e/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /tmp/e/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /tmp/e/lib/python2.7/site-packages (from oauth2client<4.0.0,>=1.5.0->google-api-python-client->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): rsa>=3.1.4 in /tmp/e/lib/python2.7/site-packages (from oauth2client<4.0.0,>=1.5.0->google-api-python-client->elasticluster==1.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): pycparser in /tmp/e/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->elasticluster==1.3.dev0)
    Installing collected packages: elasticluster
      Running setup.py develop for elasticluster
      ...
    Successfully installed elasticluster
    Cleaning up...

However, `pip` as installed by CentOS7 is quite old::

    $ pip --version
    pip 1.4.1 from /tmp/e/lib/python2.7/site-packages (python 2.7)

Perhaps, there is a minimal version of `pip` *and* a minimal version of
`setuptools` that are required for parsing conditional dependencies: if you
don't have *both* then things will silently (...!) fail.

**Comment by riccardomurri** [comment]
It looks like the minimal version of `pip` that can successfully install
ElastiCluster on CentOS 7.2 is `7.1.0`. Luckily it can be upgraded from
`pip==1.4.1` directly inside the virtualenv::

    pip install --upgrade 'pip==7.1.0'

Alas, there is apparently also a *maximum* version of `pip` that works on CentOS
7.2, and that is `pip==8.0.1` -- after that version, `pip` fails to download
other versions of `pip` (and, presumably other packages as well) with this error::

    SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

The relevant [changelog entry][1] seems to be::

    **8.0.2 (2016-01-21)**

    * Stop attempting to trust the system CA trust store because it's extremely
      common for them to be broken, often in incompatible ways. See :pull:`3416`.

[1]: https://github.com/pypa/pip/blob/master/CHANGES.txt#L137

**Comment by riccardomurri** [comment]
This should be fixed in the latest "master", can you please try?

**Comment by verdurin** [comment]
It does install, after I follow the advice of the error message to run
```
easy_install -U setuptools
```

but when I try to run it:
```
(elasticluster)[root@proliant2 src]# elasticluster
Traceback (most recent call last):
  File "/root/src/github/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/root/src/github/elasticluster/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/root/src/github/elasticluster/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/src/github/elasticluster/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyparsing>=2.0.1
```

**Comment by verdurin** [comment]
Actually, I missed some errors during the installation:

```
 Running setup.py install for PyYAML
    checking if libyaml is compilable
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fP
IC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -
I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
```

then I realised that `gcc-c++` was needed (please add this to the requirements list).

Later on, there are more errors:

```
  Running setup.py install for funcsigs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/src/github/elasticluster/build/funcsigs/setup.py", line 51, in <module>
        test_suite = 'unittest2.collector',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/root/src/github/elasticluster/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/root/src/github/elasticluster/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/root/src/github/elasticluster/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/root/src/github/elasticluster/lib/python2.7/site-packages), Requirement.parse('setuptools>=17.1'))
    Complete output from command /root/src/github/elasticluster/bin/python -c "import setuptools;__file__='/root/src/github/elasticluster/build/funcsigs/setup.py';exec(compile(open(__file__).read().replac
e('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4Gm7WS-record/install-record.txt --single-version-externally-managed --install-headers /root/src/github/elasticluster/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/root/src/github/elasticluster/build/funcsigs/setup.py", line 51, in <module>

    test_suite = 'unittest2.collector',

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/root/src/github/elasticluster/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/root/src/github/elasticluster/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/root/src/github/elasticluster/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (setuptools 0.9.8 (/root/src/github/elasticluster/lib/python2.7/site-packages), Requirement.parse('setuptools>=17.1'))
```

**Comment by riccardomurri** [comment]
I have added solutions to these steps in the troubleshooting section of the
docs.  Long story short: use ``pip install --upgrade setuptools`` instead
of ``easy_install -U setuptools``.

Can you please try again?

**Comment by verdurin** [comment]
Yes, that works - thanks.

Would it not be possible to fix the error message, rather than relying on people reading the troubleshooting document after seeing the error?

**Comment by riccardomurri** [comment]
> Would it not be possible to fix the error message,
>  rather than relying on people reading the troubleshooting document 
> after seeing the error?

Done in commit 22f2499; thanks for the suggestion!
