### ISSUE TITLE
Common tasks breaks with --limit

### ISSUE THREAD

**Issue by HackerMD** [gc3-uzh-ch/elasticluster#337]
The tasks "Set /etc/hosts from Ansible hostgroups" and "Setup /etc/ssh/shosts.equiv file" break when not all `hosts` are available via `hostvars`, e.g. in case the playbook is run with the `--limit` argument.

```
TASK [common : Set /etc/hosts from Ansible hostgroups] *************************
fatal: [test-slurm-worker-001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_default_ipv4'"}
fatal: [test-slurm-worker-002]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_default_ipv4'"}
fatal: [test-slurm-master-001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_default_ipv4'"}
```

The culprits are the jinja template files `roles/common/templates/etc/hosts.j2`:

```
127.0.0.1 localhost.localdomain localhost

{% if hosts %}
{% for host in hosts|sort %}
{% if host != 'localhost' %}
{{ hostvars[host].ansible_default_ipv4.address }} {{ host }}
{% endif %}
{% endfor -%}

{% else %}
{% for host in groups['all']|sort %}
{% if host != 'localhost' %}
{{ hostvars[host].ansible_default_ipv4.address }} {{ host }}
{% endif %}
{% endfor %}

{% endif %}
```

and `roles/common/templates/etc/ssh/shosts.equiv.j2`:

```
{% for host in groups.all %}
{{ host }}
{{ hostvars[host].ansible_default_ipv4.address | default('') }}
{% endfor %}
```

**Comment by riccardomurri** [comment]
I do not think this can be changed or "fixed" with the current
architecture of Ansible.  Information about *all* hosts in the cluster
is needed to build those files (and `/etc/ansible/hosts` and
`/etc/genders` and possibly many others) and that information simply
is not available when Ansible is run with `--limit`.

In other words: the templates cannot be changed, so you cannot use
the `--limit` option.

On the other hand, Ansible is pretty fast when replaying actions that
are already in a "ok" state, so why bother?

**Comment by HackerMD** [comment]
There is currently no way (at least non I could come up with) that allows running certain roles selectively.

When playbooks in the `roles` directory are called directly, they fail due to undefined variables. They also fail when the missing variables are included from `group_vars/all`.

Simply rerunning everything becomes very annoying and hard to debug when dealing with hundreds of hosts.

In my opinion there should be a way to (re)run individual roles independently, be it via the `--limit` argument or by selective running playbooks that are included in `site.yml`.

**Comment by riccardomurri** [comment]
> there should be a way to (re)run individual roles independently,

This is a different problem :-) and luckily already has a solution:

* You can leverage [Ansible "tags" mechanism][1]; create a playbook
  named `after.yml` with content similar to this one::

        ---
        - name: Apply local customizations
          tags:
            - after
          hosts: all
          roles:
            - { role: 'role1', param1: 'foo', param2: 'bar' }
            - role2
            - role3
   
  Then run it with::
   
        elasticluster setup mycluster -- after.yml --tags after

  or equivalently::
   
        ansible-playbook -i /path/to/mycluster.inventory after.yml --tags after
        
  The important part is that the argument to Ansible's `--tags`
  option matches the tags appearing in the `after.yml` playbook.
   
* Alternatively, you can
  (ab)use [Ansible's `--start-at-task` option][2]' create a playbook
  named `after.yml` with content similar to::

        ---
        - name: Empty play for being a "goto" target
          tags:
            - after
          hosts: all
          tasks:
            - name: GOTO target
              debug:
                msg="No-op"

        - name: Apply local customizations
          tags:
            - after
          hosts: all
          roles:
            - { role: 'role1', param1: 'foo', param2: 'bar' }
            - role2
            - role3
   
  Then you can invoke it with::
   
        elasticluster setup mycluster -- after.yml --start-at-task='GOTO target'

  or equivalently::
   
        ansible-playbook -i /path/to/mycluster.inventory after.yml --start-at-task='GOTO target'

The difference between the first and second option is that (2) will
ignore the default ElastiCluster playbooks, whereas (1) will skip (as
in Ansible's "skippped task") them.


[1]: http://docs.ansible.com/ansible/playbooks_tags.html
[2]: http://docs.ansible.com/ansible/playbooks_startnstep.html

**Comment by HackerMD** [comment]
Cool! Thanks for the hint!

**Comment by HackerMD** [comment]
Using the following tasks instead of the template might also do the trick:

```yaml
- name: Add hosts to /etc/hosts
   become: yes
   lineinfile:
       state=present
       dest=/etc/hosts
       regexp=".*{{ item }}$"
       line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    when: hostvars]item].ansible_default_ipv4.address is defined
    whitn_items: "{{ groups['all'] }}"
```

**Comment by riccardomurri** [comment]
Thanks for the suggestion!  However, I see two problems with it:

1) The `lineinfile` task (e.g. the above one) would need `state=present` when building the cluster or adding nodes, but `state=absent` when removing the nodes.  This can be added through an additional variable in the Ansible inventory, but it's not plug-and-play in the current ElastiCluster code.

2) In addition, some RHEL/CentOS variant like to alias the host name to "127.0.0.1 localhost" -- the template would overwrite this with a non-loopback address and effectively remove `localhost` from `/etc/hosts`, which I am afraid would wreak havoc.

**Comment by riccardomurri** [comment]
On second thought, *1.* above is a much larger problem: you can run `elasticluster setup` independently of other actions, and in that case there is no good value for `state=...`.  

For example, you could run a few `elasticluster remove-node --no-setup ...` and then `elasticluster resize --no-setup --add ...` and finally `elasticluster setup`: in this case ElastiCluster should add or remove lines to the `/etc/hosts` file depending on the host name.  I see no easy way of doing that with the proposed `lineinfile:` task.
