### ISSUE TITLE
Feature request: pass "elasticluster setup" extra args to Ansible

### ISSUE THREAD

**Issue by nicoulaj** [gc3-uzh-ch/elasticluster#349]
It would be nice if we could do things like:
```
elasticluster setup mycluster --skip-tags ...
elasticluster setup mycluster --step ...
elasticluster setup mycluster --start-at-task ...
elasticluster setup mycluster playbook.retry
```

**Comment by riccardomurri** [comment]
You can already do that :-)

Just add a `--` in the middle to prevent `elasticluster` from interpreting the options as "own" options::

    elasticluster setup mycluster -- --tags local --verbose
