### ISSUE TITLE
SELinux prevents correct logging on CentOS 7 VMs

### ISSUE THREAD

**Issue by vinjana** [gc3-uzh-ch/elasticluster#370]
On Centos 7 VMs, systemctl and journalctl don't work correctly. Service systemd-journald can not be started with SELinux in "enforcing" mode. Furthermore, no logs are written. The effect seems to be visible only after same time.

You can quickly check the starting of journald with

  $ systemctl restart systemd-journald
  Job for systemd-journald.service failed. See "systemctl status systemd-journald.service" and "journalctl -xe" for details.
  $ setenforce 0
  $ systemctl restart systemd-journald
  $ systemctl status systemd-journald

Note that again calling "setenforce 1" again also prevents restarting journald.

Commenting out the re-enabling of SELinux in share/playbooks/roles/iptables/tasks/main.yml produces VMs with working journald. 

This may be related to http://serverfault.com/questions/764687/systemd-journald-fails-to-start-on-centos-7. Currently, SELinux is temporarily turned off in share/playbooks/roles/iptables/tasks/main.yml and later turned on again.

**Comment by riccardomurri** [comment]
The ServerFault answer you linked seems to indicate that `restorecon -r /` would solve the issue of journald (and possibly other programs) not working after a SELinux stop+restart.

I do not know enough of SELinux myself to judge whether that is a suitable workaround.
Any opinion?

**Comment by vinjana** [comment]
For me that caused that the VM could not be booted anymore.

**Comment by riccardomurri** [comment]
that = 'restorecon -r /' ?

**Comment by vinjana** [comment]
Sorry, yes: I did 'restorecon -r /' on the command line and could not reboot.

HOWEVER, I now have tried out the procedure with 2 fresh VMs where I did 'restorecon -r /' and repeated the reboot successfully! So there is some chance, that the previous experience was just bad luck or something else I overlooked. The restorecon therefore seems to have fixed the issue.

**Comment by riccardomurri** [comment]
I've just pushed a commit to the "master" branch that runs `restorecon` after re-enabling the SELinux policy.  Can you please test it and ley me know if it solves the issue?
