### ISSUE TITLE
Slurm playbook fails while trying to find "slurm_workers" attribute

### ISSUE THREAD

**Issue by Moisan** [gc3-uzh-ch/elasticluster#372]
When launching a Slurm cluster, it fails at the following step:

```
TASK [slurm-common : Deploy SLURM configuration file] **************************
fatal: [master001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'slurm_workers'"}
```

This is based on the following configuration:

```
[setup/slurm]
provider=ansible
master_groups=slurm_master
worker_groups=slurm_worker
```

```
[cluster/slurm]
cloud=google
login=google
setup=slurm
image_id=ubuntu-1604-xenial-v20161130
security_group=default
flavor=n1-highcpu-8
master_nodes=1
worker_nodes=10
ssh_to=master
image_userdata=
```

**Comment by riccardomurri** [comment]
What version of ElastiCluster are you running?  I cannot find any trace of `slurm_workers` (plural) in https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/roles/slurm-common/templates/slurm.conf.j2 nor in any other file of the current "master" branch.

**Comment by Moisan** [comment]
I reinstalled the latest version on a clean python environment and I couldn't reproduce my issue. I'll close the issue, sorry for the false alarm!
