### ISSUE TITLE
The service slurmdbd won't start (CentOS 7.2)

### ISSUE THREAD

**Issue by burigolucas** [gc3-uzh-ch/elasticluster#374]
The service `slurmdbd` won't start on `CentOS Linux release 7.2.1511 (Core)`. The hostname is not correctly assigned. The complete output of `elasticluster -vvv start` including Ansible logs is located in the following file:
[elasticluster_start_output.txt](https://github.com/gc3-uzh-ch/elasticluster/files/716407/elasticluster_start_output.txt)

**Comment by riccardomurri** [comment]
Can you please also post the file `/etc/hosts` from node `frontend001` and the output of these commands::

    uname -n
    hostname
    hostname -s
    hostname -f

**Comment by burigolucas** [comment]
File `/etc/hosts` from `frontend001`:

# THIS FILE IS CONTROLLED BY ELASTICLUSTER
# local modifications will be overwritten
# the next time `elasticluster setup` is run!
#

127.0.0.1  localhost localhost.localdomain localhost4 localhost4.localdomain4

10.0.0.119 compute001 vm-1-74.my.department vm-1-74
10.0.0.118 frontend001 vm-1-73.my.department vm-1-73

Output of commands:
`uname -n`: vm-1-73.my.department
`hostname`: vm-1-73.my.department
`hostname -s`: vm-1-73
`hostname -f`: frontend001

**Comment by riccardomurri** [comment]
Hmmm... this contrasts with what Ansible reports::

    TASK [common : Set host name to Ansible "inventory name"] **********************
    ...
    changed: [frontend001] => {"ansible_facts": {"ansible_domain": "my.department", "ansible_fqdn": "vm-1-73.my.department", "ansible_hostname": "frontend001", "ansible_nodename": "frontend001"}, "changed": true, "name": "frontend001"}

What version of Ansible are you running?

**Comment by burigolucas** [comment]
`ansible version`: ansible 2.2.1.0

**Comment by riccardomurri** [comment]
Can you also provide the output of the following commands? (Watch out for potentially sensible info!)

```
grep '.' /var/lib/dhclient/*.lease
ip addr
```

**Comment by burigolucas** [comment]
Output of `grep '.' /var/lib/dhclient/*.lease`:
lease {
  interface "eth0";
  fixed-address 10.0.0.118;
  option subnet-mask 255.255.255.0;
  option routers 10.0.0.1;
  option dhcp-lease-time 86400;
  option dhcp-message-type 5;
  option domain-name-servers 10.0.0.3;
  option dhcp-server-identifier 10.0.0.3;
  option interface-mtu 1400;
  option dhcp-renewal-time 43200;
  option broadcast-address 10.0.0.255;
  option dhcp-rebinding-time 75600;
  option host-name "host-10-0-0-118";
  option domain-name "my.department";
  renew 4 2017/01/19 21:16:53;
  rebind 5 2017/01/20 08:04:58;
  expire 5 2017/01/20 11:04:58;
}

Output of `ip addr`:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:bb:6f:42 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.118/24 brd 10.0.0.255 scope global dynamic eth0
       valid_lft 71027sec preferred_lft 71027sec
    inet6 fe80::f816:3eff:febb:6f42/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by riccardomurri** [comment]
Then I really do not understand where this `vm-1-73` hostname is coming from ...

**Comment by riccardomurri** [comment]
More questions:

1. What does the `slurm.conf` file have for `AccountingStorageHost=...`? Is the
   `slurm.conf` exactly the same on frontend and compute nodes?
   
2. Is it possible that you did not define any host in class `slurm_master` ?

3. Can you also provide files `/etc/cloud/cloud.cfg`,
   `/var/lib/cloud/instance/cloud-config.txt`, `/var/lib/cloud/user-data.txt`,
   and `/var/lib/cloud/instance/vendor-data.txt` from the frontend node?
   
4. Is it possible to share the VM image that you are using as a starting point for E11C customizations?

**Comment by riccardomurri** [comment]
Can you also please provide the output of `hostnamectl status` ?

**Comment by burigolucas** [comment]
1. SLUMR is not installed in the compute node, no `slurm.conf` available. As for the frontend node, `slurm.conf` has `AccountingStorageHost=frontend001`

2. The cluster has the following setup in the configuration file of ElastiCluster:
`frontend_groups=slurm_master`
`compute_groups=slurm_worker`

3. The files `/var/lib/cloud/instance/user-data.txt` and `/var/lib/cloud/instance/cloud-config.txt` are empty. The file  `/var/lib/cloud/instance/vendor-data.txt` contains only `{}`. The file `/etc/cloud/cloud.cfg` is attached ([cloud_cfg.txt](https://github.com/gc3-uzh-ch/elasticluster/files/719504/cloud_cfg.txt)).

4. I am not able to share the VM image.

5. The output of `hostnamectl status`:
   Static hostname: vm-1-73.my.department
         Icon name: computer-vm
           Chassis: vm
        Machine ID: d1c01fff36bb42738c09cdce081d362a
           Boot ID: 72124a097fa54e5b829a17711721ddb6
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.10.1.el7.x86_64
      Architecture: x86-64

**Comment by riccardomurri** [comment]
And what's the value of `DbdHost` and `StorageHost` in `/etc/slurm/slurmdbd.conf` ?

**Comment by riccardomurri** [comment]
I have tried again the current "master" playbooks with:

- the official CentOS 7 AMI on AWS us-east-1
- the official CentOS 7 RAW image ([CentOS-7-x86_64-GenericCloud-1511.raw.tar.gz](http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1511.raw.tar.gz)) on our local OpenStack

In both cases, the setup ends correctly and the cluster is fully-functional.

So apparently there is something in your local CentOS image that prevents the playbook from running correctly (actually, the problem seems to be that the host name is not changed although Ansible thinks it is) but I've run out of guesses as to what is going wrong and I'm not able to debug the problem further without direct access.  Do you think you could set up a cluster with a public IP address and let me SSH in?

**Comment by burigolucas** [comment]
`DbdHost=frontend001`
`StorageHost=localhost`

I agree there shall be something in my local CentOS image causing the issue. Unfortunately I am not able to provide a public IP so you could log in.

Thank you for all your help @riccardomurri

**Comment by riccardomurri** [comment]
It's been quite a while this issue has been reported, but no-one else reported similar problems. So I'm going to consider this "solved" (or, at least, a local configuration issue).
