### ISSUE TITLE
Issue with boot_disk_size in the cluster node section

### ISSUE THREAD

**Issue by marcbrisson** [gc3-uzh-ch/elasticluster#376]
Using google compute engine. I get error using boot_disk_size in the cluster node section
 

```
[cluster/slurm]
cloud=google
login=google
setup=slurm
security_group=default
image_id=https://www.googleapis.com/compute/v1/projects/jda-labs---decision-science-01/global/images/image-python-ubuntu
flavor=n1-standard-1
master_nodes=1
worker_nodes=4
ssh_to=master
image_userdata=
boot_disk_size=20

[cluster/slurm/master]
flavor=n1-standard-2
boot_disk_size=100
```

I get the error: 

`ERROR In section cluster/slurm: Wrong keys 'boot_disk_size' in {'min_num': 1, 'image_userdata': '', 'image_id': 'https://www.googleapis.com/compute/v1/projects/jda-labs---decision-science-01/global/images/image-python-ubuntu', 'num': 1, 'security_group': 'default', 'flavor': 'n1-standard-2', 'login': 'google', 'boot_disk_size': '100'}`

Riccardo Murri @riccardomurri janv. 19 16:25
@marcbrisson_twitter This is a bug in the config parser, can you please report it on https://github.com/gc3-uzh-ch/elasticluster/issues ?

**Comment by riccardomurri** [comment]
This should now be fixed in the latest "master" branch, can you please update and check?

Also note that it is possible that defining `boot_disk_size` in the `[cluster/*]` section does not yield any effect... In that case, please open another issue!

**Comment by marcbrisson** [comment]
boot_disk_size does work in the [cluster/slurm/master] and [cluster/slurm/worker] section.

But it doesn't seem to work in [cluster/slurm] as you mentionned. I will do more test later and open ticket if I can confirm.

thanks
