### ISSUE TITLE
NTP required

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#380]
I'm looking at a cluster that was craeted a while ago, and some of the compute nodes are rejected by SLURM owing to divergent system clocks.

Please include NTP on all nodes, so that a cluster's clocks are all synchronised to the same time source.

**Comment by riccardomurri** [comment]
Good point! This should be fixed in commit 01539e0, with NTPd being installed by default on every cluster.  Can you please check and confirm?
