### ISSUE TITLE
 boot_disk_size in the cluster node section is ignored on GCE

### ISSUE THREAD

**Issue by marcbrisson** [gc3-uzh-ch/elasticluster#381]
Using google compute engine. I the boot_disk_size in the cluster section is ignored.

[cluster/slurm]
cloud=google
login=google
setup=slurm
security_group=default
image_id=ubuntu-1604-xenial-v20170113
flavor=n1-standard-1
master_nodes=1
worker_nodes=4
ssh_to=master
image_userdata=
boot_disk_size=15

all machines are 10gb only, the default size on GCE

**Comment by riccardomurri** [comment]
@marcbrisson can you please check that @Moisan 's pull request #419 fixes the issue?

**Comment by marcbrisson** [comment]
Yes it looks good!

**Comment by riccardomurri** [comment]
Thanks for taking the time to check!

The issue has thus just been fixed by merging #419 , contributed by @Moisan
