### ISSUE TITLE
Google cloud API attribute sshKeys will be deprecated in March 2017

### ISSUE THREAD

**Issue by Moisan** [gc3-uzh-ch/elasticluster#391]
[The google cloud documentation on ssh keys](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys) states that using the `sshKeys` metadata will be deprecated in March 2017. They suggest to use `ssh-keys` instead. 

I modified the code of elasticluster to use this API attribute and it works well on CentOS 7. However, it breaks the Ubuntu instances when using the Slurm playbook. 

Short story: the API call to GCE should be switched to use `ssh-keys` but this seems to break stuff with Ubuntu.

**Comment by riccardomurri** [comment]
Hi @Moisan can you please share the config (cluster + cloud + setup sections) that breaks SLURM/Ubuntu?  (Of course, please remove/hide any actual credentials and sensible/reserved details.)

**Comment by Moisan** [comment]
```
[cloud/google]
provider=google
gce_client_id=<my_client_id>
gce_client_secret=<my_cliend_secret>
gce_project_id=<my_project_id>
noauth_local_webserver=True

[setup/slurm]
provider=ansible
master_groups=slurm_master
worker_groups=slurm_worker

[cluster/slurm_ubuntu]
cloud=google
login=google
setup=slurm
security_group=default
image_id=ubuntu-1610-yakkety-v20170103
flavor=n1-standard-1
master_nodes=1
worker_nodes=2
ssh_to=master
image_userdata=
```

With this config and using `ssh-keys` instead of `sshKeys` in the file `elasticluster/providers/gce.py`, I obtain the following error (on both workers):

```fatal: [worker002]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1486562724.49-137088891104188 `\" && echo ansible-tmp-1486562724.49-137088891104188=\"` echo ~/.ansible/tmp/ansible-tmp-1486562724.49-137088891104188 `\" ), exited with result 1", "unreachable": true}```

**Comment by riccardomurri** [comment]
My reading of the [API documentation for setting instance metadata][1] is that
this is a process that must be done *after* the instance has been created, not
when requesting the instance (as ElastiCluster does currently). In other words,
changing the source to properly use the new `ssh-keys` metadata might be more
work than just renaming a parameter:[*] one would need to create the instance,
fetch metadata (to get the "fingerprint" value), then post new metadata
including the `ssh-keys`. This adds quite some code to
`GoogleCloudProvider.start_instance()`.  

Unfortunately, I likely won't have time to work on this before mid-March, at
which point Google might have already removed the `sshKeys` parameter.

As a workaround, though, it seems that `sshKeys` is still supported at the
*project* level, so it may be possible to just use the same set of SSH keys for
all VMs in the project. Would that be an option?


[1]: https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#instance-only

[*]: I think that just renaming the metadata parameter only leads to it being
    ignored with the likely result you experienced, i.e., not being able to
    connect.

**Comment by Moisan** [comment]
I recently re-tested with the latest version and I don't have this issue anymore. As of now, Google cloud simply ignore the sshKeys metadata. The instances are now open to everyone on the same project. While this is the behavior I want, I wonder if this is the behavior you wish to obtain.
