### ISSUE TITLE
gmond on ubuntu compute node uses 100% on 1 core

### ISSUE THREAD

**Issue by akmb** [gc3-uzh-ch/elasticluster#411]
After starting a cluster (slurm, ganglia) I discover that gmond uses 100% on all compute nodes. This happens on ubuntu 14.04 and 16.04.

To fix this add ‘deaf = yes’ on ganglia_monitors except ganglia_master in `ganglia/templates/gmond.conf.j2`, something like:
```
globals {
  daemonize = yes
  setuid = yes
  user = ganglia
  debug_level = 0
  max_udp_msg_len = 1472
  mute = no
{% if inventory_hostname in groups['ganglia_monitor'] and not inventory_hostname in groups['ganglia_master'] %}
  deaf = yes
{% elif inventory_hostname in groups['ganglia_master'] %}
  deaf = no
{% endif %}
  host_dmax = 0 /*secs */
  cleanup_threshold = 300 /*secs */
  gexec = no
  send_metadata_interval = 10
}
```

**Comment by riccardomurri** [comment]
Thanks!  If you can resubmit this as a pull request, I'll merge it so your name will be on the contributors list.  If you don't care about that, I will just apply the change you suggested and credit you in the log message.

**Comment by akmb** [comment]
ok, have done it ... :)

**Comment by riccardomurri** [comment]
Merged, thanks for contributing!
