### ISSUE TITLE
Node name mismatch across `cluster/*` and `setup/*` sections in config file goes undetected

### ISSUE THREAD

**Issue by dirkpetersen** [gc3-uzh-ch/elasticluster#415]
dirk@rhino1:~$ elasticluster start gce-slurm
Starting cluster `gce-slurm` with:
* 2 worker nodes.
* 1 frontend nodes.
(This may take a while...)
Configuring the cluster.
(this too may take a while...)
2017-03-31 17:12:16 rhino1 gc3.elasticluster[33543] WARNING UserWarning: Node kind `worker` not defined in cluster!

PLAY [Apply local customizations (before)] *************************************

TASK [setup] *******************************************************************
ok: [frontend001]

PLAY [Common setup for all hosts] **********************************************

TASK [setup] *******************************************************************
ok: [frontend001]

TASK [common : Provide workaround for YAML syntax error in lines containing colon+space] ***
ok: [frontend001]

TASK [common : include] ********************************************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/common/tasks/init-Debian.yml for frontend001

TASK [common : Ensure extra repositories are present (Ubuntu)] *****************
changed: [frontend001]

TASK [common : Ensure the APT package cache is updated] ************************
changed: [frontend001]

TASK [common : Install Ansible `apt` module dependencies] **********************
changed: [frontend001]
 [WARNING]: Consider using apt module rather than running apt-get

TASK [common : Upgrade all installed packages to latest version] ***************
changed: [frontend001]

TASK [common : Ensure additional packages are installed] ***********************
changed: [frontend001] => (item=[u'apt-transport-https', u'debconf', u'debconf-utils'])

TASK [common : Ensure additional packages are installed (Debian 8 "jessie")] ***
skipping: [frontend001] => (item=[]) 

TASK [common : Provide workaround for https://github.com/ansible/ansible-modules-core/issues/4472] ***
ok: [frontend001]

TASK [common : Install policy package for service autostart] *******************
skipping: [frontend001]

TASK [common : Install policy script for service autostart] ********************
skipping: [frontend001]

TASK [common : Set /etc/hosts from Ansible hostgroups] *************************
changed: [frontend001]

TASK [common : Patch `/etc/redhat-release`] ************************************
skipping: [frontend001]

TASK [common : Set host name to Ansible "inventory name"] **********************
changed: [frontend001]

TASK [common : Undo patch to `/etc/redhat-release`] ****************************
skipping: [frontend001]

TASK [common : Check for cloud-init conf file] *********************************
ok: [frontend001]

TASK [common : Ensure changes to hostname are not overwritten by cloud-init] ***
changed: [frontend001]

TASK [common : include] ********************************************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/common/tasks/software-Debian.yml for frontend001

TASK [common : Install commonly needed software (Debian-family)] ***************
changed: [frontend001] => (item=[u'bzip2', u'cpio', u'gzip', u'lzip', u'p7zip-full', u'tar', u'unzip', u'xz-utils', u'zip', u'git', u'mercurial', u'subversion', u'g++', u'gcc', u'libc6-dev', u'make', u'kexec-tools', u'm4', u'moreutils', u'rsync', u'screen', u'tmux', u'vim'])

TASK [common : Setup SSH known hosts file] *************************************
changed: [frontend001]

TASK [common : Setup /etc/ssh/shosts.equiv file] *******************************
changed: [frontend001]

TASK [common : Setup /root/.shosts file] ***************************************
changed: [frontend001]

TASK [common : Setup SSH host based authentication (server configuration file)] 
changed: [frontend001] => (item={u'value': u'yes', u'key': u'HostbasedAuthentication'})
changed: [frontend001] => (item={u'value': u'no', u'key': u'IgnoreRhosts'})

TASK [common : Setup SSH host based authentication (server configuration file)] 
changed: [frontend001] => (item={u'value': u'yes', u'key': u'HostbasedAuthentication'})
changed: [frontend001] => (item={u'value': u'yes', u'key': u'EnableSSHKeysign'})

TASK [iptables : Load distribution-specific data] ******************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/iptables/tasks/init-Debian.yml for frontend001

TASK [iptables : Load configuration and service names (Debian/Ubuntu)] *********
ok: [frontend001]

TASK [iptables : Load configuration and service names (older Debian/Ubuntu)] ***
skipping: [frontend001]

TASK [iptables : Load package names (Debian/Ubuntu)] ***************************
ok: [frontend001]

TASK [iptables : Temporarily disable SELinux (RHEL-family)] ********************
skipping: [frontend001]

TASK [iptables : Install iptables packages] ************************************
changed: [frontend001] => (item=[u'iptables', u'iptables-persistent'])

TASK [iptables : Deploy netfilter rules] ***************************************
changed: [frontend001] => (item=etc/iptables/rules.v4)
changed: [frontend001] => (item=etc/iptables/rules.v6)

TASK [iptables : Ensure netfilter rules are loaded at boot] ********************
ok: [frontend001] => (item=iptables)
ok: [frontend001] => (item=ip6tables)

RUNNING HANDLER [common : restart sshd] ****************************************
changed: [frontend001]

RUNNING HANDLER [iptables : no-op] *********************************************
ok: [frontend001] => {
    "msg": "Not reloading iptables -- not supported by netfilter-persistent service unit"
}

TASK [iptables : Enable SELinux (RHEL-family)] *********************************
skipping: [frontend001]

TASK [iptables : Restore SELinux labels on `/` (RHEL-family)] ******************
skipping: [frontend001]

TASK [ntpd : Load distribution-specific parameters] ****************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/ntpd/tasks/init-Debian.yml for frontend001

TASK [ntpd : Set NTPd common playbook params (Debian/Ubuntu)] ******************
ok: [frontend001]

TASK [ntpd : Deploy NTP configuration file] ************************************
changed: [frontend001]

TASK [ntpd : Install NTP packages] *********************************************
ok: [frontend001]

TASK [ntpd : Enable NTP service at boot] ***************************************
ok: [frontend001]

TASK [pdsh : Install pdsh packages (Debian-family)] ****************************
changed: [frontend001]

TASK [pdsh : Install pdsh packages (RHEL-family)] ******************************
skipping: [frontend001] => (item=[]) 

TASK [pdsh : Create genders file for PDSH] *************************************
changed: [frontend001]

TASK [pdsh : Make SSH the default exec method for PDSH] ************************
changed: [frontend001]

RUNNING HANDLER [ntpd : restart ntpd] ******************************************
changed: [frontend001]

PLAY [Slurm master Playbook] ***************************************************

TASK [setup] *******************************************************************
ok: [frontend001]

TASK [nis : Load distribution-specific parameters] *****************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nis/tasks/init-Debian.yml for frontend001

TASK [nis : Set NIS common playbook params (Debian)] ***************************
ok: [frontend001]

TASK [nis : Set NIS common playbook params (Ubuntu 14.04)] *********************
skipping: [frontend001]

TASK [nis : Pre-load debconf answer to questions (Debian/Ubuntu)] **************
changed: [frontend001]

TASK [nis : Deploy additional NIS configuration (Debian/Ubuntu)] ***************
changed: [frontend001] => (item=etc/default/nis)
changed: [frontend001] => (item=etc/defaultdomain)

TASK [nis : Set NIS domain (CentOS/RHEL)] **************************************
skipping: [frontend001]

TASK [nis : Install NIS common packages] ***************************************
changed: [frontend001] => (item=[u'nis'])

TASK [nis : Deploy `ypserv` configuration files] *******************************
changed: [frontend001]

TASK [nis : Deploy `yppasswdd` configuration file (CentOS/RHEL)] ***************
skipping: [frontend001]

TASK [nis : Install NIS master server packages] ********************************

TASK [nis : Ensure `ypserv` starts at boot] ************************************
ok: [frontend001] => (item=rpcbind)
ok: [frontend001] => (item=nis)

RUNNING HANDLER [nis : restart NIS master services] ****************************
changed: [frontend001] => (item=rpcbind)
changed: [frontend001] => (item=nis)

TASK [nis : Update NIS/YP databases (NIS master server)] ***********************
changed: [frontend001]

TASK [nis : Deploy `ypbind` configuration files] *******************************
skipping: [frontend001]

TASK [nis : Ensure NIS/YP is used as a name service] ***************************
skipping: [frontend001] => (item=passwd) 
skipping: [frontend001] => (item=group) 
skipping: [frontend001] => (item=shadow) 

TASK [nis : Replace `compat` in `/etc/nsswitch.conf` with `files nis`] *********
skipping: [frontend001] => (item=passwd) 
skipping: [frontend001] => (item=group) 
skipping: [frontend001] => (item=shadow) 

TASK [nis : Ensure `ypbind` starts at boot] ************************************
skipping: [frontend001] => (item=rpcbind) 
skipping: [frontend001] => (item=nis) 

TASK [nfs-server : Load distribution-specific parameters] **********************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nfs-server/tasks/init-Debian.yml for frontend001

TASK [nfs-server : Set NFS server variables (Debian/Ubuntu)] *******************
ok: [frontend001]

TASK [nfs-server : Work around Debian bug] *************************************
skipping: [frontend001]

TASK [nfs-server : install NFS server software] ********************************
changed: [frontend001] => (item=[u'nfs-kernel-server', u'nfs-common'])

TASK [nfs-server : Export directories] *****************************************
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "[{u'path': u'/home', u'clients': u'{{groups.slurm_worker + groups.slurm_submit|default([])}}'}]: 'dict object' has no attribute 'slurm_worker'"}
 [WARNING]: Could not create retry file '/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'.         [Errno 30] Read-only file system: u'/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'

PLAY RECAP *********************************************************************
frontend001                : ok=51   changed=29   unreachable=0    failed=1   

2017-03-31 17:21:05 rhino1 gc3.elasticluster[33543] ERROR Command `ansible-playbook /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.yml --inventory=/fh/fast/_ADM/SciComp/user/dirk/.elasticluster/storage/gce-slurm.inventory --become --become-user=root` failed with exit code .
2017-03-31 17:21:05 rhino1 gc3.elasticluster[33543] ERROR Check the output lines above for additional information on this error.
2017-03-31 17:21:05 rhino1 gc3.elasticluster[33543] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2017-03-31 17:21:05 rhino1 gc3.elasticluster[33543] WARNING Cluster `gce-slurm` not yet configured. Please, re-run `elasticluster setup gce-slurm` and/or check your configuration

WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     gce-slurm
Cluster template: gce-slurm
Default ssh to node: frontend001
- worker nodes: 2
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh gce-slurm

To upload or download files to the cluster, use the command:

    elasticluster sftp gce-slurm

dirk@rhino1:~$ elasticluster setup gce-slurm
Updating cluster `gce-slurm`...
Configuring cluster `gce-slurm`...
2017-03-31 17:22:40 rhino1 gc3.elasticluster[40939] WARNING UserWarning: Node kind `worker` not defined in cluster!

PLAY [Apply local customizations (before)] *************************************

TASK [setup] *******************************************************************
ok: [frontend001]

PLAY [Common setup for all hosts] **********************************************

TASK [setup] *******************************************************************
ok: [frontend001]

TASK [common : Provide workaround for YAML syntax error in lines containing colon+space] ***
ok: [frontend001]

TASK [common : include] ********************************************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/common/tasks/init-Debian.yml for frontend001

TASK [common : Ensure extra repositories are present (Ubuntu)] *****************
ok: [frontend001]

TASK [common : Ensure the APT package cache is updated] ************************
changed: [frontend001]

TASK [common : Install Ansible `apt` module dependencies] **********************
changed: [frontend001]
 [WARNING]: Consider using apt module rather than running apt-get

TASK [common : Upgrade all installed packages to latest version] ***************
ok: [frontend001]

TASK [common : Ensure additional packages are installed] ***********************
ok: [frontend001] => (item=[u'apt-transport-https', u'debconf', u'debconf-utils'])

TASK [common : Ensure additional packages are installed (Debian 8 "jessie")] ***
skipping: [frontend001] => (item=[]) 

TASK [common : Provide workaround for https://github.com/ansible/ansible-modules-core/issues/4472] ***
ok: [frontend001]

TASK [common : Install policy package for service autostart] *******************
skipping: [frontend001]

TASK [common : Install policy script for service autostart] ********************
skipping: [frontend001]

TASK [common : Set /etc/hosts from Ansible hostgroups] *************************
ok: [frontend001]

TASK [common : Patch `/etc/redhat-release`] ************************************
skipping: [frontend001]

TASK [common : Set host name to Ansible "inventory name"] **********************
ok: [frontend001]

TASK [common : Undo patch to `/etc/redhat-release`] ****************************
skipping: [frontend001]

TASK [common : Check for cloud-init conf file] *********************************
ok: [frontend001]

TASK [common : Ensure changes to hostname are not overwritten by cloud-init] ***
ok: [frontend001]

TASK [common : include] ********************************************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/common/tasks/software-Debian.yml for frontend001

TASK [common : Install commonly needed software (Debian-family)] ***************
ok: [frontend001] => (item=[u'bzip2', u'cpio', u'gzip', u'lzip', u'p7zip-full', u'tar', u'unzip', u'xz-utils', u'zip', u'git', u'mercurial', u'subversion', u'g++', u'gcc', u'libc6-dev', u'make', u'kexec-tools', u'm4', u'moreutils', u'rsync', u'screen', u'tmux', u'vim'])

TASK [common : Setup SSH known hosts file] *************************************
ok: [frontend001]

TASK [common : Setup /etc/ssh/shosts.equiv file] *******************************
ok: [frontend001]

TASK [common : Setup /root/.shosts file] ***************************************
ok: [frontend001]

TASK [common : Setup SSH host based authentication (server configuration file)] 
ok: [frontend001] => (item={u'value': u'yes', u'key': u'HostbasedAuthentication'})
ok: [frontend001] => (item={u'value': u'no', u'key': u'IgnoreRhosts'})

TASK [common : Setup SSH host based authentication (server configuration file)] 
ok: [frontend001] => (item={u'value': u'yes', u'key': u'HostbasedAuthentication'})
ok: [frontend001] => (item={u'value': u'yes', u'key': u'EnableSSHKeysign'})

TASK [iptables : Load distribution-specific data] ******************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/iptables/tasks/init-Debian.yml for frontend001

TASK [iptables : Load configuration and service names (Debian/Ubuntu)] *********
ok: [frontend001]

TASK [iptables : Load configuration and service names (older Debian/Ubuntu)] ***
skipping: [frontend001]

TASK [iptables : Load package names (Debian/Ubuntu)] ***************************
ok: [frontend001]

TASK [iptables : Temporarily disable SELinux (RHEL-family)] ********************
skipping: [frontend001]

TASK [iptables : Install iptables packages] ************************************
ok: [frontend001] => (item=[u'iptables', u'iptables-persistent'])

TASK [iptables : Deploy netfilter rules] ***************************************
ok: [frontend001] => (item=etc/iptables/rules.v4)
ok: [frontend001] => (item=etc/iptables/rules.v6)

TASK [iptables : Ensure netfilter rules are loaded at boot] ********************
ok: [frontend001] => (item=iptables)
ok: [frontend001] => (item=ip6tables)

TASK [iptables : Enable SELinux (RHEL-family)] *********************************
skipping: [frontend001]

TASK [iptables : Restore SELinux labels on `/` (RHEL-family)] ******************
skipping: [frontend001]

TASK [ntpd : Load distribution-specific parameters] ****************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/ntpd/tasks/init-Debian.yml for frontend001

TASK [ntpd : Set NTPd common playbook params (Debian/Ubuntu)] ******************
ok: [frontend001]

TASK [ntpd : Deploy NTP configuration file] ************************************
ok: [frontend001]

TASK [ntpd : Install NTP packages] *********************************************
ok: [frontend001]

TASK [ntpd : Enable NTP service at boot] ***************************************
ok: [frontend001]

TASK [pdsh : Install pdsh packages (Debian-family)] ****************************
ok: [frontend001]

TASK [pdsh : Install pdsh packages (RHEL-family)] ******************************
skipping: [frontend001] => (item=[]) 

TASK [pdsh : Create genders file for PDSH] *************************************
ok: [frontend001]

TASK [pdsh : Make SSH the default exec method for PDSH] ************************
ok: [frontend001]

PLAY [Slurm master Playbook] ***************************************************

TASK [setup] *******************************************************************
ok: [frontend001]

TASK [nis : Load distribution-specific parameters] *****************************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nis/tasks/init-Debian.yml for frontend001

TASK [nis : Set NIS common playbook params (Debian)] ***************************
ok: [frontend001]

TASK [nis : Set NIS common playbook params (Ubuntu 14.04)] *********************
skipping: [frontend001]

TASK [nis : Pre-load debconf answer to questions (Debian/Ubuntu)] **************
ok: [frontend001]

TASK [nis : Deploy additional NIS configuration (Debian/Ubuntu)] ***************
ok: [frontend001] => (item=etc/default/nis)
ok: [frontend001] => (item=etc/defaultdomain)

TASK [nis : Set NIS domain (CentOS/RHEL)] **************************************
skipping: [frontend001]

TASK [nis : Install NIS common packages] ***************************************
ok: [frontend001] => (item=[u'nis'])

TASK [nis : Deploy `ypserv` configuration files] *******************************
ok: [frontend001]

TASK [nis : Deploy `yppasswdd` configuration file (CentOS/RHEL)] ***************
skipping: [frontend001]

TASK [nis : Install NIS master server packages] ********************************

TASK [nis : Ensure `ypserv` starts at boot] ************************************
ok: [frontend001] => (item=rpcbind)
ok: [frontend001] => (item=nis)

TASK [nis : Update NIS/YP databases (NIS master server)] ***********************
changed: [frontend001]

TASK [nis : Deploy `ypbind` configuration files] *******************************
skipping: [frontend001]

TASK [nis : Ensure NIS/YP is used as a name service] ***************************
skipping: [frontend001] => (item=passwd) 
skipping: [frontend001] => (item=group) 
skipping: [frontend001] => (item=shadow) 

TASK [nis : Replace `compat` in `/etc/nsswitch.conf` with `files nis`] *********
skipping: [frontend001] => (item=passwd) 
skipping: [frontend001] => (item=group) 
skipping: [frontend001] => (item=shadow) 

TASK [nis : Ensure `ypbind` starts at boot] ************************************
skipping: [frontend001] => (item=rpcbind) 
skipping: [frontend001] => (item=nis) 

TASK [nfs-server : Load distribution-specific parameters] **********************
included: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nfs-server/tasks/init-Debian.yml for frontend001

TASK [nfs-server : Set NFS server variables (Debian/Ubuntu)] *******************
ok: [frontend001]

TASK [nfs-server : Work around Debian bug] *************************************
skipping: [frontend001]

TASK [nfs-server : install NFS server software] ********************************
ok: [frontend001] => (item=[u'nfs-kernel-server', u'nfs-common'])

TASK [nfs-server : Export directories] *****************************************
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "[{u'path': u'/home', u'clients': u'{{groups.slurm_worker + groups.slurm_submit|default([])}}'}]: 'dict object' has no attribute 'slurm_worker'"}
 [WARNING]: Could not create retry file '/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'.         [Errno 30] Read-only file system: u'/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'

PLAY RECAP *********************************************************************
frontend001                : ok=47   changed=3    unreachable=0    failed=1   

2017-03-31 17:23:10 rhino1 gc3.elasticluster[40939] ERROR Command `ansible-playbook /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.yml --inventory=/fh/fast/_ADM/SciComp/user/dirk/.elasticluster/storage/gce-slurm.inventory --become --become-user=root` failed with exit code .
2017-03-31 17:23:10 rhino1 gc3.elasticluster[40939] ERROR Check the output lines above for additional information on this error.
2017-03-31 17:23:10 rhino1 gc3.elasticluster[40939] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2017-03-31 17:23:10 rhino1 gc3.elasticluster[40939] WARNING Cluster `gce-slurm` not yet configured. Please, re-run `elasticluster setup gce-slurm` and/or check your configuration

WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     gce-slurm
Cluster template: gce-slurm
Default ssh to node: frontend001
- worker nodes: 2
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh gce-slurm

To upload or download files to the cluster, use the command:

    elasticluster sftp gce-slurm

**Comment by dirkpetersen** [comment]
This is my current config: 

# For Amazon instead (region us-east-1) you can use:
#

# For Google Compute Engine you can use:
#
[cloud/google]
provider=google
gce_client_id=
gce_client_secret=
gce_project_id=scicomp-compute
zone=us-west1-b
##noauth_local_webserver=True

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
#user_key_private=~/.ssh/id_rsa
#user_key_public=~/.ssh/id_rsa.pub
user_key_private=~/.ssh/id_rsa_ansible
user_key_public=~/.ssh/id_rsa_ansible.pub

#
[login/google]
image_user=fredhutch.gcp
#image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
#user_key_private=~/.ssh/id_rsa
#user_key_public=~/.ssh/id_rsa.pub
user_key_private=~/.ssh/id_rsa_ansible
user_key_public=~/.ssh/id_rsa_ansible.pub

[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker

[cluster/gce-slurm]
cloud=google
#login=ubuntu
login=google
setup=ansible-slurm
security_group=default
image_id=ubuntu-1604-xenial-v20170307
flavor=n1-standard-1
frontend_nodes=1
worker_nodes=2
image_userdata=
ssh_to=frontend

**Comment by dirkpetersen** [comment]
so it seems this is actually an issue with the NFS server. I am having this problem consistently with ubuntu16, ubuntu16 and debian8, with slurm and gridengine

TASK [nfs-server : install NFS server software] ********************************
task path: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nfs-server/tasks/main.yml:12
changed: [frontend001] => (item=[u'nfs-kernel-server', u'nfs-common']) => {"cache_update_time": 1491017005, "cache_updated": false, "changed": true, "item": ["nfs-kernel-server", "nfs-common"], "stderr": "", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe f}

TASK [nfs-server : Export directories] *****************************************
task path: /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/roles/nfs-server/tasks/main.yml:25
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "[{u'path': u'/home', u'clients': u'{{groups.slurm_worker + groups.slurm_submit|default([])}}'}]: 'dict object' has no attribute 'slurm_worker'"}
 [WARNING]: Could not create retry file '/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'.         [Errno 30] Read-only file system: u'/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'


PLAY RECAP *********************************************************************
frontend001                : ok=51   changed=28   unreachable=0    failed=1   

2017-03-31 20:31:25 rhino1 gc3.elasticluster[16876] ERROR Command `ansible-playbook /app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.yml --inventory=/fh/fast/_ADM/SciComp/user/dirk/.elasticluster/storage/gce-slurm.inventory --become --become-user=root -vv` failed with exit c.
2017-03-31 20:31:25 rhino1 gc3.elasticluster[16876] ERROR Check the output lines above for additional information on this error.
2017-03-31 20:31:25 rhino1 gc3.elasticluster[16876] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2017-03-31 20:31:25 rhino1 gc3.elasticluster[16876] WARNING Cluster `gce-slurm` not yet configured. Please, re-run `elasticluster setup gce-slurm` and/or check your configuration

WARNING: YOUR CLUSTER IS NOT READY YET!

Cluster name:     gce-slurm
Cluster template: gce-slurm
Default ssh to node: frontend001
- frontend nodes: 1
- worker nodes: 2

**Comment by riccardomurri** [comment]
> so it seems this is actually an issue with the NFS server

Indeed.  

I can reproduce the issue; will look into it later (possibly on Monday), but anyway it looks like running the playbook a second time fixes the issue.

In other words, after `elasticluster start xxx` fails, just run `elasticluster setup xxx` and it should proceed to (successful) completion.

**Comment by dirkpetersen** [comment]
Thanks, using `elasticluster setup` does not fix it for me.  My google user  for [login/google] image_user= does contain a dot. hopefully that does not cause on issue

**Comment by dirkpetersen** [comment]
Ah, I seems it cannot create the  site.retry file. This is because we use central shared python installs that are readonly (virtual envs are not maintainable for us).  Can the site.retry be created somewhere in ~./elasticluster instead ?

[WARNING]: Could not create retry file '/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'.         [Errno 30] Read-only file
system: u'/app/python2/2.7.13/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry'

**Comment by dirkpetersen** [comment]
i now installed elasticluster in virtualenv but am still getting this, not sure how to apply limit

TASK [nfs-server : Export directories] *****************************************
fatal: [frontend001]: FAILED! => {"failed": true, "msg": "[{u'path': u'/home', u'clients': u'{{groups.slurm_worker + groups.slurm_submit|default([])}}'}]: 'dict object' has no attribute 'slurm_worker'"}
	to retry, use: --limit @/fh/fast/_ADM/SciComp/user/dirk/elasticluster/lib/python2.7/site-packages/elasticluster/share/playbooks/site.retry

**Comment by riccardomurri** [comment]
Hmmm, wait the config you posted is *not* correct.

Here's the issue::

>         [setup/ansible-slurm]
>         provider=ansible
>         frontend_groups=slurm_master
>         compute_groups=slurm_worker

Fine, so you want to set up a cluster with two node groups, one named
"frontend" and one named "compute".  However:

>         [cluster/gce-slurm]
>         # ...
>         frontend_nodes=1
>         worker_nodes=2

Here you require that cluster `gce-slurm` has two kinds of nodes, one
called "frontend" (OK) and one called "worker".

So the problem lies in the mismatch in node group names across the
`cluster/gce-slurm` and the `setup/ansible-slurm` sections.

(I agree that ElastiCluster should detect this and report a
configuration error early on, instead of treating undefined node groups
as "empty".)

Can you please try if fixing the configuration fixes the issue?

**Comment by riccardomurri** [comment]
> Ah, I seems it cannot create the site.retry file. This is because we
> use central shared python installs that are readonly (virtual envs are
> not maintainable for us). Can the site.retry be created somewhere in
> ~./elasticluster instead ?

The `site.retry` file is created by Ansible and *not* used by
ElastiCluster.  I'll see if I can disable it altogether, as it's
typically not useful at all in ElastiCluster.

**Comment by riccardomurri** [comment]
> > so it seems this is actually an issue with the NFS server
> 
> Indeed.  I can reproduce the issue *[...]*

I stand corrected: there *is* possibly some issue with NFS, but only appears
intermittently, I have not so far been able to pinpoint the causes, and anyway
it looks like it has nothing to do with *this* issue (which is most likely
caused by inconsistent configuration, see above).

**Comment by dirkpetersen** [comment]
doh, I had not paid attention to keys being variable ...thanks for pointing this out!

SETUP NOW WORKS

 [setup/ansible-slurm]
         provider=ansible
         frontend_groups=slurm_master
         worker_groups=slurm_worker

**Comment by riccardomurri** [comment]
Ok, not ElastiCluster will complain if a cluster definition has different node names than the `setup/*` section -- see https://github.com/gc3-uzh-ch/elasticluster/commit/6a65128af1acca01ca9dc9f0606a033db9f65ee7

I guess this would have prevented the issue you ran into.

OK to consider this as solved now?
