### ISSUE TITLE
ceph configuration documentation

### ISSUE THREAD

**Issue by lila** [gc3-uzh-ch/elasticluster#417]
would be nice to have some documentation on the variables and options for the ceph config at:  http://elasticluster.readthedocs.io/en/latest/playbooks.html

**Comment by riccardomurri** [comment]
Indeed, I would like to have that too :-)

Srsly, that playbook has been contributed long time ago with no documentation -- I would have to reconstruct what it does (assuming it still works with the current version of Ceph) before I can document it...

Maybe @arcimboldo or @blmt can help?
