### ISSUE TITLE
Populating variables from the OS

### ISSUE THREAD

**Issue by kuzlovsky** [gc3-uzh-ch/elasticluster#421]
Hello,

In a template I would like to do something like:
{% for gpu_device in gpu_devices %}

Is it possible to fill the variable gpu_devices from the OS?

The bash command would be:
$(ls /dev/nvidia[0-9]*)

Or alternatively could set it from python:
import glob; glob.glob('/dev/nvidia[0-9]*')

I am not sure how to write this down:
gpu_devices={{$(ls /dev/nvidia[0-9]*)}}

Regards,
Joe

**Comment by riccardomurri** [comment]
Looks to me more of a "how do I do this in Ansible" question than an actual ElastiCluster issue?

Anyway, if you can trust `$(ls /dev/nvidia[0-9]*)` to return the right answer,
then why not just use it and register the output? Something like the following
Ansible tasks (untested)::

    - name: List GPU devices
      shell: |
        ls -1 /dev/nvidia[0-9]*
      register: ls_gpus
      
    - name: Fail if no GPUs
      fail:
        msg: 'No GPUs detected!'
      when: ls_gpus|failed
      
    - name: Print GPU device names for debugging
      debug:
        msg: '{% for gpu in ls_gpus.stdout.split() %}{{ gpu }}{% endfor %}'

**Comment by kuzlovsky** [comment]
Thank you @riccardomurri for the pointer, I did not know the difference between eleasticluster, ansible and Jinja2

I looked them up and could make it work :)

For anyone else I ended up using `ls -1 /dev/nvidia[0-9]* 2> /dev/null || true`, if you need the count you can use `{{ls_gpus.stdout.split()|length}}`
