### ISSUE TITLE
Installation error: version conflict for `pbr`

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#430]
I see the following error on an RHEL 7.1 VM, after manually upgrading `setuptools`:
```
(elasticluster)bash-4.2$ elasticluster list
Traceback (most recent call last):
  File "/home/ahuffman/src/venv/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pbr 1.10.0 (/home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages), Requirement.parse('pbr>=2.0.0'), set(['oslo.i18n', 'oslo.serialization', 'oslo.utils', 'debtcollector']))
```

**Comment by riccardomurri** [comment]
Can you please run the following and post the output?

    find /home/ahuffman/src/venv/elasticluster/lib/python2.7/site-packages -name '*.py' | xargs egrep "(from|import) +pbr"

**Comment by riccardomurri** [comment]
Nevermind, I found the issue: the problem is a combination of several factors:

- ElastiCluster pins `python-novaclient` to version `<8.0.0` because of #425 
- package `python-novaclient==7.1.0` depends on `pbr<2.0.0`
- newer OpenStack packages require `pbr>=2.0.0`
- `pip` does not resolve version conflicts in the whole dependency tree, only at top-level (it has already been reported as a `pip` bug but no progress yet)

The quick fix is to just install the same set of packages that are installed for Python 2.6.

**Comment by riccardomurri** [comment]
(Not specific to RHEL, just reproduced on a Ubuntu VM.)

**Comment by verdurin** [comment]
Okay, thanks. Just tried on a `CentOS 7.3` VM and saw the same thing, but you've already found it's more general anyway.

**Comment by riccardomurri** [comment]
There is now pull request #429 to support libcloud (which also has an OpenStack backend) -- this might be a good time to test it, if you had time :-)

**Comment by thomasdstewart** [comment]
I just ran into this on Debian testing (Stretch), I was able to workaround with:
pip install 'python-novaclient==7.0.0'; pip install --upgrade pbr

**Comment by riccardomurri** [comment]
There is a fixed version of the code in branch "issues/#425" at http://github.com/riccardomurri/elasticluster

I will merge it into "master" after it has received some independent testing, likely early next week.

**Comment by riccardomurri** [comment]
hey @witlox , can you please test the branch with the proposed fix?

**Comment by witlox** [comment]
still complaining on pbr
pkg_resources.ContextualVersionConflict: (pbr 1.10.0 (.../elasticluster/lib/python2.7/site-packages), Requirement.parse('pbr>=2.0.0'), set(['python-neutronclient', 'debtcollector', 'oslo.utils']))

**Comment by thomasdstewart** [comment]
I gave that branch a try and I was able to run elasticluster and resize a cluster. Via:

$ virtualenv elasticlustertest
$ . elasticlustertest/bin/activate
$ cd elasticlustertest
$ git clone https://github.com/riccardomurri/elasticluster.git src
$ cd src
$ git checkout issues/#425
$ pip install -e .
$ elasticluster resize ...

**Comment by riccardomurri** [comment]
@witlox do you run into the issue with an *existing* virtualenv? do you still get the error in a *new* clean-slate virtualenv?

**Comment by witlox** [comment]
after wiping the virtualenv it works, good work!

**Comment by riccardomurri** [comment]
Fixed `setup.py` is now up in "master" and the workaround is now documented in ElastiCluster "troubleshooting" document.

Thank you all for reporting and for promptly testing!  It's fantastic to receive such prompt replies in a call for help!
