### ISSUE TITLE
Divergence between install.rst and troubleshooting.rst

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#435]
The latest changes with the `pip` workaround fix various problems for me on `CentOS`.

However, I noticed that there's now a variation in the `pip` upgrade suggestions between `install.rst` and `troubleshooting.rst`, with the former suggesting `pip>=9.0.0` while the latter suggests `pip>=8.1.2`.

I know the suggestions are for different reasons, but it might cause confusion to diverge like this.

**Comment by riccardomurri** [comment]
Just fixed in "master".  

Thanks a lot! it's rare to find people who actually read the docs, and rarer even to find those who suggest improvements!
