### ISSUE TITLE
elasticluster list-templates fails on centos6 with python2.6

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#449]
Have followed installation instructions on centos6 with python 2.6.6. According to the elasticluster documentation 2.6 python should be fine to use. 

Get the following:
``
(elasticluster)[centos@elasticluster` ~]$ elasticluster list-templates
/home/centos/elasticluster/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/home/centos/elasticluster/bin/elasticluster", line 9, in <module>
    load_entry_point('elasticluster==1.2', 'console_scripts', 'elasticluster')()
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/home/centos/elasticluster/lib/python2.6/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/centos/elasticluster/lib/python2.6/site-packages/elasticluster/__init__.py", line 31, in <module>
    from elasticluster.providers.ansible_provider import AnsibleSetupProvider
  File "/home/centos/elasticluster/lib/python2.6/site-packages/elasticluster/providers/ansible_provider.py", line 30, in <module>
    import ansible.callbacks as anscb
ImportError: No module named callbacks
``

**Comment by riccardomurri** [comment]
Hello @maikenp :

From the traceback it looks like you are running a very old version of the ElastiCluster code (the dependency on `ansible.callbacks` was removed long ago: commit https://github.com/gc3-uzh-ch/elasticluster/commit/0068bcd9c25dd6caf59825ae7df9c81f5ad1273f on Dec. 4, 2015).

How did you install ElastiCluster?  What instructions did you follow?

**Comment by maikenp** [comment]
I see, how strange. I followed the instructions on:
https://elasticluster.readthedocs.io/en/latest/install.html

**Comment by riccardomurri** [comment]
Can you please run the following command and post the output here?

    pip freeze | grep elasticluster

**Comment by maikenp** [comment]
elasticluster)[centos@elasticluster ~]$ pip freeze | grep elasticluster
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
elasticluster==1.2

**Comment by riccardomurri** [comment]
As noted in #448, ElastiCluster 1.2 should not be used any more.  Please install from GitHub following https://elasticluster.readthedocs.io/en/latest/install.html#installing-development-code-from-github

Also note that, although ElastiCluster itself is still compatible with Python 2.6, dependency packages are dropping support for it.  If you're on CentOS/RHEL, use the [Software Collections Library](https://wiki.centos.org/SpecialInterestGroup/SCLo/CollectionsList) e.g. see https://gist.github.com/dalegaspi/dec44117fa5e7597a559

**Comment by maikenp** [comment]
I see, thank you.
