### ISSUE TITLE
image_userdata parameter is ignored

### ISSUE THREAD

**Issue by rnaplus** [gc3-uzh-ch/elasticluster#461]
I have been trying to setup a script to run automatically upon node creation by setting the `image_userdata` key in the cluster section of the config file. It seems to be ignored as I have not seen any indication that the parameter is doing anything at all. Here's a snippet of my config:

```
[cluster/mycluster]
cloud=google
login=google-login
setup_provider=ansible-gridengine
security_group=default
image_id=debian-8-jessie-v20170227
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=2
image_userdata=#!/bin/bash
        echo Success! > /home/rnaplus/startup.log
ssh_to=frontend
```

I have also tried passing the entire command list as a single string. e.g.:
`image_userdata='#!/bin/bash; echo Success! > /home/rnaplus/startup.log'`

My current solution is to specify a custom image using the `image_id` parameter, where the image is already in the desired state (so no need to run script).

**Comment by lila** [comment]
see https://github.com/gc3-uzh-ch/elasticluster/issues/393 for a fix... (that was a while ago)...

- k

**Comment by riccardomurri** [comment]
Oooops! I guess it's high time I fix it them ;-)

Can you check if PR #492 solves the issue?

**Comment by riccardomurri** [comment]
PR #492 merged into "master". I think this solves the issue, please feel free to re-open if not.
