### ISSUE TITLE
When rebooting frontend after changing selinux to disabled, can not any longer reach the comput-nodes with ssh

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#466]
Hi, 

after successfully starting my cluster, I need to loginto the frontend in order to disable selinux. This is needed in order to get ARC grid software working on the frontend. 

After rebooting the frontend (to get the new selinux setting in play) I do not any more reach the compute nodes with ssh. 

However, if I restart the compute nodes too, everything works fine. 

Is there a way to avoid having to reboot the compute nodes also?

**Comment by riccardomurri** [comment]
> after successfully starting my cluster, I need to loginto the frontend in order to disable selinux. This is needed in order to get ARC grid software working on the frontend. 
> 
> After rebooting the frontend (to get the new selinux setting in play) I do not any more reach the compute nodes with ssh. 
> 
> However, if I restart the compute nodes too, everything works fine. 
> 
> Is there a way to avoid having to reboot the compute nodes also?

It should not be necessary to reboot the compute nodes at all -- I mean
if it happens, it's either a bug in ElastiCluster or there's something
unexpected in your VMs/infrastructure/etc.

If you *don't* disable SELinux on the front-end, do you still need to
reboot the compute nodes?

**Comment by maikenp** [comment]
No, if I do not disable SELinux and reboot the frontend, then there is no need to reboot the compute nodes, then things work as they should. 

However, I do need to disable SELinux. And this requires a reboot of the frontend, and hence then the compute nodes :)

**Comment by maikenp** [comment]
Ah, question is: if I just restart the frontend without disabling SeLinux. Yes, will try that and report.

**Comment by riccardomurri** [comment]
> However, I do need to disable SELinux. And this requires a reboot of
> the frontend, and hence then the compute nodes :)

Can't you just set it to *not enforcing* ?

        # as root, run:
        setenforce 0

**Comment by maikenp** [comment]
It is possible it is an option. I will test it out, will not know completely until I have actually managed to correctly configure ARC to receive jobs. Then I will let you know. Thanks!

**Comment by maikenp** [comment]
It is probably due to some settings on our end. I will close the issue as I do not mind the need to reboot all cluster at the moment.
