### ISSUE TITLE
Setting up the frontend only after initial start and setup of cluster

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#467]
Hi,

After successfully having started and initially setup my cluster, I need to install ARC grid software on the frontend. 

I use
`elasticluster start slurm -n gridcluster`
to start and initially set up the cluster with 1 frontend and 2 compute nodes.  

To manage this I have had to use the attached configuration file  [config.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1176730/config.txt) which is placed in my .elasticluster folder, and it uses the default name: config. 

I then need to install ARC on the frontend. To do this I have had to do the following
`elasticluster  setup gridcluster -- playbooks/playbook_arc_install_uh-sky_setup.yml`

which then as you see takes my custom ansible playbook (playbook_arc_install_uh-sky_setup.yml) and installs arc. 

In [config.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1176730/config.txt)  you see that I have added in 
`[setup/ansible-slurm]`
`frontend_groups=slurm_master,ganglia_master,ganglia_monitor,arccetest`

which is needed in order for the arc-installation to take place once I run my custom playbook. In the initial start and setup, the arccetest is ignored, I assume since the default playbook does not contain any information about this custom playbook. 

When I do the setup gridcluster command above, then the arccetest kicks in, and ARC is installed on my frontend node. This does work, however, it also goes through all the other setup stuff, slurm, ganglia, on both frontend and compute notes and this takes a long time. 

What I would like to achieve is for the ARC setup to use my custom playbook and a custom configuration file (something like this ) [config_frontend.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1176754/config_frontend.txt)  just for setting up the frontend.  Or alternatively like this [configv2.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1176714/configv2.txt), which will then be run at the same time as the startup and initial setup. 

In the case of using the config_frontend I envisage being able to do

`elasticluster setup gridcluster -c config_frontend -- mycustomplaybook`

In the case of using the configv2 I will need elasticluster to use two playbooks, the default one, and my custom one, since I am imagining then just needing to do
`elasticluster start slurm -n gridcluster` 
and both playbooks being available, hence both setups (ansible-slurm and ansible-arc) being performed. 

How would be the recommended way to achieve this? 

Thanks!

**Comment by riccardomurri** [comment]
> What I would like to achieve is for the ARC setup to use my custom
> playbook *[...]* which will then be run at the same time as the
> startup and initial setup.

There are a couple of ways to achive this effect right now (albeit
both are more convoluted than I'd wish).

* You can modify the [`after.yml`][1] file in the
  `elasticluster/share/playbooks/` directory within the ElastiCluster
  sources.  This is a normal Ansible playbook, so you can just copy
  your "arcce.yml" file there (basically, it's the same as running
  `elasticluster setup slurm -- after.yml`)::
  
        ---
        - name: Apply local customizations (after)
          tags:
            - after
            - local
          hosts: arccetest
          roles: []
          tasks: 
            # put your ARC CE stuff here

* You can run `elasticluster start --no-setup`: this starts VMs but
  does *not* run the playbooks so finishes quickly.  Then you run
  `elasticluster setup ... -- my-playbook.yml`
  
The latter solution is more robust against code updates etc.

In the long run, I would like to add configuration options `after=`
and `before=` to the `[setup/*]` section, which should allow to add
arbitrary arguments to the `ansible-playbook` command line, including
additional playbooks to run.

[1]: https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/after.yml

**Comment by maikenp** [comment]
Thanks a lot for that.

When it comes to the first option, I would need to extract the ip-adress of the frontend automatically, as it must be known to my playbook.yml . Is this possible?


_______________________________
Maiken Pedersen
Research Computing Services, USIT
University of Oslo, Norway
mob: +47 466 28 328


On 26 Jul 2017, at 17:30, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:


What I would like to achieve is for the ARC setup to use my custom
playbook [...] which will then be run at the same time as the
startup and initial setup.

There are a couple of ways to achive this effect right now (albeit
both are more convoluted than I'd wish).

  *   You can modify the after.yml<https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/after.yml> file in the
elasticluster/share/playbooks/ directory within the ElastiCluster
sources. This is a normal Ansible playbook, so you can just copy
your "arcce.yml" file there (basically, it's the same as running
elasticluster setup slurm -- after.yml)::

  ---
  - name: Apply local customizations (after)
    tags:
      - after
      - local
    hosts: arccetest
    roles: []
    tasks:
      # put your ARC CE stuff here


  *   You can run elasticluster start --no-setup: this starts VMs but
does not run the playbooks so finishes quickly. Then you run
elasticluster setup ... -- my-playbook.yml

The latter solution is more robust against code updates etc.

In the long run, I would like to add configuration options after=
and before= to the [setup/*] section, which should allow to add
arbitrary arguments to the ansible-playbook command line, including
additional playbooks to run.

**Comment by riccardomurri** [comment]
> When it comes to the first option, I would need to extract the
> ip-adress of the frontend automatically, as it must be known to my
> playbook.yml

You do not need that.  This is what the `hosts: ...` line in the
playbooko is for.  Just replace `...` with any Ansible group the
front-end is in, e.g. `slurm_master` or `arccetest` (assuming you had
`frontend_groups=slurm_master,arccetest` in your configuration).

**Comment by maikenp** [comment]
Sorry, I was a bit too unclear.

In my playbook I create a configuration file from a template in my  roles/arc_install/template

This uses a variable I set in my playbook:


- hosts: arccetest
  gather_facts: no

  vars:
    - hostname_ip: "158.37.63.170"

  roles:
    - arc_install


The actual ip-adress is needed in my ARC configuration file. And it would be nice not to have to edit the playbook before running it.

_______________________________
Maiken Pedersen
Research Computing Services, USIT
University of Oslo, Norway
mob: +47 466 28 328


On 26 Jul 2017, at 20:04, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:

> When it comes to the first option, I would need to extract the
> ip-adress of the frontend automatically, as it must be known to my
> playbook.yml

You do not need that. This is what the `hosts: ...` line in the
playbooko is for. Just replace `...` with any Ansible group the
front-end is in, e.g. `slurm_master` or `arccetest` (assuming you had
`frontend_groups=slurm_master,arccetest` in your configuration).

**Comment by riccardomurri** [comment]
> In my playbook I create a configuration file from a template
> This uses a variable I set in my playbook: 
>
>       - hosts: arccetest 
>         gather_facts: no 
>         vars: 
>         - hostname_ip: "158.37.63.170"

You can use `{{ ansible_default_ipv4.address }}` in the template to find the IP address that Ansible uses to connect to the machine.  Is this what you are looking for?

**Comment by riccardomurri** [comment]
This StackOverflow answer is relevant: https://stackoverflow.com/a/39822604/459543

**Comment by maikenp** [comment]
Thanks a lot for that. What did the trick was the following: 
`"{{ hostvars['frontend001'].ansible_default_ipv4.address }}"`

Hopefully final question about running my own playbooks after the VM has started. 

Assume I have already created a VM. And then I want to set it up with my custom stuff. Then I can not do as you suggest: 

> You can run elasticluster start --no-setup: this starts VMs but does not run the playbooks so finishes quickly. Then you run elasticluster setup ... -- my-playbook.yml

since it has already started, right? 

Right now, since I have to have all the stuff the setup has to do in one single line: 
`frontend_groups=slurm_master,ganglia_master,ganglia_monitor,arccetest`

it goes checking all of these even though it will just really do any action on the accetest.  This is what takes a lot of time. 

I prefer to run the setup step after starting the VM. As I might want to run the setup several times. I do not then want to start and stop the cluster, as it each time gets destroyed when I stop it. 

I might be misunderstanding some basics here. Sorry for that if this is the case! :)

**Comment by riccardomurri** [comment]
I think there's two different questions here:

> Assume I have already created a VM. And then I want to set it up with my custom stuff. Then I can not do as you suggest: 
> 
> > You can run elasticluster start --no-setup: this starts VMs but does not run the playbooks so finishes quickly. Then you run elasticluster setup ... -- my-playbook.yml
> 
> since it has already started, right?

You can run `elasticluster setup` at any time on a running cluster.  It
will just re-run Ansible and go through all the playbooks again.

So, yes, it will do what you lament here:

> it goes checking all of these even though it will just really do any
> action on the accetest.  This is what takes a lot of time.

To only run a portion of the playbooks, use the Ansible "tags"
mechanism:

1. Tag your playbook with e.g. the "ARC" tag::

        # contents of arc.yml
        ---
        - name: Apply local customizations (after)
          # ||| HERE |||
          # vvv      vvv
          tags:
          - ARC
          hosts: arccetest
          tasks:
             # ...

2. Run the `setup` command with `-t ARC`::

        elasticluster setup mycluster -- arc.yml -t ARC

   This will skip any action on playbooks that are *not* tagged ARC,
   i.e., only execute "ARC"-tagged plays.

Hope this helps!

**Comment by maikenp** [comment]
Ah yes, that really helps yes, thanks for that!

_______________________________
Maiken Pedersen
Research Computing Services, USIT
University of Oslo, Norway
mob: +47 466 28 328


On 27 Jul 2017, at 17:23, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:

I think there's two different questions here:

> Assume I have already created a VM. And then I want to set it up with my custom stuff. Then I can not do as you suggest:
>
> > You can run elasticluster start --no-setup: this starts VMs but does not run the playbooks so finishes quickly. Then you run elasticluster setup ... -- my-playbook.yml
>
> since it has already started, right?

You can run `elasticluster setup` at any time on a running cluster. It
will just re-run Ansible and go through all the playbooks again.

So, yes, it will do what you lament here:

> it goes checking all of these even though it will just really do any
> action on the accetest. This is what takes a lot of time.

To only run a portion of the playbooks, use the Ansible "tags"
mechanism:

1. Tag your playbook with e.g. the "ARC" tag::

# contents of arc.yml
---
- name: Apply local customizations (after)
# ||| HERE |||
# vvv vvv
tags:
- ARC
hosts: arccetest
tasks:
# ...

2. Run the `setup` command with `-t ARC`::

elasticluster setup mycluster -- arc.yml -t ARC

This will skip any action on playbooks that are *not* tagged ARC,
i.e., only execute "ARC"-tagged plays.

Hope this helps!

**Comment by maikenp** [comment]
I close the issue, thanks a lot for the good tip. And it is just ansible stuff, so will tweak according to what elasticluster allows there.
