### ISSUE TITLE
lua version error with elasticluster and centos7

### ISSUE THREAD

**Issue by laurapoggio-sptools** [gc3-uzh-ch/elasticluster#470]
I am using elasticluster version 1.3.dev0. Since yesterday I get the following error

`
failed: [frontend001] (item=[u'lua-5.1.4.8', u'lua-filesystem', u'lua-posix', u'lua-term']) => {"changed": false, "failed": true, "item": ["lua-5.1.4.8", "lua-filesystem", "lua-posix", "lua-term"], "msg": "No package matching 'lua-5.1.4.8' found available, installed or updated", "rc": 126, "results": ["No package matching 'lua-5.1.4.8' found available, installed or updated"]}
`

I am using the same config file as before, but I installed elasticluster on a new machine with the newest version from git.
The latest lua package in centos7 repository is 5.1.4
The machine uses the latest centos image available on google cloud: centos-7-v20170719

The cluster is created but SGE is not installed.

Thanks a lot

**Comment by laurapoggio-sptools** [comment]
My config file:

```
[cloud/google]
provider=google
gce_client_id=*****
gce_client_secret=*****
gce_project_id=*****
zone=europe-west1-b
noauth_local_webserver=True

# Create a login (call it "google-login")
[login/google-login]
image_user=myuser
image_user_sudo=root
image_sudo=True
user_key_name=myuser
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Gridengine software to be configured by Ansible
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

# Bring all of the elements together to define a cluster called "gridengine"
[cluster/gridengine]
cloud=google
login=google-login
setup=ansible-gridengine
security_group=default
image_id=centos-7-v20170719
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=2
image_userdata=
ssh_to=frontend

```

**Comment by riccardomurri** [comment]
This should be fixed in the latest "master" branch (commit 1078d5f or later).

Can you please test it and confirm that it works?

**Comment by laurapoggio-sptools** [comment]
Tested with latest centos image available on google cloud: centos-7-v20170719 and it worked.
Thanks

**Comment by riccardomurri** [comment]
Glad to know it's working! Many thanks for testing promptly! :-)
