### ISSUE TITLE
region_name ignored when using openstack

### ISSUE THREAD

**Issue by pescobar** [gc3-uzh-ch/elasticluster#473]
Hi all,

I am using elasticluster with an openstack cloud which has two regions (ZH and LS)

I have noticed that no matter what I use as "region_name" in the elasticluster configuration, always the first region is used (ZH in this case). 

I was getting really strange errors `No image found with ID found` or `Network xxxxx could not be found`. Out of ideas trying to debug the issue I tried to use `region_name=LS` using the node_id and network_id from region ZH and then elasticluster booted correctly :|

It seems that elasticluster ignores "region_name" in the config. It always uses region ZH no matter what I define in the configuration file

**Comment by riccardomurri** [comment]
Hello,

This should have been fixed in commit 477b120 (i.e., HEAD~).

This is one commit before the one that you reported as troublesome on the
mailing list.

Can you please try it and tell me if it works?

Ciao,
R

**Comment by riccardomurri** [comment]
At least, it should work if you set the environment variable OS_REGION_NAME.

Il 07 ago 2017 11:51 AM, "Riccardo Murri" <riccardo.murri@gmail.com> ha
scritto:

> Hello,
>
> This should have been fixed in commit 477b120 (i.e., HEAD~).
>
> This is one commit before the one that you reported as troublesome on the
> mailing list.
>
> Can you please try it and tell me if it works?
>
> Ciao,
> R
>
>
>

**Comment by riccardomurri** [comment]
Isn't this the same issue as #471 ?

Il 07 ago 2017 11:52 AM, "Riccardo Murri" <riccardo.murri@gmail.com> ha
scritto:

> At least, it should work if you set the environment variable
> OS_REGION_NAME.
>
> Il 07 ago 2017 11:51 AM, "Riccardo Murri" <riccardo.murri@gmail.com> ha
> scritto:
>
>> Hello,
>>
>> This should have been fixed in commit 477b120 (i.e., HEAD~).
>>
>> This is one commit before the one that you reported as troublesome on the
>> mailing list.
>>
>> Can you please try it and tell me if it works?
>>
>> Ciao,
>> R
>>
>>
>>

**Comment by pescobar** [comment]
Hi @riccardomurri 

with my current commit `6c8c8f8528d71e613cc17e71e1c6e3050b9f4b18` defining `OS_REGION_NAME="LS"` didn't work

I haven't tried latest version in the master branch because I hit the problem I reported in the mailing list `ERROR Could not start node `compute002`: 'OpenStackCloudProvider' object has no attribute 'compute_api_version' `

thanks for your support

**Comment by riccardomurri** [comment]
Hello,

Can you please try checking out commit
 477b120 ?

It should work with regions (tested by @maikenp ) and does not have the
problem you reported on the mailing list.

Ciao,
R

**Comment by pescobar** [comment]
commit https://github.com/gc3-uzh-ch/elasticluster/commit/477b12045d58222b97c868c01dab3917c73b4932 seems to work fine. 

Thanks for you help @riccardomurri !!

**Comment by riccardomurri** [comment]
Do you get this error when operating on a old/existing cluster? (e.g., `elasticluster resize`) I cannot reproduce this with "new" clusters (i.e., `elasticluster start`)

Also: could you please post the complete Python traceback of the error?  You can get it when setting verbosity to DEBUG (`elasticluster -vvv ...`)

**Comment by riccardomurri** [comment]
I cannot reproduce this neither with new nor with old/existing clusters.

Can you please try again with the latest "master" branch and tell me if you still get the error?  If yes, please post a complete Python traceback (or email me if it's confidential/sensitive)

**Comment by pescobar** [comment]
@riccardomurri I have tested the latest code from master branch and now I am not hitting the problem of `'OpenStackCloudProvider' object has no attribute 'compute_api_version'` 

I cannot explain the reason but I guess this issue can be close.

p.s. sorry for the late reply. I have been overloaded latest days
