### ISSUE TITLE
elasticluster/share/etc/config.template has outdated instructions for GCE. 

### ISSUE THREAD

**Issue by mbasilyan** [gc3-uzh-ch/elasticluster#475]
The section beginning with "Google Compute Engine users" has outdated instructions (I can't follow them in the current UI).

**Comment by mbasilyan** [comment]
Yup -- It might be easier to replace the steps with a link to Google's official docs: maybe something like this: https://developers.google.com/identity/protocols/OAuth2

(Just a note: I work on GCE.)

**Comment by riccardomurri** [comment]
> Yup -- It might be easier to replace the steps with a link to Google's official docs: maybe something like this: https://developers.google.com/identity/protocols/OAuth2

I agree that a pointer to official docs would be better; this particular link, however, seems to me too much geared towards developers -- I suspect many users of ElastiCluster on GCE would be lost already at the introduction and need a more step-by-step guide (click here, copy this string, paste it in config file).

How about @mbookman 's guide? http://googlegenomics.readthedocs.io/en/latest/use_cases/setup_gridengine_cluster_on_compute_engine/index.html#index-obtaining-client-id-and-client-secrets -- is this still valid?

> (Just a note: I work on GCE.)

I know :) You joined the conf call organized by Karan, didn't you?

If you have any suggestions/patches/amendments for GCE please just go ahead and make a PR -- I know the source is trustworthy so I can just click the "merge" button ;-)

**Comment by riccardomurri** [comment]
I have reworded and reformatted a large portion of the `config.template` file:
https://github.com/riccardomurri/elasticluster/blob/issues/475/elasticluster/share/etc/config.template
Can you please take a look at it and see if it fixes the issue you've raised?

Also, if I may still borrow another bit of your time:

* the comments in the `config.template` file are basically an earlier version of the "configuration" manual page; would it make more sense to remove them altogether and just place a few links to the manual? (Or should the comments be rather more extensive, as people do not read manuals?)

* there is a number of commented examples collected at <https://github.com/riccardomurri/elasticluster/tree/issues/475/examples> which are more recent and better commented (IMHO) than the examples in both the `config.template` and the manual page... which examples should go into the `config.template`?
