### ISSUE TITLE
Scientific Linux support

### ISSUE THREAD

**Issue by nicolasbaer** [gc3-uzh-ch/elasticluster#48]
A few people at the academic cloud experience workshop asked me for support of scientific linux images. What do you think: would it make sense? He suggested to publish it there somewhere whenever we support it.

**Comment by riccardomurri** [comment]
Closing this now -- SL6 has been supported for a while in the SLURM playbooks, advertised at HEPiX, and still no-one seems to be using ElastiCluster with it outside of the UZH Physics Dept.
