### ISSUE TITLE
dl.fedoraproject.org Connection timed out

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#485]
I can readh the url from my browser (dl.fedoraproject.org) but below you see the failure. 

What could be the problem? Supposedly on the fedoraproject side? 

'''
TASK [common : enable the EPEL repository (RHEL/CentOS)] **********************************************************************************************************************************************************************************************************************************************************
changed: [compute001] => {"changed": true, "msg": "", "rc": 0, "results": ["Loaded plugins: fastestmirror, presto\nSetting up Install Process\nExamining /tmp/tmpwlm9Ke/epel-release-latest-6.noarch.rpm: epel-release-6-8.noarch\nMarking /tmp/tmpwlm9Ke/epel-release-latest-6.noarch.rpm to be installed\nDetermining fastest mirrors\n * base: ftp.uninett.no\n * extras: ftp.uninett.no\n * updates: ftp.uninett.no\nResolving Dependencies\n--> Running transaction check\n---> Package epel-release.noarch 0:6-8 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch       Version    Repository                         Size\n================================================================================\nInstalling:\n epel-release     noarch     6-8        /epel-release-latest-6.noarch      22 k\n\nTransaction Summary\n================================================================================\nInstall       1 Package(s)\n\nTotal size: 22 k\nInstalled size: 22 k\nDownloading Packages:\nRunning rpm_check_debug\nRunning Transaction Test\nTransaction Test Succeeded\nRunning Transaction\n\r  Installing : epel-release-6-8.noarch                                      1/1 \n\r  Verifying  : epel-release-6-8.noarch                                      1/1 \n\nInstalled:\n  epel-release.noarch 0:6-8                                                     \n\nComplete!\n"]}
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to dl.fedoraproject.org at port 443: [Errno 110] Connection timed out"}
'''

**Comment by riccardomurri** [comment]
Are you using a security group in OpenStack that forbids outgoing connections?  Or is the use of a proxy needed to connect to the internet from your cloud?

**Comment by pescobar** [comment]
@maikenp I would suggest that you ssh to one of the booted machines and try `ping 8.8.8.8` to double check if the machines have internet connectivity? If that works try `ping google.com` to double check if dns resolution works.

**Comment by maikenp** [comment]
Well, I just ran the same setup several times yesterday with success, and as far as I know I have not changed anything from then. 

Thanks for the tip. Machine is not booted at the moment, will check that once up and running.

**Comment by maikenp** [comment]
yes, so it miraculously works again :) Probably a problem with the actual server I was trying to connect to? I will close the issue.
