### ISSUE TITLE
- include: roles/some_role.yml

### ISSUE THREAD

**Issue by Marc0Polo** [gc3-uzh-ch/elasticluster#493]
It seems with latest ansible v2.4 version that "- include:" directives (#Deprecated) in site.yml must be only related to playbook root directory to benefit from group_vars and others global variables.
With "- include: roles/some_role.yml" group_vars variables are not fetched.
With "- include: some_role.yml" variables as group_vars are fetched.

**Comment by riccardomurri** [comment]
Same issue as #495, which see for more extensive discussion.

Fixed in the playbooks update, in commits ab3fa1c through d3cc5f9
