### ISSUE TITLE
Question: Change worker_nodes AMI while master is up

### ISSUE THREAD

**Issue by ctaperts** [gc3-uzh-ch/elasticluster#499]
I am trying to preserve the master while changing the worker nodes AMI for the sge cluster.

The issue is we would not like the Master Nodes IP to change between versions.

Is it possible to change the worker node AMI for the cluster while the master is up?

Thank you

**Comment by riccardomurri** [comment]
> Is it possible to change the worker node AMI for the cluster while the master is up?

In similar cases I have used the following approach:

1. In the config file, add a new worker node class to the cluster
   (let's call it `worker2`).  It should be a copy of class `worker`,
   with one little difference (detailed below)::

        [setup/mycluster]
        # ...
        worker_groups=...
        worker2_groups=<exact copy of worker_groups>

        [cluster/mycluster]
        setup=mycluster
        master_nodes=1
        worker_nodes=8
        worker2_nodes=8  # again, copy worker_*
        # ...

2. Override `image_id` (or any other parameter you want to change
   e.g. `flavor`), for class `worker2` only::

        [cluster/mycluster/worker2]
         image_id=<a different AMI>

3. Now add the new worker nodes to the cluster::

        elasticluster resize mycluster -a 8:worker2

4. Finally, you can remove the old worker nodes (make sure no job is running there first!)::

        elasticluster resize mycluster -r 8:worker

I have used this to add nodes with a larger flavor, but it should work
if you change the `image_id` or any other "construction" parameter.

**Comment by ctaperts** [comment]
you are awesome thanks!
