### ISSUE TITLE
Error creating a cluster of machine type n1-standard-96 (Skylake)

### ISSUE THREAD

**Issue by Smahanita** [gc3-uzh-ch/elasticluster#517]
Hello,
I'm getting an error when creating a cluster with n1-standard-96 machine type. Any idea how to set the instance to be skylake?

Here is the error:
`ERROR Error creating instance <HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/$project/zones/us-central1-a/instances?alt=json returned "Machine Types with more vCPUs than 64 and more memory than 455Gb are not supported for instances that do not have minimum CPU platform set to 'skylake' or higher.">`

Here is the config file:

```
[cloud/google]
provider=google
gce_client_id=
gce_client_secret=
gce_project_id=
noauth_local_webserver=True

[login/google]
image_user=$user
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker
submit_groups=slurm_submit,glusterfs_client
global_var_multiuser_cluster=yes


[cluster/clustergold]
cloud=google
login=google
security_group=default
image_id=https://www.googleapis.com/compute/v1/projects/$project/global/images/image-gold
boot_disk_type=pd-ssd
boot_disk_size=20
flavor=n1-standard-96
setup=slurm
frontend_nodes=1
compute_nodes=4
compute_nodes_min=2
ssh_to=frontend

```

**Comment by riccardomurri** [comment]
With the code in the "master" branch it is not currently possible to select a minimum CPU platform.

Can you please try the code in PR https://github.com/gc3-uzh-ch/elasticluster/pull/518 and see if it solves your issue?  With that code, you should be able to specify the minimum CPU platform by adding this line to the `[cluster/clustergold]` section::

    min_cpu_platform=Intel Skylake

**Comment by Smahanita** [comment]
Great! It worked with PR#518.
Thank you

**Comment by riccardomurri** [comment]
Glad it worked quickly this time!
