### ISSUE TITLE
htcondor on debian or ubuntu

### ISSUE THREAD

**Issue by maikenp** [gc3-uzh-ch/elasticluster#527]
Hi, 
I am giving the htcondor cluster a try, after successfully using elasticluster with slurm. 

I am encountering various problems, using elasticluster version 1.3.dev0

If I try with Debian 9:
The apt-get update fails I think due to some amd64 packages trying that can not be accessed (http://research.cs.wisc.edu/htcondor/debian/stable stretch/contrib amd64 Packages)
This is at least the error I get when logging into the newly created machine and trying apt-get update.  The error-message from elasicluster (ansible) is 
```
TASK [update package cache]
fatal: [compute001]: FAILED! => {"changed":false, "failed":true "msg": "Failed to update apt cache"}
```

Then I tried Ubuntu 17.10 instead, and I get error for the task "Install common HPC software" as 
libatlas-dev is not available. 

Should elasticluster work with debian 9 and/or ubuntu 17.10? 

Best wishes
Maiken

**Comment by riccardomurri** [comment]
To be honest, I haven't used the HTCondor setup since a few years now, so the playbook is likely broken with any current OS... I can try to bring it up-to-date but it will take a few days.

Two questions for you:

* How urgent is this?
* What OS should have priority? (Debian 9 / Ubuntu 16.04 / CentOS 7)

**Comment by maikenp** [comment]
Ok, thanks for quick response. 

It is not super-urgent, but would be nice to have it soonish. I can help debug. 
Would prefer centos7 but can be debian/ubuntu too depending on what is easiest. 


Seems the package name has changed from libatlas-dev to libatlas-base-dev

**Comment by maikenp** [comment]
For the centos case by the way the playbook breaks in

"Fix configuration file" task /etc/condor destination dir does not exist. 

I can try to debug a bit and see where I get and get back to you if I find some solutions. That might help speed things up.

**Comment by maikenp** [comment]
Trying again with Debian 
Changes needed in playbooks: 

in htcondor.yml
```
group.condor_workers -> groups.condor_worker
```

In htcondor.yml
NFS_EXPORT  add items dash, change

```
NFS_EXPORTS:
  path: '/home'
  clients...
```
to
```
NFS_EXPORTS:
  - path: '/home'
     clients: ...
```

cache update fails for some yet unidentified reason. Have set it to be ignored. 

Then the cluster actually gets set up at least, but have not yet tested if it is doing what it should. 

Maiken

**Comment by riccardomurri** [comment]
Hmmm... it looks like HTCondor does *not* support Debian 9, nor Ubuntu 16.04:
http://research.cs.wisc.edu/htcondor/instructions/

The latest version (8.7.x) is only packaged for Debian 8.x and Ubuntu 12.04 and 14.04 and CentOS7 (which is however not currently supported by ElastiCluster's playbook -- ATM entirely Debian/Ubuntu-centric).

**Comment by maikenp** [comment]
Right, then I go for Debian 8, that is not a big problem.

On 13 Mar 2018, at 15:16, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm... it looks like HTCondor does not support Debian 9, nor Ubuntu 16.04:
http://research.cs.wisc.edu/htcondor/instructions/

The latest version (8.7.x) is only packaged for Debian 8.x and Ubuntu 12.04 and 14.04 and CentOS7 (which is however not currently supported by ElastiCluster's playbook -- ATM entirely Debian/Ubuntu-centric).

**Comment by riccardomurri** [comment]
I have pushed at https://github.com/riccardomurri/elasticluster in branch `issue/#527` the modified code (including the fixes you suggested above) that works on Debian 8.

I'll check it on Ubuntu 14.04 and then make a PR.

**Comment by riccardomurri** [comment]
Same branch also works with Ubuntu 14.04 (I can successfully run the "sleep" example in http://research.cs.wisc.edu/htcondor/manual/quickstart.html)

**Comment by riccardomurri** [comment]
Pushed code that fixes this to https://github.com/gc3-uzh-ch/elasticluster/pull/528

@maikenp Can you please test it and confirm that it works?

**Comment by maikenp** [comment]
Yes I will, and get back to you.

**Comment by riccardomurri** [comment]
Pushed code that fixes this to https://github.com/gc3-uzh-ch/elasticluster/pull/528

@maikenp Can you please test it and confirm that it works?

**Comment by maikenp** [comment]
I will. Will give an update on it tomorrow. Thanks!

On 14 Mar 2018, at 21:18, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:


Pushed code that fixes this to #528<https://github.com/gc3-uzh-ch/elasticluster/pull/528>

@maikenp<https://github.com/maikenp> Can you please test it and confirm that it works?

**Comment by riccardomurri** [comment]
Sorry - I hit the wrong button and a copy of the last message was re-sent...

No hurries!

**Comment by maikenp** [comment]
Ok :)

On 14 Mar 2018, at 21:40, Riccardo Murri <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry - I hit the wrong button and a copy of the last message was re-sent...

No hurries!

**Comment by riccardomurri** [comment]
Merged into "master" anyway -- it won't be worse than what we had before :-)
