### ISSUE TITLE
Azure support not working

### ISSUE THREAD

**Issue by riccardomurri** [gc3-uzh-ch/elasticluster#529]
It looks like Azure support is currently broken both in the `azure` provider and in the `libcloud` one.
For more details and discussion, see: https://groups.google.com/forum/#!topic/elasticluster/yp_YMJPF3u8

**Comment by dsteinkraus** [comment]
Commented in the linked forum. (I didn't know there was a libcloud provider, so I have nothing to contribute on that.)

**Comment by Smahane** [comment]
@riccardomurri  Thanks for announcing this issue here. It was driving me crazy! any promised date of when this bug could get fixed? I'm hoping to be able to create an Azure cluster later this week.

**Comment by riccardomurri** [comment]
> ny promised date of when this bug could get fixed?

@Smahane The basic functionality is now available in PR #530 and works.  I'm polishing it and will be ready to merge by end of this week into "master" (hence, in the Docker image).  You're welcome to test the PR already and tell me if there are any macroscopic bugs or missing functionality ;-)

**Comment by Smahane** [comment]
Great! I will give it a try. What is the Docker image? Any docs?

**Comment by riccardomurri** [comment]
New Azure provider has now been merged into "master"; in a few minutes the Docker image will be rebuilt with it as well.

@Smahane The Docker image is meant to provide a 0-install experience for ElastiCluster (through Docker). Here's the relevant docs: http://elasticluster.readthedocs.io/en/latest/install.html#quickstart
