### ISSUE TITLE
make a release?

### ISSUE THREAD

**Issue by notestaff** [gc3-uzh-ch/elasticluster#532]
Can you make a new tagged release?  I want to make a conda-forge recipe for elasticluster so it can be installed with conda.  This requires a tagged release, and the existing ones are very old.  Thanks!

**Comment by riccardomurri** [comment]
Good point; a release is overdue! 

I was planning to tag 1.3.0 when [milestone 1.3](https://github.com/gc3-uzh-ch/elasticluster/milestone/6) is reached, but that keeps shifting in the future ... :-(

Would a pre-release tag do?  e.g. `1.3.0pre1`

**Comment by notestaff** [comment]
Yes prerelease is fine

**Comment by riccardomurri** [comment]
Just tagged 1.3.0pre1

**Comment by riccardomurri** [comment]
(By the way, when you publish the conda forge recipe, could you please announce it on the elasticluster@googlegroups.com mailing-list?)

**Comment by riccardomurri** [comment]
Sorry to resurrect an old closed thread, but @pescobar is also working on a Conda recipe: https://groups.google.com/forum/#!searchin/elasticluster/pablo$20conda%7Csort:date/elasticluster/antylU_KfaI/ZERLyiooCwAJ

Maybe it's a good idea to join efforts? :-)
