### ISSUE TITLE
Seemingly random report of one or two or compute/frontend "did not report successful termination of playbook". 

### ISSUE THREAD

**Issue by nbarsch** [gc3-uzh-ch/elasticluster#535]
I've been over and over every guide I could find including error troubleshooting here: https://github.com/gc3-uzh-ch/elasticluster/issues/478,  https://github.com/gc3-uzh-ch/elasticluster/issues/47,  and especially https://github.com/gc3-uzh-ch/elasticluster/issues/521 to no avail. Though this is in all likelihood a setting I have in the wrong place. 

I'm trying to follow the instructions here: https://cloud.google.com/solutions/running-r-at-scale

I've run R on a slurm scheduler before, but I've never set up the slurm scheduler nor done it in gcloud so I'm a bit of a noob. 

I'm running a mac. I configured everything as instructed and get the VM's in my google cloud, but get the error 

```
elasticluster -vvv start myslurmcluster

####after a lot of other code that seems to be working
PLAY RECAP ******************************************************************************************************************************************************
compute001                 : ok=159  changed=93   unreachable=0    failed=0   
compute002                 : ok=159  changed=93   unreachable=0    failed=0   
compute003                 : ok=159  changed=93   unreachable=0    failed=0   
frontend001                : ok=163  changed=100  unreachable=0    failed=0   

ERROR The following nodes did not report successful termination of the setup playbook: compute002, frontend001
WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
WARNING Cluster `myslurmcluster` not yet configured. Please, re-run `elasticluster setup myslurmcluster` and/or check your configuration

WARNING: YOUR CLUSTER `myslurmcluster` IS NOT READY YET!

```

In all likelihood this is a newbie error that I have made, but can I get some help troubleshooting? Thanks in advance!

**Comment by riccardomurri** [comment]
Hello Neal,  can you please post the `image_id` you're using?

It looks  like ElasticClustrr is misdetecting the base OS, or simply doing
the wrong thing.

>

**Comment by nbarsch** [comment]
Thanks riccardomurri,

image_id=debian-8-jessie-v20180129

**Comment by riccardomurri** [comment]
Can you also please, right after the cluster setup has failed, run this (and post output here):

    elasticluster ssh mycluster -n compute001 systemctl status netfilter-persistent

**Comment by nbarsch** [comment]
I got through the netfilter issue by updating the v# to 2018 on the image_id and updated my post with a new error. . . sorry if I caused confusion. 

Happy to do that command though, but I get an error:

`error: unrecognized arguments: systemctl status netfilter-persistent`

I am on my mac, so I may not have the command systemct1?

**Comment by nbarsch** [comment]
My new error is that it reports a seemingly random one or two or compute/frontend did not report successful termination of playbook. The cluster seems to be working, despite the warning it is not ready

**Comment by riccardomurri** [comment]
Can you please post the entire output from `elasticluster start` or
`elasticluster setup` where the error occurs?

**Comment by riccardomurri** [comment]
> My new error is that it reports a seemingly random one or two or
> compute/frontend did not report successful termination of playbook.

This might be a concurrency problem with the generation of the final
report: for sufficiently many nodes, some reports will overwrite the
others.  This might have escaped testing because of a too small
cluster size.

Can you please upgrade to the latest "master" code and retry?  Or use
the latest Docker inage, which will be ready in a few minutes.

**Comment by riccardomurri** [comment]
(You need commit 2567fbb or later.)

**Comment by riccardomurri** [comment]
Sorry, it's commit aa97145c -- I erroneously left a critical part of that commit out...

**Comment by riccardomurri** [comment]
Is this solved now?

**Comment by riccardomurri** [comment]
Since no reply, assuming it is -- or that you're no longer interested.

**Comment by orxshi** [comment]
I got the same error:

> 2018-04-30 13:00:39 3acefac83dfd gc3.elasticluster[1] ERROR The following nodes did not report successful termination of the setup playbook: compute003, compute010, compute004
> 2018-04-30 13:00:39 3acefac83dfd gc3.elasticluster[1] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
> 2018-04-30 13:00:39 3acefac83dfd gc3.elasticluster[1] WARNING Cluster `slurm-on-gce` not yet configured. Please, re-run `elasticluster setup slurm-on-gce` and/or check your configuration

The cluster size was supposed to be 10 compute nodes but in the end 3 compute nodes were missing (compute003, 004, and 010).

I scrolled a little back and found out this error:

> 2018-04-30 12:30:13 3acefac83dfd gc3.elasticluster[1] ERROR Error creating instance `<HttpError 403 when requesting https://www.googleapis.com/compute/v1/projects/tailor-193612/zones/us-central1-a/instances?alt=json returned "Quota 'IN_USE_ADDRESSES' exceeded. Limit: 8.0 in region us-central1.">`

**Comment by orxshi** [comment]
Oh my bad. For some reason Google changed my quota and I wasn't expecting this. I assumed this must be related to elasticluster.
