### ISSUE TITLE
Update `ssh` and `sftp` subcommand to allow specifying a node

### ISSUE THREAD

**Issue by arcimboldo** [gc3-uzh-ch/elasticluster#54]
So far, you have to specify a configuration option `ssh_to` to define the group you want to connect to when running `elasticluster ssh`. However, sometimes it may be useful to ssh to a specific host instead.

The proposal is to modify `ssh` and `sftp` commands in order to accept an optional name as argument which is the name of the host. For instance, given the following cluster fonfiguration snippet:

    [cluster/slurm]
    frontend_nodes=1
    compute_nodes=3
    ssh_to=frontend

Running:

    elasticluster ssh 

will connect to the `frontend001` host, but the following command:

    elasticluster ssh compute002

will connect to compute002 node.

The same should apply to `elasticluster sftp`

**Comment by nicolasbaer** [comment]
This is solved in fd6d12c
