### ISSUE TITLE
[nfs-client] Error mounting /home: mount.nfs

### ISSUE THREAD

**Issue by pnik073** [gc3-uzh-ch/elasticluster#540]
I am following up the deployment of SLURM cluster after the fix of #539. I run from the latest `master` and also from latest `docker`. In both cases, I get the following `Error mounting /home: mount.nfs`, see code block. 

> Any ideas on that?

```
TASK [nfs-client : add to /etc/fstab] *********************************************************************************************************
fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /home: mount.nfs: Connection timed out\n"}

PLAY RECAP ************************************************************************************************************************************
compute001                 : ok=62   changed=38   unreachable=0    failed=1   
compute002                 : ok=62   changed=38   unreachable=0    failed=1   
frontend001                : ok=122  changed=89   unreachable=0    failed=0   

2018-03-31 23:56:30 ubuntu-xenial gc3.elasticluster[796] ERROR Command `ansible-playbook --private-key=/home/vagrant/.ssh/elasticluster.pem /home/vagrant/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/home/vagrant/.elasticluster/storage/slurm.inventory --become --become-user=root -e elasticluster_output_dir=/tmp/elasticluster.CJs4o2.d` failed with exit code 2.
```

**Comment by riccardomurri** [comment]
I have tried to give instructions on how to solve this at: http://elasticluster.readthedocs.io/en/latest/troubleshooting.html#setup-of-a-cluster-fails-and-stops-at-task-nfs-client-add-to-etc-fstab

Can you please check them out and let me know if it solves your problem?

**Comment by pnik073** [comment]
Today is time to celebrate `Your cluster slurm is ready!` (This is the message I get from the SLURM provisioning)! I am so thankful for that @riccardomurri!

**Test output for MPI and SLURM:**
```
ubuntu@compute001:~$ mpirun -np 2 -host compute001,compute002 hostname
compute001
compute002
ubuntu@compute001:~$ srun -n 4 hostname
compute001
compute001
compute002
compute002
```

## Elasticluster + SLURM + AWS configuration

### AWS security group (called `elasticluster` in my `slurm.conf` ):

Type | Protocol | Port Range | Source | Description
:-- | :-- | :-- | :-- | :--
All traffic | All | All | 0.0.0.0/0 |  
SSH | TCP | 22 | 0.0.0.0/0

### Config file:
[slurm.conf.txt](https://github.com/gc3-uzh-ch/elasticluster/files/1867856/slurm.conf.txt)
