### ISSUE TITLE
Failed: Ensure the APT package cache is updated

### ISSUE THREAD

**Issue by orxshi** [gc3-uzh-ch/elasticluster#541]
Until now elasticluster was working perfectly. I have changed nothing but today I got the following error for "./elasticluster.sh start slurm-on-gce". I tested three times and got the same output.

TASK [common : Ensure the APT package cache is updated] ************************************************************************************************************************************************************
fatal: [compute005]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute007]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute006]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute003]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute004]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute009]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute001]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute008]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute002]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
fatal: [compute010]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
 [WARNING]: Could not create retry file '/home/elasticluster/share/playbooks/site.retry'.         [Errno 13] Permission denied: u'/home/elasticluster/share/playbooks/site.retry'

**Comment by riccardomurri** [comment]
Can you please do the following:

1. Post the image ID from the config file you're using;

2. Post a dump of the firewall rules;

3. When the luster setup fails, run `elasticluster ssh slurm-on-gce` and
then run `sudo apt-get update` on the front end node. Post the entire
output here.


Il lun 2 apr 2018 13:06 orxshi <notifications@github.com> ha scritto:

**Comment by orxshi** [comment]
1. image_id=https://www.googleapis.com/compute/v1/projects/tailor-193612/global/images/image-20

2. Output of `sudo iptables -S`:

-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
-A DOCKER-USER -j RETURN

3. Output of `sudo apt-get update` on front end:

Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease             
Get:4 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease [6377 B]
Hit:5 http://deb.debian.org/debian stretch-backports InRelease           
Hit:6 http://deb.debian.org/debian stretch Release                       
Get:7 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease [3843 B]
Get:8 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease [3876 B]
Err:4 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
Err:7 http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
Err:8 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt google-compute-engine-stretch-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: Failed to fetch http://packages.cloud.google.com/apt/dists/google-compute-engine-stretch-stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: Failed to fetch http://packages.cloud.google.com/apt/dists/google-cloud-packages-archive-keyring-stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by riccardomurri** [comment]
Given these errors::

    Err:4 http://packages.cloud.google.com/apt cloud-sdk-stretch InRelease
      The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB

It's quite clear that this is not a network error, as I had initially
thought. Rather, you seem to be using an image snapshot that was
probably made some time ago -- since then, the GPG key used to verify
the signature on the package repositories has changed, and now
APT won't even update the package list since the key doesn't match.

This may happen on Debian and Ubuntu: when they are about to change
the key, a new version of the appropriate `*-keyring` package is
issued, containing both the old and the new key.  If you don't update
the keyring package before the new key starts being used, you end up
exactly in this situation.  Except in your case:

1. All the failing repositories seem to be Google Cloud ones, so I do
   not know what "keyring" package should be updated.

2. The public key used for signing packages seems to be unknown to
   major keyservers, so we cannot even install it using `apt-key adv`.

Can you please run this command on the frontend node and post the output?

```
sudo egrep '^deb' /etc/apt/sources.list /etc/apt/sources.list.d/*
```

**Comment by orxshi** [comment]
Output of `sudo egrep '^deb' /etc/apt/sources.list /etc/apt/sources.list.d/*` on frontend gave:

```
/etc/apt/sources.list:deb http://deb.debian.org/debian/ stretch main
/etc/apt/sources.list:deb-src http://deb.debian.org/debian/ stretch main
/etc/apt/sources.list:deb http://security.debian.org/ stretch/updates main
/etc/apt/sources.list:deb-src http://security.debian.org/ stretch/updates main
/etc/apt/sources.list:deb http://deb.debian.org/debian/ stretch-updates main
/etc/apt/sources.list:deb-src http://deb.debian.org/debian/ stretch-updates main
/etc/apt/sources.list.d/backports.list:deb http://deb.debian.org/debian/ stretch-backports main
/etc/apt/sources.list.d/backports.list:deb-src http://deb.debian.org/debian/ stretch-backports main
/etc/apt/sources.list.d/google-cloud.list:deb http://packages.cloud.google.com/apt cloud-sdk-stretch main
/etc/apt/sources.list.d/google-cloud.list:deb http://packages.cloud.google.com/apt google-compute-engine-stretch-stable main
/etc/apt/sources.list.d/google-cloud.list:deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch main
```

**Comment by riccardomurri** [comment]
Ok, so the secure way to fix it would be the following:

1. Start a VM from your "image-20" image;
2. Run the following command (all on one line)::

        sudo wget -O /etc/apt/trusted.gpg.d/google-cloud-packages-archive-keyring-stretch.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

3. Verify that this has fixed the `apt-get update` problem by running (you should get no `Err:` nor `W:` lines)::

        sudo apt-get update

4. Then make a new VM snapshot and use that for building the cluster.


The insecure way is: add the following line to your `[setup/...]` section and rebuild the cluster:

        global_var_insecure_https_downloads=yes

Let me know how it goes.

**Comment by orxshi** [comment]
The secure way worked fine.

**Comment by riccardomurri** [comment]
Good :-) then I'm closing this issue.
