### ISSUE TITLE
PostgreSQL | Add PostgreSQL repository apt-key] 

### ISSUE THREAD

**Issue by pnik073** [gc3-uzh-ch/elasticluster#542]
I was trying to provision a Spark cluster on AWS and I got a `Failed to validate the SSL certificate for www.postgresql.org:443` related to PostgreSQL | Add PostgreSQL repository apt-key]. The error is similar to #539, hence **I managed to fix it** like with the following change:

* Flag not working: `global_var_insecure_https_downloads=yes`
* File related: `/elasticluster/share/playbooks/roles/postgresql/tasks/install.yml`
* Missing flag: validate_certs: '{{ not insecure_https_downloads|default("no")|bool }}'
* Solution tested: `validate_certs: no` works.

> Will you add this config flag on this file too? Thanks!

## Error

```
TASK [postgresql : PostgreSQL | Add PostgreSQL repository apt-key] ***********************************************
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for www.postgresql.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: (\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')],)\",)."}

PLAY RECAP *******************************************************************************************************
compute001                 : ok=45   changed=27   unreachable=0    failed=0   
compute002                 : ok=45   changed=27   unreachable=0    failed=0   
frontend001                : ok=76   changed=50   unreachable=0    failed=1   

2018-04-02 14:44:37 ubuntu-xenial gc3.elasticluster[18123] ERROR Command `ansible-playbook --private-key=/home/vagrant/.ssh/elasticluster.pem /home/vagrant/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/home/vagrant/.elasticluster/storage/spark.inventory --become --become-user=root -e elasticluster_output_dir=/tmp/elasticluster.oC6UBR.d` failed with exit code 2.
```

## Dummy fix

```
$ git diff

--- a/elasticluster/share/playbooks/roles/postgresql/tasks/install.yml
+++ b/elasticluster/share/playbooks/roles/postgresql/tasks/install.yml
@@ -11,6 +11,7 @@
   apt_key:
     id: "{{ postgresql_apt_key_id }}"
     url: "{{ postgresql_apt_key_url }}"
+    validate_certs: no
     state: present
   when: postgresql_apt_key_url and postgresql_apt_key_id

**Comment by riccardomurri** [comment]
Many thanks for providing this patch!  I have merged it in my working code, will be pushed to GitHub with the next set of changes.

(The usual way to suggest changes in the code on GitHub is through [pull requests][1], because that allows reviews and public conversations, but I am not strict on this: if you prefer submitting patches via issues or email, that works for me.  I prefer to have one contribution more than one pull request less ;-)  Thanks again!)

[1]: https://help.github.com/articles/about-pull-requests/
