### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by pnik073** [gc3-uzh-ch/elasticluster#543]
I am trying to provision a Spark cluster on AWS and I get the `No space left on device` during the step `TASK [anaconda : Download Anaconda installer script]`. I have tried `flavor=` with **big storage** and I keep on getting the following error.

## Error
```
TASK [anaconda : Download Anaconda installer script] ********************************************************************************************************
fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create temporary content file: [Errno 28] No space left on device"}

PLAY RECAP **************************************************************************************************************************************************
compute001                 : ok=45   changed=30   unreachable=0    failed=0   
compute002                 : ok=45   changed=30   unreachable=0    failed=0   
frontend001                : ok=99   changed=70   unreachable=0    failed=1   
```

> *Any idea way how to configure the storage or solve that issue?*

**Comment by riccardomurri** [comment]
The default download location for the Anaconda installer script is within the `/tmp` directory; it's possible that the `/tmp` directory on your front-end node is mounted from RAM disk and thus has limited space.
Can you please check by doing the following?

1. Log in to the front-end node with `elasticluster ssh clustername`
2. Run the command::

        df -h /tmp

If it turns out that `/tmp` has limited space, you can try running this in your shell *before* running `elasticluster start` or `elasticluster setup`::

        export TMPDIR=/var/tmp

**Comment by pnik073** [comment]
Indeed, I get this from the master node:

```
ubuntu@frontend001:~$ df -h  /tmp/
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.7G  7.4G  303M  97% /
ubuntu@frontend001:~$ df -h 
Filesystem      Size  Used Avail Use% Mounted on
udev            7.4G     0  7.4G   0% /dev
tmpfs           1.5G  9.3M  1.5G   1% /run
/dev/xvda1      7.7G  7.4G  303M  97% /
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/xvdb        64G   52M   61G   1% /mnt
tmpfs           1.5G     0  1.5G   0% /run/user/122
tmpfs           1.5G     0  1.5G   0% /run/user/125
tmpfs           1.5G     0  1.5G   0% /run/user/123
tmpfs           1.5G     0  1.5G   0% /run/user/124
tmpfs           1.5G     0  1.5G   0% /run/user/1000
ubuntu@frontend001:~$ ls /
bin   core  etc   initrd.img      lib    lib64       media  opt          proc  run   snap  sys  usr  vmlinuz
boot  dev   home  initrd.img.old  lib32  lost+found  mnt    pg_stat_tmp  root  sbin  srv   tmp  var  vmlinuz.old
```

Therefore, the `/var` option will not help too. I will try to check how to get `/` on the `/dev/xvdb`. I will let you know how it goes.

**Comment by pnik073** [comment]
It seems that the default HD size for AWS is **8GB** (see table below). Is there any option in `elasticluster` to provision more space (similar to Vagrant's `aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 20 }]`)?

Volume Type | Device | Snapshot | Size (GiB) | Volume Type | IOPS | Throughput (MB/s) | Delete on Termination | Encrypted |  
:-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- | :--
Root | /dev/sda1 | snap-0f1fc0d2e135251f8 |  8 | General Purpose SSD (GP2) | 100 / 3000 | N/A |   | Not Encrypted

> My library dependencies will take a lot of space. Therefore, it would be preferable to resize the main disk. Unless, I miss something here.

**Comment by pnik073** [comment]
The solution I used a new AMI image (which I manually created) with larger HD size on AWS. Then I add this on my `conf` file and goes on.

**Comment by riccardomurri** [comment]
Good to know you've solved the issue! I'm adding a few notes for the record, in case other people with the same issue land here by web searches:

> I will try to check how to get / on the /dev/xvdb

You can set the download location to an arbitrary directory (provided you can write to it both on the cluster nodes and on the machine where you're running ElastiCluster).  So for instance, this would download the Anaconda installer script into `/mnt` (which has 61GB free in the dump above):

        export TMPDIR=/mnt
        elasticluster setup my-spark-cluster

> Is there any option in elasticluster to provision more space

Yes, there is an option `boot_disk_size`.  It is already available in "master" for [Google Cloud][1] and [OpenStack][2]; the [corresponding code for AWS][3] is currently being tested in PR #536.  (Note that PR code is not available in Docker images; let me know if you want to test it with Docker.)

[1]: http://elasticluster.readthedocs.io/en/latest/configure.html#additional-optional-configuration-keys-for-google-cloud
[2]: http://elasticluster.readthedocs.io/en/latest/configure.html#additional-optional-configuration-keys-for-openstack-clouds
[3]: https://github.com/gc3-uzh-ch/elasticluster/pull/536
