### ISSUE TITLE
ansible : Add Ansible APT repository (Ubuntu)

### ISSUE THREAD

**Issue by pnik073** [gc3-uzh-ch/elasticluster#544]
When I run the provisioning of a Spark cluster on AWS (with Ubuntu Xenial AMI) I get the following error `ansible : Add Ansible APT repository (Ubuntu)` *"value of state must be one of: present,absent, got: latest"*. 

```
TASK [ansible : Add Ansible APT repository (Ubuntu)] ****************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
('{{ansible_distribution}}' == 'Ubuntu')

fatal: [frontend001]: FAILED! => {"changed": false, "failed": true, "msg": "value of state must be one of: present,absent, got: latest"}

PLAY RECAP **********************************************************************************************************************
compute001                 : ok=117  changed=17   unreachable=0    failed=0   
compute002                 : ok=117  changed=17   unreachable=0    failed=0   
frontend001                : ok=143  changed=19   unreachable=0    failed=1   

2018-04-04 01:13:27 ubuntu-xenial gc3.elasticluster[18209] ERROR Command `ansible-playbook --private-key=/home/vagrant/.ssh/elasticluster.pem /home/vagrant/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/home/vagrant/.elasticluster/storage/spark.inventory --become --become-user=root -e elasticluster_output_dir=/tmp/elasticluster.SCDyQT.d` failed with exit code 2.
```

I have further looked at the `.../ansible/tasks/main.yml` if I could change something, but I did not get any luck with it. I also tried to use in the config file `global_var_pkg_install_state=present`, also no luck with that. If I remove the state or edit the repo, I get some longer error.

> I have also used as reference the [Ansible page](http://docs.ansible.com/ansible/latest/modules/apt_repository_module.html) and [Canonical page](https://launchpad.net/~ansible/+archive/ubuntu/ansible), to get some ideas.

```
# Ansible does not provide a repo for Debian, so we do not add one and users on
# Debian "stable" will get whatever version of Ansible was released with the OS.
# Suggestions or PRs to improve this are welcome.
- name: Add Ansible APT repository (Ubuntu)
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: '{{ pkg_install_state }}'
  when: is_ubuntu
```

> **Any ideas on that?**

**Comment by riccardomurri** [comment]
Should be fixed in the latest "master" code: update and you should be good to go.

Sorry, the wrong `state:` line slipped in during a global search/replace for another business.

**Comment by pnik073** [comment]
`Your cluster spark is ready!`

**Comment by riccardomurri** [comment]
Yay! :-)
