### ISSUE TITLE
Local Ubuntu Cluster Config Example

### ISSUE THREAD

**Issue by s8i** [gc3-uzh-ch/elasticluster#547]
I am new to elasticluster and I apologise if I missed this:

**I need to configure for a Local Ubuntu 16.04 machine Slurm cluster.**
Master machine has elasticluster installed and docker container is up (`elasticluster version 1.3.dev2`)
`./elasticluster list` reports config successfully.

I have 20 machines in a Munge realm by sharing the same: `/etc/munge/munge.key`
```bash
eighti@linuxpegasus:/etc/munge$ munge -n | ssh linuxcapture01 unmunge
eighti@linuxcapture01's password:
STATUS:           Success (0)
ENCODE_HOST:      linuxcapture01 (127.0.1.1)
ENCODE_TIME:      2018-04-09 16:58:22 +1200 (1523249902)
DECODE_TIME:      2018-04-09 16:58:26 +1200 (1523249906)
TTL:              300
CIPHER:           aes128 (4)
MAC:              sha1 (3)
ZIP:              none (0)
UID:              eighti (1000)
GID:              eighti (1000)
LENGTH:           0
```
NTP source is synced (same output on all machines):
```bash
eighti@linuxpegasus:/etc/munge$ timedatectl
      Local time: Mon 2018-04-09 17:02:47 NZST
  Universal time: Mon 2018-04-09 05:02:47 UTC
        RTC time: Mon 2018-04-09 05:02:47
       Time zone: Pacific/Auckland (NZST, +1200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```
User is the same on all machines
That same user is `sudo` on all machines:
```bash
eighti@linuxpegasus:/etc/munge$ grep -Po '^sudo.+:\K.*$' /etc/group
eighti,stage
```
Master machine has ssh pub_keys entered to `~/.ssh/know_hosts` from all other machines
Ansible is used everyday successfully on these machines

I have a feeling I'm very close to being able to deploy a cluster once I understand how to edit or replace the `.elasticluster/config` file

**If there is a better place to make these requests, I am very happy to go there and this "issue" may be disregarded**

**Comment by riccardomurri** [comment]
I've replied to the message you've sent to the mailing list: https://groups.google.com/forum/#!topic/elasticluster/J5dm7WZH0bU

**Comment by riccardomurri** [comment]
Closing issue, as discussion continues on the mailing list.
