### ISSUE TITLE
Project name in image-id is replaced with image-cloud

### ISSUE THREAD

**Issue by orxshi** [gc3-uzh-ch/elasticluster#549]
I set my project as `tailor-193612` in both `gce_project_id` and `image_id`. But for some reason `elasticluster 1.3.dev3` gives error in which project name in `image-id` is replaced with `image-cloud`.

**Error message:**

> Could not start node `compute003`: Error creating instance `<HttpError 400 when requesting https://www.googleapis.com/compute/v1/projects/tailor-193612/zones/us-central1-a/instances?alt=json returned "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/image-cloud/global/images/image-23'. The project 'image-cloud' was not found.">` -- <class 'elasticluster.exceptions.InstanceError'>

**Configuration file:**
```
[cloud/google]
noauth_local_webserver=yes
provider=google
gce_client_id=<>
gce_client_secret=<>
gce_project_id=tailor-193612

[login/google]
image_user=orxan.shibli
image_sudo=yes
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

[setup/slurm]
frontend_groups=slurm_master
compute_groups=slurm_worker
submit_groups=slurm_submit,glusterfs_client
global_var_multiuser_cluster=yes

[cluster/slurm-on-gce]
setup=slurm
frontend_nodes=1
compute_nodes=3
ssh_to=frontend
cloud=google
login=google
flavor=n1-standard-1
security_group=default
image_id=https://www.googleapis.com/compute/v1/projects/tailor-193612/global/images/image-23
```

**Comment by riccardomurri** [comment]
I see the problem: in [gce.py line 296 (also see the preceding block of comments)](https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/providers/gce.py#L295), the assumption is made that, if an image ID is *not* a "self-link URL" then it is a shortcut to a well-known project, and the project name is extracted as the part before the the first `-`.  So `image-23` is interpreted as an image in public project `image-cloud`.

Workaround: use self-link URLs as the image ID.  (If it doesn't work, destroy the cluster, remove `$HOME/.elasticluster/storage/mycluster*` and retry.)

I will check if this shortcut feature can be made more robust.

**Comment by orxshi** [comment]
What is self-link URL? I got the address of image from the list:

`gcloud compute images list --uri`

**Comment by riccardomurri** [comment]
Can you please try again with the latest master?  You should now get a real error from ElastiCluster if the `image_id` is invalid.

As to "self-link URL": it's the `https://...` URL that `gcloud compute images list --uri` displays.  I see that you have it in the config you posted already, but the only way you could have gotten the error message you reported is if you had `image_id=image-23` in a previous version of the config file and tried to start a cluster with that; also note that the `image_id` is only read when the cluster is first created -- if starting a cluster fails, and you change the config, the cluster will still use the old value.  You need to stop/destroy the cluster and then re-create it with the new config.

**Comment by riccardomurri** [comment]
> However, after stopping and re-starting it worked fine.

Good :-)
