### ISSUE TITLE
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified

### ISSUE THREAD

**Issue by orxshi** [gc3-uzh-ch/elasticluster#553]
I get an error message:

> sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified

Output of `sudo sacctmgr show users`:

```
      User   Def Acct     Admin 
---------- ---------- --------- 
orxan.shibli       root      None 
      root         root Administ+
```

**Comment by riccardomurri** [comment]
Can you please try again?  This should be fixed in the latest "master" code (and the Docker image as soon as it finishes building).

**Comment by orxshi** [comment]
After `./elasticluster --pull` problem solved.

**Comment by riccardomurri** [comment]
Great!  Thanks for testing!
