### ISSUE TITLE
SSH ProxyCommand not passed to Ansible

### ISSUE THREAD

**Issue by mkjpryor-stfc** [gc3-uzh-ch/elasticluster#567]
When `ssh_proxy_command` is given in a `[cluster/...]` section in order to facilitate access via a bastion host, it is not propagated into the Ansible configuration, resulting in a failure to access machines.

The workaround is to specify `ansible_ssh_args=-o ProxyCommand='...'` in the `[setup/...]` section, but this should really be done automatically, especially as the `setup` sections are meant to be generic, and the `ProxyCommand` encodes a particular bastion host, which might change per-cluster.

**Comment by riccardomurri** [comment]
This should by fixed by https://github.com/gc3-uzh-ch/elasticluster/pull/570 -- do you have any time to test it and confirm that it works?
