### ISSUE TITLE
elasticluster: slurm + gce issues

### ISSUE THREAD

**Issue by jrieffel** [gc3-uzh-ch/elasticluster#579]
Thanks developers for creating such an astonishingly effective and easy to use tool!  The ability to deploy a slurm cluster from the command line is amazing!  Some questions however:

a) I created a slurm cluster on GCE using a variation of the steps [here](https://googlegenomics.readthedocs.io/en/latest/use_cases/setup_gridengine_cluster_on_compute_engine/).  This is for teaching a parallel computing class of ~24 students.   I can ssh into the front end without difficulty, and get an interactive shell via srun.  However, my students get an error to the effect of `srun: error: Unable to allocate resources: Invalid account or account/partition combination specified`.  Is there a way to, by default, give new users access to the cluster, or do I have to manually sacctmgr add each user to the cluster?

b) I used 'elasticluster resize' to add additional compute nodes to the cluster.  The instances appear on GCE, but not on sinfo.  Is there additional work I need to do on the frontend instance to make it aware of the new compute nodes, or should this have been taken care of automatically?

**Comment by jrieffel** [comment]
I solved (b) with a slurmctld restart.  question (a) remains

**Comment by riccardomurri** [comment]
> Is there a way to, by default, give new users access to the cluster, or do I have to manually sacctmgr add each user to the cluster?

At the moment, you need to run `sacctmgr create user` for each additional user:

    sacctmgr -i add user "username" account=root

On Debian/Ubuntu, this can be easily automated by adding this `sacctmgr` invocation to the `/usr/local/sbin/adduser.local` script.

Does this solve your problem?
