### ISSUE TITLE
Missing nfs-server.yml file error

### ISSUE THREAD

**Issue by Lanilen** [gc3-uzh-ch/elasticluster#581]
Hello,

I'm trying to deploy elasticluster on the Catalyst Cloud using the latest repo, and when I execute "elasticluster start slurm -n cluster" I get the following error:

Starting cluster `cluster` with:
 * 1 frontend nodes.
 * 2 compute nodes.
 (This may take a while...)
 Configuring the cluster ...
 (this too may take a while)
 ERROR! Unable to retrieve file contents Could not find or access '/home/ubuntu/src/elasticluster/share/playbooks/roles/nfs-server.yml' on the Ansible Controller. If you are using a module and expect the file to exist on the remote, see the remote_src option 2018-09-19 10:04:55 orchestral gc3.elasticluster[12641]
 ERROR Command `ansible-playbook --private-key=/home/ubuntu/elasticluster/id_rsa /home/ubuntu/src/elasticluster/share/playbooks/main.yml --inventory=/home/ubuntu/.elasticluster/storage/cluster.inventory --become --become-user=root -e @/tmp/extra_vars.yml` failed with exit code 1. 2018-09-19 10:04:55 orchestral gc3.elasticluster[12641]
 WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`. 2018-09-19 10:04:55 orchestral gc3.elasticluster[12641]
 WARNING Cluster `cluster` not yet configured. Please, re-run `elasticluster setup cluster` and/or check your configuration 

Seems like it's looking for "share/playbooks/roles/nfs-server.yml" as referenced in "share/playbooks/main.yml", but the file isn't there.

Cheers,
Roger.-

**Comment by riccardomurri** [comment]
Thanks for noticing!  The file was in my working directory, but I had forgotten to `git add` it...

Should be fixed in commit 3f4b978c (latest "master") -- can you pls update and check?

**Comment by Lanilen** [comment]
Worked like a charm, thanks!

**Comment by riccardomurri** [comment]
Great!  Many thanks for testing!
