### ISSUE TITLE
myslurmcluster start error

### ISSUE THREAD

**Issue by Morpheuscc** [gc3-uzh-ch/elasticluster#585]
I'm trying to create a slurmcluster following [https://cloud.google.com/solutions/running-r-at-scale](Running R at Scale) I've gotten everything configured, but when I start the cluster, I get the following:

(elasticluster) chris@chris-virtual-machine:~/elasticluster$ elasticluster start myslurmcluster
Starting cluster `myslurmcluster` with:
* 5 compute nodes.
* 1 frontend nodes.
(This may take a while...)
Configuring the cluster ...
(this too may take a while)
ERROR! Invalid options for include_tasks: hosts

The error appears to have been in '/home/chris/elasticluster/src/elasticluster/share/playbooks/roles/common/tasks/main.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_tasks: 'init-{{ansible_os_family}}.yml'
- include_tasks: hosts.yml hosts={{groups.all}}
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2018-10-11 18:55:24 chris-virtual-machine gc3.elasticluster[48557] ERROR Command `ansible-playbook --private-key=/home/chris/.ssh/google_compute_engine /home/chris/elasticluster/src/elasticluster/share/playbooks/main.yml --inventory=/home/chris/.elasticluster/storage/myslurmcluster.inventory --become --become-user=root -e @/tmp/extra_vars.yml` failed with exit code 4.
2018-10-11 18:55:24 chris-virtual-machine gc3.elasticluster[48557] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2018-10-11 18:55:24 chris-virtual-machine gc3.elasticluster[48557] WARNING Cluster `myslurmcluster` not yet configured. Please, re-run `elasticluster setup myslurmcluster` and/or check your configuration

WARNING: YOUR CLUSTER `myslurmcluster` IS NOT READY YET!

Cluster name:     myslurmcluster
Cluster template: myslurmcluster
Default ssh to node: frontend001
- compute nodes: 5
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh myslurmcluster

To upload or download files to the cluster, use the command:

    elasticluster sftp myslurmcluster

I have not touched that particular configuration file, so I'm not sure what is wrong. When I log in to the frontend server, R is not started and not even installed. Not sure if the two issues are related.

**Comment by riccardomurri** [comment]
How are you running ElastiCluster? Docker image or locally-installed Python package?

**Comment by Morpheuscc** [comment]
Locally installed Python package

**Comment by riccardomurri** [comment]
> When I log in to the frontend server, R is not started and not even installed.

Yes, this is the meaning of the message:
```
WARNING: YOUR CLUSTER myslurmcluster IS NOT READY YET!
```

**Comment by Morpheuscc** [comment]
Thanks for looking into this. No matter how long I wait, it remains NOT READY YET. Is this related to the configuration issue?

**Comment by riccardomurri** [comment]
What version of Ansible are you running?

```
ansible-playbook --version
```

**Comment by riccardomurri** [comment]
> No matter how long I wait, it remains NOT READY YET. Is this related to the configuration issue?

Yes, basically the error happened very early on so your cluster was not configured at all.

**Comment by Morpheuscc** [comment]
I'm running ansible 2.5.1. I had to update, but I'm trying it now with the updated version. I'll also update Python.

**Comment by riccardomurri** [comment]
> I'll also update Python.

Not sure what you mean here: ElastiCluster runs with Python 2.7 and won't run with Python 3.x

**Comment by riccardomurri** [comment]
I'd suggest running the Dockerized version -- it's trivial to update and install.  https://elasticluster.readthedocs.io/en/latest/install.html#quickstart

**Comment by Morpheuscc** [comment]
I misunderstood when you said to update the Python code. I realize now that you meant the elasticluster python code? Updated ansible did not help. I will try the Dockerized version. Thanks

**Comment by Morpheuscc** [comment]
I'm a bit confused using the docker version. I have it installed from the .sh file, and I've tried running 

`docker run -it riccardomurri/elasticluster`

which shows a list of commands and then the container immediately dies even though I have passed in the argument -i. Am I missing something there?

**Comment by riccardomurri** [comment]
> Am I missing something there?

Yes, you should not directly run `docker`.  Use the `elasticluster.sh` script you downloaded *instead* of the Python-based `elasticluster`.  I.e., run `/path/to/dowload/location/elasticluster.sh start mycluster` etc. -- this will call Docker with the right parameters.

**Comment by Morpheuscc** [comment]
My config file for reference

[cloud/google]
provider=google

# Set the credentials and GCP project ID.
# NOTE! Substitute your own client ID, client secret, and project ID
# for the placeholders.
gce_client_id=xxxxx
gce_client_secret=xxxxx
gce_project_id=xxxxx

# Set the GCP zone. You can use any zone.
noauth_local_webserver=True
zone=europe-west1-b

# Set credentials for using SSH to log in to the cluster.
# NOTE! Substitute your own GCP user name.
# NOTE! Make sure that the gcloud user keys are in the specified
# location on your host computer.
[login/google]
image_user=xxxxx
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Configure Ansible SSH timeouts and the number of forked processes.
[setup/ansible]
ansible_forks=20
ansible_timeout=200

# Configure Slurm with 2 groups of hosts: 1 frontend (slurm_master) and
# the rest with the role "slurm_worker".
[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master,r
compute_groups=slurm_worker,r

# Define the cluster.
[cluster/myslurmcluster]
cloud=google
login=google
setup=ansible-slurm
security_group=default

# Specify the image, machine type, node count, and boot disk size for
# the cluster nodes.
image_id=debian-9-stretch-v20181009
flavor=n1-highcpu-4
frontend_nodes=1
compute_nodes=5
ssh_to=frontend
boot_disk_size=20
scheduling=preemptible
min_cpu_platform=Intel Haswell

# Configure the head node to have a 1 TB root volume using a
# solid-state drive (SSD).
[cluster/myslurmcluster/frontend]
boot_disk_type=pd-ssd
boot_disk_size=100

**Comment by riccardomurri** [comment]
I think this is now fixed. Can you please try?

* Update the Docker image:

        elasticluster.sh --pull --latest

* Configure cluster:

        elasticluster.sh setup myslurmcluster

**Comment by riccardomurri** [comment]
(You may have to wait approx 15 minutes for the new Docker image to be available.)

**Comment by Morpheuscc** [comment]
Thank you so much for looking into this. My apologies, I'm unfortunately incredibly new at Linux. When I pulled the latest Docker image from riccardomurri/elasticluster, it pulls the same image as the one I already had. How can I pull the latest .sh file?

**Comment by riccardomurri** [comment]
> How can I pull the latest .sh file?

It takes a while for the Docker image to build. Watch this page: https://hub.docker.com/r/riccardomurri/elasticluster/tags/ when the image tagged `87ee7968` is there, you can pull.

**Comment by Morpheuscc** [comment]
Thanks, sorry I missed your initial message. That previous bug is fixed and now I'm looking the following. I'm guessing this is a different issue.

chris@chris-virtual-machine:~/Downloads$ ./elasticluster.sh start myslurmcluster
Starting cluster `myslurmcluster` with:
* 5 compute nodes.
* 1 frontend nodes.
(This may take a while...)
Configuring the cluster ...
(this too may take a while)
ERROR! Invalid options for include_tasks: fs

The error appears to have been in '/home/elasticluster/share/playbooks/roles/nfs-client/tasks/main.yml': line 57, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Mount NFS filesystems
  ^ here

2018-10-11 18:50:50 0f623fec9e15 gc3.elasticluster[1] ERROR Command `ansible-playbook --private-key=/home/chris/.ssh/google_compute_engine /home/elasticluster/share/playbooks/main.yml --inventory=/home/chris/.elasticluster/storage/myslurmcluster.inventory --become --become-user=root -e @/tmp/extra_vars.yml` failed with exit code 4.
2018-10-11 18:50:50 0f623fec9e15 gc3.elasticluster[1] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2018-10-11 18:50:50 0f623fec9e15 gc3.elasticluster[1] WARNING Cluster `myslurmcluster` not yet configured. Please, re-run `elasticluster setup myslurmcluster` and/or check your configuration

WARNING: YOUR CLUSTER `myslurmcluster` IS NOT READY YET!

Cluster name:     myslurmcluster
Cluster template: myslurmcluster
Default ssh to node: frontend001
- compute nodes: 5
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh myslurmcluster

To upload or download files to the cluster, use the command:

    elasticluster sftp myslurmcluster

**Comment by riccardomurri** [comment]
Ok, I pushed (hopefully) a fix; you'll have to wait for Docker image tagged c3acb9f2 before updating and trying this out.

**Comment by Morpheuscc** [comment]
Awesome - looks like the cluster is loading now. Thank you so much! One more question - through the dockerized version, how can I edit the playbook file for say R that designates which packages to install to all?

**Comment by riccardomurri** [comment]
> One more question - through the dockerized version, how can I edit the playbook file for say R that designates which packages to install to all?

Can you pls open another issue with this question? :-)

**Comment by riccardomurri** [comment]
> looks like the cluster is loading now.

All is well that ends well :-)

Thank you very much for reporting and testing the fixes -- I'm surprised such a fundamental issue went unreported for such a long time! (I've probably switched to using `include_tasks:` a couple months ago...)
