### ISSUE TITLE
Editing the playbook file (e.g. R) designating packages for slaves

### ISSUE THREAD

**Issue by Morpheuscc** [gc3-uzh-ch/elasticluster#586]
Thank you to the developers. I was wondering how can I configure the the playbook file when using the dockerized version of elasticluster?

**Comment by riccardomurri** [comment]
You do not need to edit the playbook file: just add this to your config file's `[cluster/...]` section:
```
 global_var_r_libraries=["devtools", "doSNOW"]
```

**Comment by Morpheuscc** [comment]
What's the difference between global_var_r_libraries and using compute_r_libraries?

**Comment by riccardomurri** [comment]
Yes, `global_var_...` applies to all nodes, `compute_var_...` applies to nodes named `compute` only.

By the way, did it work?
