### ISSUE TITLE
if 1 cluster .yml file is not valid (e.g. empty), elasticluster stops reading the others as well.

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#588]
how to reproduce:
in elasticluster storage have an empty <cluster>.yml file
Note: this can be produced if, for exaple, the setup process was interrupted before elasticluster was able to fill the content.
then run:
$ elasticluster list
gc3.elasticluster[7408] ERROR Error: type object argument after ** must be a mapping, not NoneType

What should be the expected behavior ?
elasticluster should report the failure of the import of the specific cluster but continue in the process with the others.

S.

**Comment by riccardomurri** [comment]
Fixed in #589, thanks @smaffiol !
