### ISSUE TITLE
`cluster/gridengine-on-gce`: Key 'nodes' error: missing keys login

### ISSUE THREAD

**Issue by Arsalan9002** [gc3-uzh-ch/elasticluster#591]
I am getting this error when trying to start my elasticluster 

http://take.ms/xa6NYV

please help me figure out the solution.

**Comment by riccardomurri** [comment]
The line just before the one you hightlighted states:

    Error: No cluster template named `myslurmcluster`

So you're trying to start a cluster which ElastiCluster does not know anything about.
What does you configuration file contain? (Do not post sensitive info like passwords or secret keys).

**Comment by Arsalan9002** [comment]
`[cloud/google]
provider=google

# Set the credentials and GCP project ID.
# NOTE! Substitute your own client ID, client secret, and project ID
# for the placeholders.
gce_client_id=824921617778-r8o4f8rmm3raceaidbv8s5v6653pl0p0.apps.googleusercontent.com
gce_client_secret=7crsoNdnGDlMf5_tjtewmFL5
gce_project_id=customer-revenue-prediction

# Set the GCP zone. You can use any zone.
noauth_local_webserver=True
zone=us-east1-b

# Set credentials for using SSH to log in to the cluster.
# NOTE! Substitute your own GCP user name.
# NOTE! Make sure that the gcloud user keys are in the specified
# location on your host computer.
[login/google]
image_user=arslanmehmood50
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Configure Ansible SSH timeouts and the number of forked processes.
[setup/ansible]
ansible_forks=20
ansible_timeout=200

# Configure Slurm with 2 groups of hosts: 1 frontend (slurm_master) and
# the rest with the role "slurm_worker".
[setup/ansible-slurm]
provider=ansible
frontend_groups=slurm_master,r
compute_groups=slurm_worker,r

# Define the cluster.
[cluster/myslurmcluster]
cloud=google
login=google
setup=ansible-slurm
security_group=default

# Specify the image, machine type, node count, and boot disk size for
# the cluster nodes.
image_id=debian-9-stretch-v20180716
flavor=n1-standard-4
frontend_nodes=1
compute_nodes=5
ssh_to=frontend
boot_disk_size=50

# Configure the head node to have a 1 TB root volume using a
# solid-state drive (SSD).
[cluster/myslurmcluster/frontend]
boot_disk_type=pd-ssd
boot_disk_size=1000`


this is my configuration file. 
Thanks for such  a quick response :)

**Comment by Arsalan9002** [comment]
can you please help me out with this issue.

**Comment by riccardomurri** [comment]
The configuration file looks correct.  Did you write it into `$HOME/.elasticluster/config` ?

**Comment by Arsalan9002** [comment]
I have placed it as follows in the virtual env root directory (elasticluster)

http://take.ms/JQ4x1

**Comment by riccardomurri** [comment]
You need to place your configuration file in `$HOME/.elasticluster/config` or it will not be picked up by default.

If you prefer to keep the config file in the root of the virtual env, you will need to use the `-c` option like this:

    elasticluster -c $VIRTUAL_ENV/config commands...

For example:

    elasticluster -c $VIRTUAL_ENV/config start mycluster

In other words, wherever you see `elasticluster` in the instructions you're reading, replace it with `elasticluster -c $VIRTUAL_ENV/config`

**Comment by riccardomurri** [comment]
Hello @Arsalan9002 did the suggestion work?  Is the issue solved?

**Comment by riccardomurri** [comment]
Lacking updates, I'm closing this issue.  Please feel free to open a new one if there are further problems to solve.
