### ISSUE TITLE
could not start nodes: 'NoneType' object has no attribute 'get_all_key_pairs'

### ISSUE THREAD

**Issue by adriaq** [gc3-uzh-ch/elasticluster#592]
Hi! I've been trying to start a simple SLURM cluster on AWS but I don't know what I am doing worong. This is the sanitized config:
```

[setup/slurm]
provider=ansible
master_groups=slurm_master,ganglia_master,glusterfs_client
compute_groups=slurm_worker,ganglia_monitor,glusterfs_server
submit_groups=slurm_submit,glusterfs_client
global_var_ansible_python_interpreter=/usr/bin/python2.7
global_var_multiuser_cluster=yes

[cloud/amazon]
provider=ec2_boto
ec2_url=https://ec2.eu-west-3.amazonaws.com
ec2_access_key= "key"
ec2_secret_key= "secret-key"
ec2_region=us-west-3

[login/ubuntu]
image_user=ubuntu
image_sudo=True
image_user_sudo=root
user_key_name=elasticluster
user_key_private=~/.ssh/elasticluster.pem
user_key_public=~/.ssh/elasticluster.pub

[cluster/slurm-aws]
setup=slurm
security_group=default
image_id=ami-08182c55a1c188dee
cloud=amazon
login=ubuntu
flavor=t2.micro
master_nodes=1
compute_nodes=4
```

launching with       elasticluster -vvvv start slurm-aws gives:
`AttributeError: 'NoneType' object has no attribute 'get_all_key_pairs'`
 The complete log is attached
[elasticluster.log](https://github.com/gc3-uzh-ch/elasticluster/files/2623950/elasticluster.log)

I've tried generating the keys, using keys that are in AWS, giving full administrador permission to the account, setting the security group to one that permits all types of traffic from everywhere.... The AMI is the standard Ubuntu Server 18.04

Thanks!

**Comment by riccardomurri** [comment]
Looks like a bug in ElastiCluster's AWS code.

Unfortunately I won't have time to look into it for a few days... :-(

**Comment by adriaq** [comment]
No prob! thx

**Comment by adriaq** [comment]
Any news? :D

**Comment by riccardomurri** [comment]
I get this error message when trying to start a cluster using the configuration you provided:

```
The image id '[ami-08182c55a1c188dee]' does not exist
```

(Sorry for taking so long to addess this issue, it's been a very busy time.)

**Comment by riccardomurri** [comment]
Hmmm... I get the same error even with AMIs from the official Ubuntu list.

**Comment by riccardomurri** [comment]
It looks like Boto returns `None` but throws no error when connecting to EC2 region `eu-west-3`. I'll have to investigate why.

**Comment by riccardomurri** [comment]
It looks like Boto is still lacking support for `eu-west-3` in 2.49.0 (latest release as I'm writing this): https://github.com/boto/boto/issues/3783

**Comment by riccardomurri** [comment]
As suggested at the end of the linked discussion of the Boto issue, setting the following environmental variable seems to work around the problem:

```sh
export BOTO_USE_ENDPOINT_HEURISTICS=True
```

**Comment by riccardomurri** [comment]
This should have been worked around in commit 58e67de -- a proper fix can only come when Boto starts supporting the Paris region.

**Comment by adriaq** [comment]
Many thanks for the detailed answer!! The cluster starts correctly now. Unfortunately I need to use Paris region but with this workaround It works
