### ISSUE TITLE
config parse lowercase keys

### ISSUE THREAD

**Issue by smaffiol** [gc3-uzh-ch/elasticluster#602]
Using `SafeConfigParser` as a parser for the configuration file leads to all keys being lowercased.
In case of: 
`master_var_NFS_EXPORT = ....`
the parser transform it into:
`master_var_nfs_export`
and thus ignored by the playbook that is, for example:
` loop: '{{NFS_EXPORT}}'`

**Comment by riccardomurri** [comment]
Fixed in commit https://github.com/gc3-uzh-ch/elasticluster/pull/604/commits/45aad5228cc4f654fad611d7966c1053e7293afa
