### ISSUE TITLE
OpenStack variables not being parsed?

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#606]
I've been trying to use an OpenStack v3 openrc file to set the environment variables, thereby not needing to supply most of them in the `elasticluster` configuration.

However, I saw this error which implied that the variables were not being read?:
```
2019-02-14 15:35:42 6a2a22af73c5 gc3.elasticluster[1] ERROR In section `cloud/openstack`: Missing keys: <type 'str'>
2019-02-14 15:35:42 6a2a22af73c5 gc3.elasticluster[1] ERROR Dropping configuration section `cloud/openstack` because of the above errors
```

**Comment by riccardomurri** [comment]
Is this with the current "master" code?  Docker image or running from Python sources?

**Comment by verdurin** [comment]
Yes, current master, with Docker.

**Comment by verdurin** [comment]
While troubleshooting I found that certain combinations of special characters in the password caused a problem too...

**Comment by riccardomurri** [comment]
> While troubleshooting I found that certain combinations of special characters in the password caused a problem too...

That should be an issue with the Docker image only; I need to play tricks in the shell script to pass environment variables down to the `elasticluster` process running in the container, and  `printenv | source` will be sensitive to shell metacharacters...

**Comment by riccardomurri** [comment]
Does your config file look like this?

```
[cloud/openstack]
provider=openstack
# no other lines in this section
```

**Comment by verdurin** [comment]
Yes, that's what I tried.

**Comment by riccardomurri** [comment]
Fixed now in "master", should be available in the Docker image within 15 minutes approx.
