### ISSUE TITLE
netfilter-persistent.service fails when launching SGE on google

### ISSUE THREAD

**Issue by mducar** [gc3-uzh-ch/elasticluster#609]
I'm trying to get SGE running on the Google cloud, but I'm running into issues.

I spun up a small VM on gcc to run the installation on.  I cloned the latest version of the repo from git and followed the installation instructions.

I get the following error message when trying to start/setup the cluster:
```
TASK [iptables : Ensure netfilter rules are loaded at boot] *****************************************************************************************************************************************************************************************************
failed: [compute003] (item=iptables) => {"changed": false, "item": "iptables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status netf
ilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [compute002] (item=iptables) => {"changed": false, "item": "iptables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status netf
ilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [compute001] (item=iptables) => {"changed": false, "item": "iptables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status netf
ilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [frontend001] (item=iptables) => {"changed": false, "item": "iptables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status net
filter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [compute003] (item=ip6tables) => {"changed": false, "item": "ip6tables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status ne
tfilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [compute002] (item=ip6tables) => {"changed": false, "item": "ip6tables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status ne
tfilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [compute001] (item=ip6tables) => {"changed": false, "item": "ip6tables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status ne
tfilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
failed: [frontend001] (item=ip6tables) => {"changed": false, "item": "ip6tables", "msg": "Unable to start service netfilter-persistent: Job for netfilter-persistent.service failed because the control process exited with error code.\nSee \"systemctl status n
etfilter-persistent.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/home/matt_ducar/elasticluster/src/elasticluster/share/playbooks/site.retry
PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************
compute001                 : ok=24   changed=3    unreachable=0    failed=1
compute002                 : ok=24   changed=3    unreachable=0    failed=1
compute003                 : ok=24   changed=3    unreachable=0    failed=1
frontend001                : ok=24   changed=3    unreachable=0    failed=1
2019-02-28 20:03:02 elasticluster-1 gc3.elasticluster[3484] ERROR Command `ansible-playbook /home/matt_ducar/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/home/matt_ducar/.elasticluster/storage/gridengine-on-gce.inventory --become --
become-user=root` failed with exit code 2.
2019-02-28 20:03:02 elasticluster-1 gc3.elasticluster[3484] ERROR Check the output lines above for additional information on this error.
2019-02-28 20:03:02 elasticluster-1 gc3.elasticluster[3484] ERROR The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup` or fix the playbooks.
2019-02-28 20:03:02 elasticluster-1 gc3.elasticluster[3484] WARNING Cluster `gridengine-on-gce` not yet configured. Please, re-run `elasticluster setup gridengine-on-gce` and/or check your configuration
WARNING: YOUR CLUSTER IS NOT READY YET!
Cluster name:     gridengine-on-gce
Cluster template: gridengine-on-gce
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 3
To login on the frontend node, run the command:
    elasticluster ssh gridengine-on-gce
To upload or download files to the cluster, use the command:
    elasticluster sftp gridengine-on-gce
```

Here is my configuration file:
```
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

[cloud/google-cloud]
provider=google
noauth_local_webserver=True
gce_project_id=XXXXXX
gce_client_id=XXXXXX
gce_client_secret=XXXXXX

[login/google-login]
image_user=matt_ducar
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

[cluster/gridengine-on-gce]
boot_disk_type=pd-ssd
boot_disk_size=100
cloud=google-cloud
login=google-login
setup=ansible-gridengine
security_group=default
image_id=debian-9-stretch-v20190213
flavor=n1-standard-1
frontend_nodes=1
compute_nodes=3
ssh_to=frontend
```
Any ideas what I'm doing wrong?

**Comment by riccardomurri** [comment]
I tried to launch an SGE cluster using the config you sent.

Debian's `netfilter-persistent` scripts swallow any errors, but if I
modify the script to be more verbose, I get this error output:

    $ sudo systemctl status netfilter-persistent.service
    [...]
    Mar 01 08:31:27 frontend001 netfilter-persistent[8170]: ip6tables-restore: line 47 failed

Line 47 of `/etc/iptables/rules.v6` contains just the command `COMMIT`. so the real error is likely before that.
Looking at the system logs right after the failed `ip6tables-restore` seems to point to an issue with kernel modules:

    # tail /var/log/syslog
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.581279] nf_defrag_ipv6: disagrees about version of symbol inet_frags_fini
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.589607] nf_defrag_ipv6: Unknown symbol inet_frags_fini (err -22)
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.597927] nf_defrag_ipv6: disagrees about version of symbol inet_frag_find
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.606184] nf_defrag_ipv6: Unknown symbol inet_frag_find (err -22)
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.614288] nf_defrag_ipv6: disagrees about version of symbol ip6_expire_frag_queue
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.623245] nf_defrag_ipv6: Unknown symbol ip6_expire_frag_queue (err -22)
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.632006] nf_defrag_ipv6: Unknown symbol pskb_trim_rcsum_slow (err 0)
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.640055] nf_defrag_ipv6: disagrees about version of symbol inet_frag_kill
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.648380] nf_defrag_ipv6: Unknown symbol inet_frag_kill (err -22)
    Mar  1 08:41:07 ge-frontend001 kernel: [ 1306.656774] xt_conntrack: cannot load conntrack support for proto=10

It does not look like the kernel was updated -- there only one kernel version on the VM ("4.9.0-8-amd64") so I don't have an easy explanation for this.

Anyway, a reboot seems to fix the issue.  I'll investigate further if this is a known issue with Debian 9.

**Comment by riccardomurri** [comment]
So it looks like the issue comes from updating the kernel:

1. If I boot up a VM on GCP with the current Debian 9 "stretch" image, and use `ip6tables-restore` on the netfilter rules file installed by ElastiCluster, everything works as expected.

2. If I run the package upgrade procedure, I see that the kernel is upgraded but *the kernel version* stays the same::

        $ apt list --upgradable
        [...]
        linux-image-4.9.0-8-amd64/stable-updates 4.9.144-3.1 amd64 [upgradable from: 4.9.130-2]

   This means that files (in particular, modules) from the new kernel will overwrite files from the old kernel.  Hence, no new kernel modules can be loaded until a reboot.

3. Indeed, if I run `apt upgrade` first and *then* I try to load the ip6tables rules, then this fails with exactly the errors reported in my previous comment.

I am a bit surprised that kernel packages are not doing proper versioning (kernel 4.9.x --with varying *x*-- is in a package versioned `4.9.0-8-amd64`); I'll check whether this is recent Debian policy or if it's a problem specific to Google Cloud.

**Comment by riccardomurri** [comment]
I get the same behaviour from the official Debian 9 image on the in-house OpenStack infrastructure, so the issue is not a Google-specific one.

**Comment by riccardomurri** [comment]
Reported to Debian as a bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923522

**Comment by riccardomurri** [comment]
Quick workaround for now is to disallow package upgrades; add this line to your config file in the `[setup/*]` section:

    global_var_upgrade_packages=no

**Comment by riccardomurri** [comment]
I have pushed a workaround to the "master" branch; in my testing it works, but please do re-open the issue if it doesn't.

The `netfilter-persistent` error will now be ignored if the kernel has been upgraded; however, the same root issue with Debian kernel updates can also cause other failures. So a safer option is to reboot the machines if a kernel upgrade took place:

    [setup/...]
    global_var_allow_reboot=yes
    # rest is unchanged ...

Note that rebooting may increase setup times.

**Comment by mducar** [comment]
Thanks Riccardo!  I have it working now also.
