### ISSUE TITLE
use of http without tls

### ISSUE THREAD

**Issue by brokenquark** [gc3-uzh-ch/elasticluster#634]
Greetings,

I am a security researcher, who is looking for security smells in Ansible scripts. I found instances where the HTTP protocol is used instead of HTTPS (HTTP with TLS). According to the Common Weakness Enumeration organization this is a security weakness (https://cwe.mitre.org/data/definitions/319.html). I was wondering why HTTP is used? Is it because of lack of tool support?

I am trying to find out if developers are forced to adopt bad practices due to lack of tool support when it comes to the HTTPS protocol. Maybe it is due to dependency on a resource that uses HTTP?

Any feedback is appreciated.

Source: https://github.com/gc3-uzh-ch/elasticluster/blob/master/elasticluster/share/playbooks/roles/rstudio/tasks/main.yml

**Comment by riccardomurri** [comment]
Many thanks for taking the time to check the Ansible playbooks in ElastiCluster for security issues.

In this case, I think it was just me being a bit sloppy: the HTTPS endpoint is available so I should have used that to download RStudio packages from the start.
