### ISSUE TITLE
Flag for debugging

### ISSUE THREAD

**Issue by loewa** [gc3-uzh-ch/elasticluster#648]
I am currently debugging placement issues on OpenStack. Is it possible to add a flag in order to have the debug output of the API calls to the provider?
Would this issue be useful for other people as well?

**Comment by riccardomurri** [comment]
Fixed in v1.3.dev19 -- many thanks for the suggestion!

You have to use verbosity 4 or more to get a log of all requests from all used modules (e.g., OpenStackSDK, Paramiko, ...); e.g.:

    elasticluster -vvvv start mycluster
