### ISSUE TITLE
Openstack Stein Bad network format: missing 'uuid' 

### ISSUE THREAD

**Issue by lebonez** [gc3-uzh-ch/elasticluster#651]
Installed a fresh stein cluster over the past few weeks. I am getting to the point of testing elasticluster. I am running into this problem. The network_ids is set to the uuid from `openstack network list`. If I print the dict containing net-id before server create it is empty. I am not sure what is going on. Maybe it is a problem in my config?

```
Traceback (most recent call last):
  File "/opt/elasticluster/src/elasticluster/cluster.py", line 580, in _start_node
    node.start()
  File "/opt/elasticluster/src/elasticluster/cluster.py", line 1319, in start
    **self.extra)
  File "/opt/elasticluster/src/elasticluster/providers/openstack.py", line 580, in start_instance
    vm = self.nova_client.servers.create(node_name, image_id, flavor, **vm_start_args)
  File "/opt/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1403, in create
    **boot_kwargs)
  File "/opt/elasticluster/lib/python2.7/site-packages/novaclient/v2/servers.py", line 802, in _boot
    return_raw=return_raw, **kwargs)
  File "/opt/elasticluster/lib/python2.7/site-packages/novaclient/base.py", line 361, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/opt/elasticluster/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 381, in post
    return self.request(url, 'POST', **kwargs)
  File "/opt/elasticluster/lib/python2.7/site-packages/novaclient/client.py", line 83, in request
    raise exceptions.from_response(resp, body, url, method)
BadRequest: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-ede12236-8cf3-425b-82ce-5a5053843b32)
```

```
[cluster/slurm]
cloud=openstack
login=ubuntu
setup=slurm
security_group=default
image_id=813e364b-8aae-4e30-9a16-fec850ac9e98
flavor=m1.medium
frontend_nodes=1
compute_nodes=4
ssh_to=frontend
network_ids=05482f0f-0249-41ba-a40e-669e4fa18437
floating_network_id=43fd8fc4-f3c5-475e-8855-c9d69cc87413
request_floating_ip=yes

[cloud/openstack]
provider=openstack
auth_url=https://host:5000/v3
username=user
password=password
project_name=project
identity_api_version=3
compute_api_version=2

[login/ubuntu]
image_user=ubuntu
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/Downloads/key.pem
user_key_public=~/Downloads/key.pub

[setup/slurm]
provider=ansible
frontend_groups=slurm_master
compute_groups=slurm_worker
```

**Comment by lebonez** [comment]
Here is what I get if I print kwargs and vm_start_args.
```
2019-07-11 15:41:48 jy-ctl01 gc3.elasticluster[3366773] DEBUG Specifying networks for node mycluster-compute003: 
{'local_ssd_interface': 'SCSI', 'local_ssd_count': 0, 'storage_account_type': 'Standard_LRS', 'min_num': 4, 'accelerator_count': 0, 'login': 'ubuntu'}
2019-07-11 15:41:48 jy-ctl01 gc3.elasticluster[3366773] DEBUG Specifying networks for node mycluster-compute004: 
{'nics': [{'net-id': '', 'v4-fixed-ip': ''}], 'key_name': 'elasticluster', 'availability_zone': '', 'security_groups': ['default'], 'userdata': ''}
```

**Comment by riccardomurri** [comment]
Can you post the output of `openstack network list` ?

Also: are you running off the Docker image or did you install from Python sources?  In the latter case, can you please post the output of  `pip freeze` from the virtualenv where you installed ElastiCluster?

**Comment by lebonez** [comment]
Running from source. Let me know if you need anything else. Thanks for the help!

`openstack network list`
```
+--------------------------------------+--------------------+--------------------------------------+
| ID                                   | Name               | Subnets                              |
+--------------------------------------+--------------------+--------------------------------------+
| 05482f0f-0249-41ba-a40e-669e4fa18437 | selfservice-public | 24418985-7597-4eb4-aace-77c57ba0e04e |
| 43fd8fc4-f3c5-475e-8855-c9d69cc87413 | VM-Demand 10       | 61a8edf5-7c37-4a35-ad53-76bdb14ee8a7 |
+--------------------------------------+--------------------+--------------------------------------+
```
`pip freeze`
```
adal==1.2.2
ansible==2.8.2
apache-libcloud==2.5.0
appdirs==1.4.3
asn1crypto==0.24.0
attrs==19.1.0
azure-common==1.1.23
azure-mgmt-compute==5.0.0
azure-mgmt-network==3.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==3.0.0
azure-nspkg==3.0.2
Babel==2.7.0
bcrypt==3.1.7
boto==2.49.0
cachetools==3.1.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cliff==2.15.0
cmd2==0.8.9
coloredlogs==10.0
contextlib2==0.5.5
cryptography==2.7
debtcollector==1.21.0
decorator==4.4.0
dogpile.cache==0.7.1
-e git://github.com/gc3-uzh-ch/elasticluster.git@02dea092468ec9d5377da8b16cddcf8bd0ae0ba0#egg=elasticluster
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.17.1
futures==3.2.0
google-api-python-client==1.7.9
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-compute-engine==2.8.13
httplib2==0.13.0
humanfriendly==4.18
idna==2.8
ipaddress==1.0.22
iso8601==0.1.12
isodate==0.6.0
Jinja2==2.10.1
jmespath==0.9.4
jsonpatch==1.23
jsonpointer==2.0
jsonschema==3.0.1
keystoneauth1==3.14.0
MarkupSafe==1.1.1
monotonic==1.5
msgpack==0.6.1
msrest==0.6.8
msrestazure==0.6.1
munch==2.3.2
netaddr==0.7.19
netifaces==0.10.9
oauth2client==4.1.3
oauthlib==3.0.2
openstacksdk==0.31.1
os-client-config==1.32.0
os-service-types==1.7.0
osc-lib==1.13.0
oslo.config==6.11.0
oslo.context==2.22.1
oslo.i18n==3.23.1
oslo.log==3.44.0
oslo.serialization==2.29.1
oslo.utils==3.41.0
paramiko==2.6.0
pathlib2==2.3.4
pbr==5.4.0
prettytable==0.7.2
pyasn1==0.4.5
pyasn1-modules==0.2.5
pyCLI==2.0.3
pycparser==2.19
pycrypto==2.6.1
pyinotify==0.9.6
PyJWT==1.7.1
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyperclip==1.7.0
pyrsistent==0.15.3
python-cinderclient==4.2.1
python-dateutil==2.8.0
python-gflags==3.1.2
python-glanceclient==2.16.0
python-keystoneclient==3.19.0
python-neutronclient==6.12.0
python-novaclient==9.1.2
pytz==2019.1
PyYAML==5.1.1
requests==2.22.0
requests-oauthlib==1.2.0
requestsexceptions==1.4.0
rfc3986==1.3.2
rsa==4.0
scandir==1.10.0
schema==0.7.0
SecretStorage==2.3.1
simplejson==3.16.0
six==1.12.0
stevedore==1.30.1
subprocess32==3.5.4
typing==3.7.4
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.25.3
warlock==1.3.3
wcwidth==0.1.7
wrapt==1.11.2
```

**Comment by riccardomurri** [comment]
This might be something related to the interaction of OpenStack "Stein" and "novaclient==9.1.2", as I cannot reproduce it with out in-house cloud (which is still at the "M" release if I'm not mistaken).

Can you please try upgrading novaclient and see if it works?  This should do it::

    pip install --upgrade python-keystoneclient python-novaclient python-neutronclient python-glanceclient

or just re-create the virtualenv where you installed ElastiCluster.

**Comment by lebonez** [comment]
I will do some more digging but that didn't seem to help still giving missing uuid. It must be something in my config because it isn't even passing the uuid from the config file.

**Comment by riccardomurri** [comment]
My guess would be that you have some old `.pyc` files around, which are picked instead of the latest sources; the issues you're describing seem to be something that was present in an unfortunate series of commits a couple months ago but has been fixed in the "master" branch.

Can you please try installing ElastiCluster afresh in a newly-created virtualenv?

**Comment by lebonez** [comment]
I had never used elasticluster before so it was relatively new install. I reinstalled with the upgrades you mentioned after modifying the requirements files so that it would allow the upgrade still to no avail. I'm going to close this and assume I am missing something in the config. I'll mess with the code a bit to find where the uuid is falling out. Thanks for the help!

**Comment by riccardomurri** [comment]
I'm still not sure what direction I could suggest you look into... If you could get me a test account on your OS "Stein" deployment, I can try running my own ElastiCluster install and see if I can reproduce the error.

**Comment by lebonez** [comment]
Okay so I installed it on my local arch linux machine and it worked. It did fail on the floating ip part but I'll figure that out (error below). I was originally running it on centos 7 where the stein controller was installed and it failed. I installed it on a fairly fresh centos 7 server that is only running a ceph nfs server without any openstack packages installed and it worked failing on the same floating ip part. So I don't think it is necessary or realistic to fix the failure in running directly on any openstack stein nodes. I am curious if it works running directly on a controller in your in house openstack cluster.

I am curious why it is trying to create the floating ip on the network_ids config portion rather then the floating_network_id.
 
```
Could not start node `compute004`: Failed allocating floating IP on network 05482f0f-0249-41ba-a40e-669e4fa18437: Bad floatingip request: Network 05482f0f-0249-41ba-a40e-669e4fa18437 is not a valid external network
```

Thanks for the help.

**Comment by riccardomurri** [comment]
If it doesn't work on your controller nodes, then I would guess that the problem is in the client libraries: since the controller nodes run OS "Stein", they will also have the "Stein" version of OpenStackSDK.  My guess would then be that the OpenStack SDK/client libraries have some backwards incompatibility which causes this error.

Can you try running off the Dockerized version of ElastiCluster (`elasticluster.sh`, see: https://elasticluster.readthedocs.io/en/latest/install.html#quickstart ) and tell me if *that* one shows the same problem?
