### ISSUE TITLE
ERROR In section `login/ubuntu`: Key 'user_key_private' error: readable_file('/home/centos/.ssh/id_rsa') raised ValueError('cannot read file `/home/centos/.ssh/id_rsa`',)

### ISSUE THREAD

**Issue by karthikvemula** [gc3-uzh-ch/elasticluster#652]
ERROR In section `login/ubuntu`: Key 'user_key_private' error:
readable_file('/home/centos/.ssh/id_rsa') raised ValueError('cannot read file `/home/centos/.ssh/id_rsa`',)

**Comment by riccardomurri** [comment]
It looks like you pointed ElastiCluster to a file it cannot read.  Can you please post the output of these two commands?

    whoami
    ls -l /home/centos/.ssh/id_rsa

**Comment by karthikvemula** [comment]
problem solved
