### ISSUE TITLE
ERROR Could not start node `compute001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-53155e08-5c95-461b-b662-27896f703de9) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>

### ISSUE THREAD

**Issue by karthikvemula** [gc3-uzh-ch/elasticluster#653]
ERROR Could not start node `compute001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-53155e08-5c95-461b-b662-27896f703de9) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>

**Comment by riccardomurri** [comment]
Quite lilely, you didn't load the OpenStack credentials in the environment.  Have you sourced your "openrc" file?

**Comment by karthikvemula** [comment]
plz send me slurm on openstack  exact configuration file not genral configuration file

**Comment by riccardomurri** [comment]
There's no such thing as a "general configuration file".  ElastiCluster is designed to work with many cloud providers and many types of clusters so it's impossible to have one single configuration...  There's however a section in the manual detailing all possible configuration options: https://elasticluster.readthedocs.io/en/latest/configure.html

**Comment by riccardomurri** [comment]
Sorry I misread your last comment.  You can use this example as a starting point for a SLURM on OpenStack: https://github.com/gc3-uzh-ch/elasticluster/blob/master/examples/slurm.conf

**Comment by karthikvemula** [comment]
WARNING ImportWarning: Not importing directory '/u/rahuls/py2.7.5_env/lib/python2.7/site-packages/oslo_i18n/locale': missing __init__.py
Starting cluster `rahuls_ec` with:
* 1 frontend nodes.
* 1 compute nodes.
(This may take a while...)
Configuring the cluster ...
(this too may take a while)
/u/rahuls/py2.7.5_env/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,

PLAY [Prepare VM for running Ansible] *******************************************************************************************************************************************************

TASK [Ensure Python is installed] ***********************************************************************************************************************************************************
fatal: [compute001]: FAILED! => {"msg": "Missing sudo password"}
fatal: [frontend001]: FAILED! => {"msg": "Missing sudo password"}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************
compute001                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
frontend001                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

2019-07-22 00:45:39 us01-engaudit-vm gc3.elasticluster[9188] ERROR Command `ansible-playbook --private-key=/u/rahuls/.ssh/id_rsa /remote/ecishome1/rahuls/py2.7.5_env/elasticluster/src/elasticluster/share/playbooks/main.yml --inventory=/u/rahuls/.elasticluster/storage/rahuls_ec.inventory -e @extra_vars.yml` failed with exit code 2.
2019-07-22 00:45:39 us01-engaudit-vm gc3.elasticluster[9188] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2019-07-22 00:45:39 us01-engaudit-vm gc3.elasticluster[9188] WARNING Cluster `rahuls_ec` not yet configured. Please, re-run `elasticluster setup rahuls_ec` and/or check your configuration
