### ISSUE TITLE
gc3.elasticluster[19601] ERROR Could not start node `frontend001`: 'int' object has no attribute 'encode' -- <class 'AttributeError'>

### ISSUE THREAD

**Issue by karthikvemula** [gc3-uzh-ch/elasticluster#654]
gc3.elasticluster[19601] ERROR Could not start node `frontend001`: 'int' object has no attribute 'encode' -- <class 'AttributeError'>

**Comment by riccardomurri** [comment]
Looks like the same as #655 -- can you please post the same info that I requested of them?

**Comment by karthikvemula** [comment]
yes same error

**Comment by riccardomurri** [comment]
Ok, then let's continue discussion on #655.
