### ISSUE TITLE
fails while ansible task "Ensure Python is installed"

### ISSUE THREAD

**Issue by rahuls1071** [gc3-uzh-ch/elasticluster#656]
Elasticluster fails while trying to setup gridengine module. Always fails in "Ensure Python is installed" task. 
Please help

Below is the part of output of "elasticluster -vvv start gridengine -n rahuls_rootec"

PLAYBOOK: main.yml ***********************************************************************************************************************************************************************
52 plays in /remote/ecishome1/rahuls/py2.7.5_env/elasticluster/src/elasticluster/share/playbooks/main.yml

PLAY [Prepare VM for running Ansible] ****************************************************************************************************************************************************
META: ran handlers

TASK [Ensure Python is installed] ********************************************************************************************************************************************************
task path: /remote/ecishome1/rahuls/py2.7.5_env/elasticluster/src/elasticluster/share/playbooks/main.yml:6
fatal: [frontend001]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 70, "stderr": "Shared connection to 10.13.240.149 closed.\r\n", "stderr_lines": ["Shared connection to 10.13.240.149 closed."], "stdout": "install-py2.sh: ERROR: Binary wrapper '/usr/bin/eatmydata' not found, even after installation. Aborting.\r\n", "stdout_lines": ["install-py2.sh: ERROR: Binary wrapper '/usr/bin/eatmydata' not found, even after installation. Aborting."]}
fatal: [compute001]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 70, "stderr": "Shared connection to 10.13.240.159 closed.\r\n", "stderr_lines": ["Shared connection to 10.13.240.159 closed."], "stdout": "install-py2.sh: ERROR: Binary wrapper '/usr/bin/eatmydata' not found, even after installation. Aborting.\r\n", "stdout_lines": ["install-py2.sh: ERROR: Binary wrapper '/usr/bin/eatmydata' not found, even after installation. Aborting."]}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************
compute001                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
frontend001                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

2019-07-22 07:49:39 us01-engaudit-vm gc3.elasticluster[19418] ERROR Command `ansible-playbook --private-key=/root/.ssh/id_rsa /remote/ecishome1/rahuls/py2.7.5_env/elasticluster/src/elasticluster/share/playbooks/main.yml --inventory=/root/.elasticluster/storage/rahuls_rootec.inventory --become --become-user=root -vv -e @extra_vars.yml` failed with exit code 2.
2019-07-22 07:49:39 us01-engaudit-vm gc3.elasticluster[19418] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2019-07-22 07:49:39 us01-engaudit-vm gc3.elasticluster[19418] WARNING Cluster `rahuls_rootec` not yet configured. Please, re-run `elasticluster setup rahuls_rootec` and/or check your configuration

WARNING: YOUR CLUSTER `rahuls_rootec` IS NOT READY YET!

Cluster name:     rahuls_rootec
Cluster template: gridengine
Default ssh to node: frontend001
- frontend nodes: 1
- compute nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh rahuls_rootec

To upload or download files to the cluster, use the command:

    elasticluster sftp rahuls_rootec

Config FIle is as below

[cluster/gridengine]
cloud=openstack
login=rahuls
setup=gridengine
security_group=default
image_id=a9071db2-b1dc-4567-8f2f-20538715321c
network_ids=586de15c-31b9-4b62-b060-9178d47a83c1
flavor=s1.medium
frontend_nodes=1
compute_nodes=1
ssh_to=frontend

[cloud/openstack]
provider=openstack
auth_url=http://<host>:5000/v3
identity_api_version=3
user_domain_name=<user_domain>
project_domain_name=<prj_domain>
username=rahuls
password=<pswd>
project_name=itcloud
region_name=RegionOne

[login/rahuls]
image_user=root
image_sudo=True
user_key_name=elasticlusterroot
user_key_private=~/.ssh/id_rsa
user_key_public=~/.ssh/id_rsa.pub

[setup/gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker

[setup/ansible]
ansible_sudo_password=<pwd>

**Comment by riccardomurri** [comment]
What kind of OS is in the base image `image_id=a9071db2-b1dc-4567-8f2f-20538715321c` ?

**Comment by rahuls1071** [comment]
> What kind of OS is in the base image `image_id=a9071db2-b1dc-4567-8f2f-20538715321c` ?

It is CentOS6.6 OS

**Comment by riccardomurri** [comment]
Indeed, there was an issue with upper/lower case of the distribution ID (`CentOS` vs `Centos`).  Should be fixed in the latest "master".  Please update and try again.

Many thanks for finding and reporting this bug!
