### ISSUE TITLE
Problem to use with Openstack deployment

### ISSUE THREAD

**Issue by wfang** [gc3-uzh-ch/elasticluster#69]
I tried to use the elasticluster to work with one OpenStack Grizzly deployment. 

I can confirm that I have made the change in the .elasticluster/config file and use the correct keys and EC2 endpoints. These key and end point are confirmed to work, as I can use the euca2ools to access the cloud.

I don't know whether it is a boto issue or just the API mismatch between AWS EC2 and openstack. 

Here is the error message I got:

gaierror: (8, 'nodename nor servname provided, or not known')

Any idea what's went wrong?

Appendix:
Here is the stacktrack:
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py(525)__bootstrap()
-> self.__bootstrap_inner()
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py(552)__bootstrap_inner()
-> self.run()
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py(505)run()
-> self.__target(_self.__args, *_self.__kwargs)
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py(96)worker()
-> result = (True, func(_args, *_kwds))
  /Library/Python/2.7/site-packages/elasticluster/cluster.py(145)start_node()
-> node.start()
  /Library/Python/2.7/site-packages/elasticluster/cluster.py(446)start()
-> self.flavor, self.image, self.image_userdata)
  /Library/Python/2.7/site-packages/elasticluster/providers/ec2_boto.py(116)start_instance()
-> self._check_keypair(key_name, public_key_path, private_key_path)
  /Library/Python/2.7/site-packages/elasticluster/providers/ec2_boto.py(194)_check_keypair()
-> keypairs = connection.get_all_key_pairs()
  /Library/Python/2.7/site-packages/boto/ec2/connection.py(2207)get_all_key_pairs()
-> [('item', KeyPair)], verb='POST')
  /Library/Python/2.7/site-packages/boto/connection.py(1064)get_list()
-> response = self.make_request(action, params, path, verb)
  /Library/Python/2.7/site-packages/boto/connection.py(1010)make_request()
-> return self._mexe(http_request)

> /Library/Python/2.7/site-packages/boto/connection.py(865)_mexe()
> -> request.body, request.headers)
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py(955)request()
> -> self._send_request(method, url, body, headers)
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py(989)_send_request()
> -> self.endheaders(body)
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py(951)endheaders()
> -> self._send_output(message_body)
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py(811)_send_output()
> -> self.send(msg)
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py(773)send()
> -> self.connect()
>   /Library/Python/2.7/site-packages/boto/https_connection.py(111)connect()
> -> sock.connect((self.host, self.port))
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py(224)meth()
> -> return getattr(self._sock,name)(*args)

**Comment by riccardomurri** [comment]
No updates since 5 years, so I'm assuming the issue is fixed or no longer relevant.
